export type FusionCategory =
  | "Asian-Latin Fusion"
  | "New American Staples"
  | "European-Asian Fusion"
  | "Indian-Western Fusion"
  | "Middle Eastern & Global Fusion";

export interface FusionDish {
  id: string;
  name: string;
  category: FusionCategory;
  originStory: string;
  ingredients: string[];
  instructions: string[];
  image: string;
  sourceUrl: string;
  supabaseId?: string;
}

export const FUSION_DISHES: FusionDish[] = [
  // ── Asian-Latin Fusion ──
  {
    id: "korean-tacos",
    name: "Korean Tacos",
    category: "Asian-Latin Fusion",
    originStory: "Born on the streets of Los Angeles by Korean-American food trucks, these tacos marry gochujang-marinated bulgogi with the hand-held convenience of Mexican street food.",
    ingredients: ["beef short ribs","gochujang","soy sauce","sesame oil","garlic","ginger","corn tortillas","kimchi","cilantro","lime"],
    instructions: ["Marinate sliced beef in gochujang, soy sauce, sesame oil, garlic and ginger for 2 hours.","Grill over high heat until caramelised.","Warm tortillas, fill with beef, kimchi, cilantro and a squeeze of lime."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/korean-tacos",
  },
  {
    id: "sushi-burrito",
    name: "Sushi Burrito",
    category: "Asian-Latin Fusion",
    originStory: "San Francisco's Sushirrito pioneered this oversized handheld wrapping sushi rice and Japanese fillings in a full nori sheet, eating like a burrito.",
    ingredients: ["sushi rice","nori sheets","salmon","avocado","cucumber","mango","sriracha mayo","ginger","soy sauce","sesame seeds"],
    instructions: ["Cook and season sushi rice.","Lay nori flat, spread rice leaving a 2 cm border.","Layer salmon, avocado, cucumber and mango.","Drizzle sriracha mayo, roll tightly and slice in half."],
    image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/sushi-burrito",
  },
  {
    id: "nikkei-ceviche",
    name: "Nikkei Ceviche",
    category: "Asian-Latin Fusion",
    originStory: "Japanese immigrants in 1800s Peru adapted their sashimi traditions to local citrus and chilli, creating this bright leche de tigre with soy and miso undertones.",
    ingredients: ["sea bass","lime juice","soy sauce","white miso","ginger","aji amarillo","red onion","coriander","sesame oil","nori strips"],
    instructions: ["Dice sea bass, toss with lime juice and cure 5 minutes.","Mix miso, soy, ginger and aji amarillo into the tiger milk.","Fold in onion and coriander, garnish with nori."],
    image: "https://images.unsplash.com/photo-1535400255456-984e3b4dfd7c?w=600&q=80",
    sourceUrl: "https://www.foodnetwork.com/nikkei-ceviche",
  },
  {
    id: "ramen-burger",
    name: "Ramen Burger",
    category: "Asian-Latin Fusion",
    originStory: "New York chef Keizo Shimamoto replaced bread buns with crisped ramen noodle patties, creating a viral dish that treats ramen as both structure and flavour.",
    ingredients: ["ramen noodles","egg","beef patty","soy glaze","arugula","shoyu tare","scallions","sesame oil","nori","burger cheese"],
    instructions: ["Cook ramen, drain and mix with egg.","Press into ring moulds and pan-fry until golden.","Grill beef patty, assemble with arugula, cheese and soy glaze between ramen buns."],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/ramen-burger",
  },
  {
    id: "mochi-donuts",
    name: "Mochi Donuts",
    category: "Asian-Latin Fusion",
    originStory: "Hawaii's Malasada shops evolved these chewy ring donuts by blending mochiko rice flour with classic Portuguese deep-fry dough, giving them their signature bounce.",
    ingredients: ["mochiko rice flour","all-purpose flour","sugar","baking powder","egg","milk","butter","matcha powder","white chocolate","sprinkles"],
    instructions: ["Mix flours, sugar and baking powder.","Add egg, milk and melted butter to form a sticky dough.","Shape into rings and deep fry at 170C until puffed and golden.","Dip in melted white chocolate tinted with matcha."],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/mochi-donuts",
  },
  {
    id: "bulgogi-quesadilla",
    name: "Bulgogi Quesadilla",
    category: "Asian-Latin Fusion",
    originStory: "LA's Korean-Mexican diaspora pressed sweet soy bulgogi and gooey jack cheese inside crisp flour tortillas, turning two pantry staples into one irresistible snack.",
    ingredients: ["beef bulgogi","flour tortillas","Monterey jack cheese","kimchi","green onions","sesame oil","sour cream","sriracha","gochujang","lime"],
    instructions: ["Cook bulgogi until caramelised.","Place tortilla in pan, scatter cheese, bulgogi and chopped kimchi.","Fold and press until golden and melted.","Serve with sriracha sour cream."],
    image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=600&q=80",
    sourceUrl: "https://www.delish.com/bulgogi-quesadilla",
  },
  {
    id: "matcha-churros",
    name: "Matcha Churros",
    category: "Asian-Latin Fusion",
    originStory: "Tokyo theme parks began dusting their churros with ceremonial-grade matcha, creating a bittersweet jade-green twist on the Spanish-Mexican deep-fried dough.",
    ingredients: ["choux pastry dough","matcha powder","sugar","vegetable oil","white chocolate","heavy cream","vanilla","cinnamon","salt","milk"],
    instructions: ["Prepare choux dough and pipe into hot oil.","Fry 3 minutes until crisp.","Toss in matcha-sugar mixture.","Serve with white chocolate dipping sauce."],
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=600&q=80",
    sourceUrl: "https://www.japanesecooking101.com/matcha-churros",
  },
  {
    id: "tamale-sushi",
    name: "Tamale Sushi Roll",
    category: "Asian-Latin Fusion",
    originStory: "Chicago chefs discovered that masa dough can be rolled inside nori just like sushi rice, creating a corn-forward vehicle for jalapeno tuna and avocado.",
    ingredients: ["masa harina","tuna","jalapeno","avocado","nori","lime zest","chipotle mayo","cucumber","cilantro","sesame seeds"],
    instructions: ["Press hydrated masa onto nori.","Layer tuna, jalapeno, avocado and cucumber.","Roll tightly using a sushi mat, refrigerate 20 minutes.","Slice and drizzle with chipotle mayo."],
    image: "https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/tamale-sushi",
  },
  {
    id: "causa-sushi",
    name: "Causa Sushi",
    category: "Asian-Latin Fusion",
    originStory: "Lima Nikkei restaurants layer aji amarillo yellow potato causa between sashimi slices instead of rice, fusing Peru's beloved causa terrine with Japanese aesthetics.",
    ingredients: ["yellow potatoes","aji amarillo paste","lime juice","tuna sashimi","avocado","mayonnaise","coriander","nori","sesame","soy"],
    instructions: ["Mash potatoes with aji amarillo, lime and salt.","Press into ring mould, add tuna and avocado layer.","Top with second potato layer and unmould.","Garnish with sesame and micro coriander."],
    image: "https://images.unsplash.com/photo-1617196034096-2186592e2f79?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/causa-sushi",
  },
  {
    id: "kimchi-empanadas",
    name: "Kimchi Empanadas",
    category: "Asian-Latin Fusion",
    originStory: "Korean settlers in Chile folded their fermented cabbage into empanada dough alongside pork and gochujang, marrying two cultures that both love stuffed pastries.",
    ingredients: ["empanada dough","kimchi","ground pork","gochujang","soy sauce","garlic","green onion","sesame oil","egg wash","cumin"],
    instructions: ["Saute pork with kimchi, gochujang, soy and garlic.","Fill dough rounds, crimp edges.","Brush with egg wash and bake at 200C for 20 minutes."],
    image: "https://images.unsplash.com/photo-1604152135912-04a022e23696?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/kimchi-empanadas",
  },
  // ── New American Staples ──
  {
    id: "lobster-mac-cheese",
    name: "Lobster Mac and Cheese",
    category: "New American Staples",
    originStory: "New England steakhouses elevated the American comfort classic by folding sweet lobster knuckle meat into a gruyere-cheddar bechamel, making mac and cheese fine dining.",
    ingredients: ["macaroni","lobster tail","gruyere","sharp cheddar","butter","flour","whole milk","dijon mustard","breadcrumbs","chives"],
    instructions: ["Cook pasta al dente.","Make bechamel with butter, flour and milk, melt in both cheeses.","Fold in chopped lobster and pasta.","Top with buttered breadcrumbs and bake at 190C for 20 minutes."],
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/lobster-mac-cheese",
  },
  {
    id: "avocado-toast-benedict",
    name: "Avocado Toast Benedict",
    category: "New American Staples",
    originStory: "Brunch culture merged California avocado toast with classic Eggs Benedict, drizzling hollandaise over smashed avocado and a poached egg on sourdough.",
    ingredients: ["sourdough bread","ripe avocado","poached eggs","hollandaise sauce","red chilli flakes","lemon juice","everything bagel seasoning","prosciutto","baby greens","sea salt"],
    instructions: ["Toast sourdough, smash avocado with lemon and season.","Poach eggs to soft set.","Layer avocado and egg on toast, drizzle hollandaise.","Finish with chilli flakes and seasoning."],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/avocado-benedict",
  },
  {
    id: "smash-burger",
    name: "Smash Burger",
    category: "New American Staples",
    originStory: "The smash technique presses a beef ball onto a screaming-hot griddle to maximise the Maillard crust, pioneered by Steak n Shake and perfected by craft burger joints.",
    ingredients: ["80/20 beef mince","American cheese","potato bun","yellow mustard","brined gherkins","raw white onion","ketchup","mayonnaise","lettuce","beef tallow"],
    instructions: ["Form loose 85g beef balls.","Smash onto screaming-hot cast iron with a heavy spatula.","Immediately season and top with cheese.","Serve on toasted bun with condiments."],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/smash-burger",
  },
  {
    id: "birria-tacos",
    name: "Birria Tacos",
    category: "New American Staples",
    originStory: "Jalisco's birria stew crossed the border and evolved into LA's quesabirria: corn tortillas dipped in rich beef consomme, pan-crisped with cheese and braised beef.",
    ingredients: ["beef short rib","guajillo chillies","ancho chillies","cinnamon","cloves","corn tortillas","oaxaca cheese","white onion","cilantro","lime"],
    instructions: ["Braise beef with rehydrated chillies and spices 3-4 hours.","Shred beef, reserve consomme.","Dip tortillas in consomme, crisp in pan with cheese.","Fill with beef, top with onion and cilantro.","Serve with consomme for dipping."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.foodnetwork.com/birria-tacos",
  },
  {
    id: "nashville-hot-chicken",
    name: "Nashville Hot Chicken Sandwich",
    category: "New American Staples",
    originStory: "Nashville's Prince's Hot Chicken Shack created a cayenne-lard paste dish that became America's most copied sandwich, landing on every fast-food menu by 2020.",
    ingredients: ["chicken thighs","buttermilk","cayenne pepper","flour","brown sugar","garlic powder","lard","brioche bun","brined gherkins","coleslaw"],
    instructions: ["Brine chicken in seasoned buttermilk overnight.","Dredge in seasoned flour and fry at 175C.","Mix cayenne paste with hot fry oil and brush on chicken.","Serve on brioche with gherkins and coleslaw."],
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/nashville-hot-chicken",
  },
  {
    id: "brunch-shakshuka",
    name: "American Brunch Shakshuka",
    category: "New American Staples",
    originStory: "Middle Eastern shakshuka landed in NYC's brunch scene where it absorbed kale, feta and sourdough, becoming a fixture on every Brooklyn menu.",
    ingredients: ["eggs","crushed tomatoes","bell peppers","onion","garlic","smoked paprika","cumin","kale","feta cheese","sourdough"],
    instructions: ["Saute onion, peppers and garlic.","Add spices and tomatoes, simmer 10 minutes.","Stir in kale, make wells and crack in eggs.","Cover and cook until whites set.","Top with feta and serve with sourdough."],
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/brunch-shakshuka",
  },
  {
    id: "bbq-brisket-banh-mi",
    name: "BBQ Brisket Banh Mi",
    category: "New American Staples",
    originStory: "Texas pitmasters near Houston's Vietnamese quarter began filling French-Vietnamese baguettes with smoked brisket and daikon, creating an unexpected regional classic.",
    ingredients: ["smoked brisket","baguette","daikon","carrot","jalapeno","cilantro","hoisin sauce","sriracha mayo","cucumber","lime"],
    instructions: ["Slice brisket thin.","Mix hoisin with sriracha for sauce.","Fill toasted baguette with brisket, veg, jalapeno and cilantro.","Drizzle sauce, add cucumber."],
    image: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/brisket-banh-mi",
  },
  // ── European-Asian Fusion ──
  {
    id: "rasta-pasta",
    name: "Rasta Pasta",
    category: "European-Asian Fusion",
    originStory: "A Jamaican-Italian mashup that stirs jerk seasoning and scotch bonnet into an Italian cream sauce, coloured with three-bell-pepper rasta stripes.",
    ingredients: ["penne pasta","jerk seasoning","red bell pepper","yellow bell pepper","green bell pepper","heavy cream","garlic","scotch bonnet","thyme","parmesan"],
    instructions: ["Cook pasta. Saute peppers and garlic.","Add cream, jerk seasoning and scotch bonnet.","Toss pasta in sauce, finish with parmesan."],
    image: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/rasta-pasta",
  },
  {
    id: "gyoza-pierogi",
    name: "Gyoza Pierogi",
    category: "European-Asian Fusion",
    originStory: "Polish-Japanese fusion chefs discovered that pierogi dough holds gyoza fillings beautifully, resulting in pan-fried dumplings with crispy bottoms and a potato-cheese heart.",
    ingredients: ["pierogi dough","pork mince","napa cabbage","soy sauce","ginger","garlic","mashed potato","quark cheese","chives","sesame oil"],
    instructions: ["Fill pierogi discs with pork, cabbage and seasoning.","Seal edges, boil 3 minutes.","Pan-fry in butter until golden bottomed.","Serve with sour cream and chives."],
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/gyoza-pierogi",
  },
  {
    id: "miso-carbonara",
    name: "Miso Carbonara",
    category: "European-Asian Fusion",
    originStory: "Tokyo trattorie replaced guanciale with Japanese smoky bacon and stirred white miso into the egg yolk base, deepening the umami of the Roman classic.",
    ingredients: ["spaghetti","white miso","egg yolks","pecorino","Japanese bacon","black pepper","sake","pasta water","nori","toasted sesame"],
    instructions: ["Cook pasta. Fry bacon until crisp.","Whisk egg yolks with miso, pecorino and pepper.","Toss hot pasta with bacon, remove from heat.","Add egg mixture with pasta water, stirring vigorously."],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/miso-carbonara",
  },
  {
    id: "thai-basil-pizza",
    name: "Thai Basil Pizza",
    category: "European-Asian Fusion",
    originStory: "Australian-Asian fusion restaurants replaced tomato base with peanut sauce and topped Neapolitan dough with Thai basil chicken, fish sauce caramel and lime zest.",
    ingredients: ["pizza dough","peanut sauce","chicken breast","Thai basil","fish sauce","lime juice","red chilli","mozzarella","bean sprouts","crushed peanuts"],
    instructions: ["Spread peanut sauce on stretched dough.","Top with mozzarella and marinated chicken.","Bake at 250C for 8-10 minutes.","Finish with fresh basil, bean sprouts, lime and peanuts."],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/thai-basil-pizza",
  },
  {
    id: "kimchi-risotto",
    name: "Kimchi Risotto",
    category: "European-Asian Fusion",
    originStory: "Milan-based Korean chefs used arborio rice and the slow stir of Italian risotto technique with kimchi brine as the broth, creating an electrifyingly funky first course.",
    ingredients: ["arborio rice","kimchi","kimchi brine","parmesan","butter","shallot","white wine","chicken stock","sesame oil","toasted nori"],
    instructions: ["Saute shallot, toast rice.","Add wine then ladle stock, stirring continuously.","Halfway through, add kimchi brine instead of stock.","Finish with butter, parmesan and chopped kimchi.","Drizzle sesame oil."],
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/kimchi-risotto",
  },
  {
    id: "teriyaki-crepes",
    name: "Teriyaki Crepes",
    category: "European-Asian Fusion",
    originStory: "Harajuku crepe stalls in Tokyo wrap French-style delicate crepes around teriyaki chicken, avocado and lettuce, eaten as street food in paper cones.",
    ingredients: ["crepe batter","chicken breast","teriyaki sauce","avocado","lettuce","mayonnaise","red cabbage","sesame seeds","spring onion","nori strip"],
    instructions: ["Cook thin crepes. Grill chicken with teriyaki sauce.","Lay crepe flat, add mayo, lettuce, chicken and avocado.","Roll into cone, secure with nori strip."],
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&q=80",
    sourceUrl: "https://www.japancentre.com/teriyaki-crepes",
  },
  {
    id: "bao-burger",
    name: "Bao Burger",
    category: "European-Asian Fusion",
    originStory: "London's Bao restaurant placed pulled pork belly inside cloud-soft steamed Taiwanese bao buns, simultaneously launching a street-food trend and redefining the British burger.",
    ingredients: ["steamed bao buns","pork belly","hoisin sauce","cucumber","peanut powder","coriander","garlic","five spice","brown sugar","rice vinegar"],
    instructions: ["Braise pork belly with hoisin, five spice, garlic and sugar until tender.","Shred pork. Steam bao buns.","Fill with pork, cucumber and peanut powder.","Garnish with coriander."],
    image: "https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/bao-burger",
  },
  {
    id: "matcha-tiramisu",
    name: "Matcha Tiramisu",
    category: "European-Asian Fusion",
    originStory: "Italian pastry chefs in Kyoto swapped espresso for ceremonial matcha, soaking ladyfingers in bitter green tea and dusting with kinako instead of cocoa.",
    ingredients: ["ladyfinger biscuits","matcha powder","mascarpone","eggs","sugar","cream","kinako","sake","vanilla","white chocolate"],
    instructions: ["Brew strong matcha, cool and add sake.","Whip mascarpone with egg yolks and sugar.","Fold in whipped cream.","Dip ladyfingers in matcha, layer with cream.","Dust with kinako and white chocolate shavings."],
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/matcha-tiramisu",
  },
  // ── Indian-Western Fusion ──
  {
    id: "naan-pizza",
    name: "Naan Pizza",
    category: "Indian-Western Fusion",
    originStory: "British curry houses discovered that tandoor-blistered naan makes a perfect pizza base: charred, chewy and ready in minutes, loaded with tikka masala sauce.",
    ingredients: ["naan bread","tikka masala sauce","paneer","mozzarella","red onion","bell peppers","coriander","chaat masala","lime","chilli flakes"],
    instructions: ["Spread tikka sauce on naan.","Top with mozzarella, paneer and vegetables.","Bake at 220C for 8 minutes.","Finish with fresh coriander and chaat masala."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/naan-pizza",
  },
  {
    id: "butter-chicken-poutine",
    name: "Butter Chicken Poutine",
    category: "Indian-Western Fusion",
    originStory: "Toronto's Indian-Canadian diaspora replaced poutine gravy with murgh makhani sauce, demonstrating that cheese curds and butter chicken are a surprisingly perfect marriage.",
    ingredients: ["fries","cheese curds","butter chicken sauce","chicken breast","cream","tomato passata","garam masala","fenugreek","ginger","coriander"],
    instructions: ["Make butter chicken sauce.","Fry or bake fries until crisp.","Heap fries with cheese curds, pour hot butter chicken over.","Garnish with coriander."],
    image: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=600&q=80",
    sourceUrl: "https://www.foodnetwork.com/butter-chicken-poutine",
  },
  {
    id: "dosa-quesadilla",
    name: "Dosa Quesadilla",
    category: "Indian-Western Fusion",
    originStory: "Bay Area South Indian restaurants fold masala dosa filling inside a wheat quesadilla with melted pepper jack, served with coconut chutney as salsa.",
    ingredients: ["flour tortillas","potato","onion","mustard seeds","curry leaves","turmeric","pepper jack cheese","coconut chutney","sambar","coriander"],
    instructions: ["Make masala potato filling.","Place tortilla in pan, add cheese and potato filling.","Fold and cook until cheese melts and tortilla crisps.","Serve with coconut chutney."],
    image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=600&q=80",
    sourceUrl: "https://www.delish.com/dosa-quesadilla",
  },
  {
    id: "tandoori-chicken-tacos",
    name: "Tandoori Chicken Tacos",
    category: "Indian-Western Fusion",
    originStory: "Mumbai food trucks adapted the taco format for Indian flavours, placing charred tandoori chicken inside corn tortillas with mint chutney standing in for salsa verde.",
    ingredients: ["chicken thighs","yoghurt","tandoori spice mix","corn tortillas","mint chutney","red onion","cucumber","mango","chaat masala","lime"],
    instructions: ["Marinate chicken in yoghurt and spices overnight.","Grill until charred and cooked through.","Warm tortillas, fill with sliced chicken.","Top with mint chutney, cucumber and red onion."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/tandoori-tacos",
  },
  {
    id: "masala-mac-cheese",
    name: "Masala Mac and Cheese",
    category: "Indian-Western Fusion",
    originStory: "London's curry-belt fusion movement stirred garam masala and caramelised onion into bechamel cheese sauce, heating mac and cheese with Indian spice layering.",
    ingredients: ["macaroni","cheddar","cream","garam masala","turmeric","caramelised onion","green chilli","butter","panko breadcrumbs","coriander"],
    instructions: ["Cook pasta. Make spiced bechamel with cheese and garam masala.","Fold in pasta and caramelised onion.","Top with spiced breadcrumbs and bake."],
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/masala-mac-cheese",
  },
  {
    id: "chicken-tikka-pasta",
    name: "Chicken Tikka Pasta",
    category: "Indian-Western Fusion",
    originStory: "British comfort food culture married the nation's favourite Indian takeaway with penne in a tikka-spiced tomato cream sauce, going viral on TikTok in 2021.",
    ingredients: ["penne","chicken breast","tikka masala paste","cream","crushed tomatoes","garlic","ginger","bell pepper","coriander","parmesan"],
    instructions: ["Marinate and grill chicken in tikka paste.","Saute garlic and ginger, add paste and tomatoes.","Add cream, simmer. Toss in pasta and sliced chicken.","Garnish with coriander."],
    image: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80",
    sourceUrl: "https://www.delish.com/chicken-tikka-pasta",
  },
  {
    id: "curry-grilled-cheese",
    name: "Curry Grilled Cheese",
    category: "Indian-Western Fusion",
    originStory: "New York Indian-American sandwich shops spread mango chutney and curry-spiced caramelised onions inside a classic grilled cheese, bridging a diner and a chaat stall.",
    ingredients: ["sourdough bread","gruyere","mango chutney","curry powder","caramelised onion","jalapeno","butter","coriander","apple","dijon mustard"],
    instructions: ["Caramelise onion with curry powder.","Spread mango chutney on one slice, mustard on other.","Fill with gruyere, onion and jalapeno.","Butter outside, grill until golden."],
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/curry-grilled-cheese",
  },
  // ── Middle Eastern & Global Fusion ──
  {
    id: "shakshuka-pizza",
    name: "Shakshuka Pizza",
    category: "Middle Eastern & Global Fusion",
    originStory: "Tel Aviv bakeries began cracking eggs into hollows of flatbread topped with spiced tomato sauce, merging shakshuka's drama with pizza's communal eating ritual.",
    ingredients: ["pizza dough","crushed tomatoes","red pepper","harissa","cumin","eggs","feta","zaatar","olive oil","fresh mint"],
    instructions: ["Stretch dough, spread tomato harissa base.","Make wells in sauce.","Bake 5 minutes at 250C, crack in eggs.","Return to oven 4-5 minutes until whites set.","Finish with feta, zaatar and mint."],
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/shakshuka-pizza",
  },
  {
    id: "falafel-burger",
    name: "Falafel Burger",
    category: "Middle Eastern & Global Fusion",
    originStory: "Berlin's street food scene placed crispy falafel inside brioche buns, dressing them with tahini instead of mayo and preserved turnips instead of gherkins.",
    ingredients: ["falafel patty","brioche bun","tahini sauce","hummus","preserved turnip","tomato","rocket","cucumber","sumac","lemon"],
    instructions: ["Deep fry or pan-fry falafel.","Toast bun and spread hummus on bottom.","Layer rocket, tomato, falafel and turnip.","Drizzle tahini, sprinkle sumac."],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/falafel-burger",
  },
  {
    id: "zaatar-focaccia",
    name: "Zaatar Focaccia",
    category: "Middle Eastern & Global Fusion",
    originStory: "Italian-Lebanese bakeries replaced rosemary with zaatar and drizzled generous pools of olive oil into focaccia dimples, creating a herb bread that belongs to both traditions.",
    ingredients: ["bread flour","zaatar","olive oil","salt","yeast","water","olives","cherry tomatoes","sea salt flakes","sumac"],
    instructions: ["Make focaccia dough, let rise.","Press into oiled tin, dimple generously.","Scatter zaatar, olives and tomatoes into dimples.","Drizzle olive oil and bake at 220C for 20-25 minutes."],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/zaatar-focaccia",
  },
  {
    id: "harissa-lamb-tacos",
    name: "Harissa Lamb Tacos",
    category: "Middle Eastern & Global Fusion",
    originStory: "Sydney's Middle Eastern-Mexican fusion trucks marinate lamb shoulder in North African harissa before slow-roasting it shawarma-style and serving in corn tortillas with tahini.",
    ingredients: ["lamb shoulder","harissa","cumin","coriander","corn tortillas","tahini","sumac onions","mint","pomegranate seeds","yoghurt"],
    instructions: ["Rub lamb with harissa and spices, slow-roast 4 hours.","Pull meat and rest.","Fill warmed tortillas with lamb.","Top with sumac onions, mint and pomegranate.","Drizzle tahini."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/harissa-lamb-tacos",
  },
  {
    id: "mujaddara-bowl",
    name: "Mujaddara Bowl",
    category: "Middle Eastern & Global Fusion",
    originStory: "NYC's grain bowl trend adopted Lebanon's ancient lentil-rice dish and dressed it with crispy chickpeas, tahini drizzle and turmeric-roasted cauliflower.",
    ingredients: ["green lentils","basmati rice","caramelised onion","cauliflower","tahini","chickpeas","cumin","lemon","parsley","pomegranate molasses"],
    instructions: ["Cook lentils with cumin, fold in cooked rice.","Roast cauliflower and chickpeas with turmeric.","Serve mujaddara topped with roasted veg.","Drizzle tahini and pomegranate molasses."],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/mujaddara-bowl",
  },
  {
    id: "persian-tahdig-bowl",
    name: "Tahdig Buddha Bowl",
    category: "Middle Eastern & Global Fusion",
    originStory: "LA's Persian-fusion cafes placed the sacred golden crust of Persian tahdig at the base of a modern Buddha bowl, surrounding the crispy rice with roasted vegetables.",
    ingredients: ["basmati rice","saffron","yoghurt","roasted vegetables","chickpeas","fresh herbs","pomegranate","barberries","pistachios","rose water dressing"],
    instructions: ["Make tahdig: line pot with oiled yoghurt-rice, steam until golden.","Roast seasonal vegetables.","Unmould tahdig, arrange veg, chickpeas and herbs around.","Drizzle rose water dressing and scatter barberries."],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/tahdig-bowl",
  },
  {
    id: "labneh-toast",
    name: "Labneh Toast",
    category: "Middle Eastern & Global Fusion",
    originStory: "London's Middle Eastern cafes swapped avocado for labneh: strained yoghurt so thick it holds toppings, dressed with dukkah and honey on sourdough.",
    ingredients: ["sourdough bread","labneh","dukkah","honey","zaatar","cucumber","cherry tomatoes","fresh mint","olive oil","sea salt"],
    instructions: ["Toast sourdough.","Spread thick labneh generously.","Top with cucumber, tomatoes and mint.","Sprinkle dukkah and zaatar, drizzle honey and olive oil."],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/labneh-toast",
  },
  {
    id: "sumac-salmon-pasta",
    name: "Sumac Salmon Pasta",
    category: "Middle Eastern & Global Fusion",
    originStory: "Stockholm chefs combined cold-smoked salmon with pasta and a sumac-tahini cream sauce, bringing Levantine tartness to a Scandinavian-Italian collision.",
    ingredients: ["linguine","cold-smoked salmon","sumac","tahini","cream","lemon","capers","dill","garlic","crispy shallots"],
    instructions: ["Cook pasta. Make sauce with tahini, cream, lemon and sumac.","Toss pasta in sauce.","Top with smoked salmon, capers and dill.","Garnish with crispy shallots."],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/sumac-salmon-pasta",
  },
  {
    id: "halloumi-tacos",
    name: "Halloumi Tacos",
    category: "Middle Eastern & Global Fusion",
    originStory: "Vegetarian fusion chefs replaced carne asada with grilled slabs of squeaky halloumi in corn tortillas, dressing them with harissa salsa and pomegranate.",
    ingredients: ["halloumi","corn tortillas","harissa","pomegranate seeds","red cabbage","mint yoghurt","lime","cumin","smoked paprika","rocket"],
    instructions: ["Slice halloumi and grill until golden.","Warm tortillas.","Fill with halloumi, red cabbage and rocket.","Top with harissa, pomegranate and mint yoghurt.","Squeeze lime."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.delish.com/halloumi-tacos",
  },
  {
    id: "turkish-eggs-brunch",
    name: "Turkish Eggs Brunch Bowl",
    category: "Middle Eastern & Global Fusion",
    originStory: "A 15th-century Ottoman court dish called cilbir: poached eggs on garlicky yoghurt with chilli butter, became a 2020s global brunch staple after landing on London menus.",
    ingredients: ["eggs","Greek yoghurt","garlic","butter","Aleppo pepper","white wine vinegar","sourdough bread","dill","sumac","olive oil"],
    instructions: ["Poach eggs in vinegared water.","Whip yoghurt with garlic and salt.","Brown butter with Aleppo pepper.","Spoon yoghurt into bowl, place eggs on top.","Pour sizzling butter over, garnish with dill."],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/cilbir",
  },
];

export const FUSION_CATEGORIES: FusionCategory[] = [
  "Asian-Latin Fusion",
  "New American Staples",
  "European-Asian Fusion",
  "Indian-Western Fusion",
  "Middle Eastern & Global Fusion",
];

export const CULINARY_BRIDGES = [
  { location: "Georgia (Caucasus)", bridge: "Eastern Europe — Middle East — Central Asia", dish: "Khachapuri", description: "Sitting at the crossroads of three culinary worlds, Georgia absorbs walnut-rich Persian aromatics, Slavic bread traditions and Central Asian spice routes into one singular cuisine." },
  { location: "Philippines", bridge: "Southeast Asia — Spain — China", dish: "Adobo", description: "Three centuries of Spanish colonialism layered over indigenous Austronesian cooking, with Fujianese traders adding vinegar-soy braising techniques to create Southeast Asia's most eclectic table." },
  { location: "Maghreb", bridge: "North Africa — Arab World — France", dish: "Bastilla", description: "Berber grain traditions, Arab spice caravans and French pastry precision converge in couscous and filo pastry alike, making Morocco one of the world's richest culinary crossroads." },
  { location: "Peru", bridge: "Inca — Spain — Japan — China", dish: "Ceviche", description: "The Andean civilisation's potato and quinoa heritage absorbed Spanish citrus, Chinese stir-fry technique and Japanese precision into a uniquely layered South American tradition." },
  { location: "Malta", bridge: "Italy — North Africa — Arab", dish: "Pastizzi", description: "This tiny Mediterranean island accumulated Sicilian pasta culture, Moorish spice influence and British pub traditions into a kitchen that punches far above its geographic weight." },
  { location: "Uzbekistan", bridge: "Persia — China — Russia", dish: "Plov", description: "Straddling the Silk Road, Uzbek cooking fused Persian pilaf and aromatics, Chinese noodle techniques and Russian dairy traditions into plov: the world's most travelled rice dish." },
  { location: "Mauritius and Reunion", bridge: "Africa — India — France — China", dish: "Dholl Puri", description: "These Indian Ocean islands fused African staples, South Indian spice traditions, French Creole cooking and Fujianese Chinese techniques into one of the world's most diverse island cuisines." },
];
