export type FusionCategory =
  | "Asian-Latin Fusion"
  | "New American Staples"
  | "European-Asian Fusion"
  | "Indian-Western Fusion"
  | "Middle Eastern & Global Fusion";

export interface FusionDish {
  id: string;
  name: string;
  category: FusionCategory;
  originStory: string;
  ingredients: string[];
  instructions: string[];
  image: string;
  sourceUrl: string;
  supabaseId?: string;
  // Parity fields
  prepTime?: number;
  cookTime?: number;
  servings?: number;
  difficulty?: "easy" | "medium" | "hard";
  dietaryTags?: string[];
  calories?: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  structuredIngredients?: { name: string; amount?: number | null; unit?: string | null }[];
  // Intelligence fields
  flavorBridge?: string[];
  heritage?: [string, string];
  substitutions?: { swap: string; for: string }[];
}

export const FUSION_DISHES: FusionDish[] = [
  // ── Asian-Latin Fusion ──
  {
    id: "korean-tacos",
    name: "Korean Tacos",
    category: "Asian-Latin Fusion",
    originStory: "Born on the streets of Los Angeles by Korean-American food trucks, these tacos marry gochujang-marinated bulgogi with the hand-held convenience of Mexican street food.",
    ingredients: ["beef short ribs","gochujang","soy sauce","sesame oil","garlic","ginger","corn tortillas","kimchi","cilantro","lime"],
    instructions: ["Marinate sliced beef in gochujang, soy sauce, sesame oil, garlic and ginger for 2 hours.","Grill over high heat until caramelised.","Warm tortillas, fill with beef, kimchi, cilantro and a squeeze of lime."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/korean-tacos",
    prepTime: 130, cookTime: 10, servings: 4, difficulty: "medium",
    dietaryTags: ["dairy-free"],
    calories: 480, protein: 32, carbs: 38, fat: 18,
    structuredIngredients: [
      { name: "beef short ribs", amount: 500, unit: "g" },
      { name: "gochujang", amount: 3, unit: "tbsp" },
      { name: "soy sauce", amount: 2, unit: "tbsp" },
      { name: "sesame oil", amount: 1, unit: "tbsp" },
      { name: "garlic", amount: 4, unit: "cloves" },
      { name: "ginger", amount: 2, unit: "cm" },
      { name: "corn tortillas", amount: 8, unit: null },
      { name: "kimchi", amount: 100, unit: "g" },
      { name: "cilantro", amount: null, unit: null },
      { name: "lime", amount: 1, unit: null },
    ],
    flavorBridge: ["gochujang heat + lime acid", "sesame umami + corn earthiness"],
    heritage: ["Korean", "Mexican"],
    substitutions: [{ swap: "jackfruit", for: "beef short ribs" }, { swap: "lettuce cups", for: "corn tortillas" }],
  },
  {
    id: "sushi-burrito",
    name: "Sushi Burrito",
    category: "Asian-Latin Fusion",
    originStory: "San Francisco's Sushirrito pioneered this oversized handheld wrapping sushi rice and Japanese fillings in a full nori sheet, eating like a burrito.",
    ingredients: ["sushi rice","nori sheets","salmon","avocado","cucumber","mango","sriracha mayo","ginger","soy sauce","sesame seeds"],
    instructions: ["Cook and season sushi rice.","Lay nori flat, spread rice leaving a 2 cm border.","Layer salmon, avocado, cucumber and mango.","Drizzle sriracha mayo, roll tightly and slice in half."],
    image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/sushi-burrito",
    prepTime: 30, cookTime: 20, servings: 2, difficulty: "medium",
    dietaryTags: ["gluten-free", "dairy-free"],
    calories: 520, protein: 28, carbs: 65, fat: 16,
    structuredIngredients: [
      { name: "sushi rice", amount: 300, unit: "g" },
      { name: "nori sheets", amount: 2, unit: null },
      { name: "salmon", amount: 200, unit: "g" },
      { name: "avocado", amount: 1, unit: null },
      { name: "cucumber", amount: 0.5, unit: null },
      { name: "mango", amount: 0.5, unit: null },
      { name: "sriracha mayo", amount: 2, unit: "tbsp" },
      { name: "pickled ginger", amount: 30, unit: "g" },
      { name: "soy sauce", amount: 2, unit: "tbsp" },
      { name: "sesame seeds", amount: 1, unit: "tsp" },
    ],
    flavorBridge: ["rice vinegar + mango sweetness", "sriracha heat + avocado fat"],
    heritage: ["Japanese", "Mexican"],
    substitutions: [{ swap: "tofu", for: "salmon" }, { swap: "brown rice", for: "sushi rice" }],
  },
  {
    id: "nikkei-ceviche",
    name: "Nikkei Ceviche",
    category: "Asian-Latin Fusion",
    originStory: "Japanese immigrants in 1800s Peru adapted their sashimi traditions to local citrus and chilli, creating this bright leche de tigre with soy and miso undertones.",
    ingredients: ["sea bass","lime juice","soy sauce","white miso","ginger","aji amarillo","red onion","coriander","sesame oil","nori strips"],
    instructions: ["Dice sea bass, toss with lime juice and cure 5 minutes.","Mix miso, soy, ginger and aji amarillo into the tiger milk.","Fold in onion and coriander, garnish with nori."],
    image: "https://images.unsplash.com/photo-1535400255456-984e3b4dfd7c?w=600&q=80",
    sourceUrl: "https://www.foodnetwork.com/nikkei-ceviche",
    prepTime: 20, cookTime: 0, servings: 4, difficulty: "easy",
    dietaryTags: ["gluten-free", "dairy-free"],
    calories: 180, protein: 22, carbs: 8, fat: 7,
    structuredIngredients: [
      { name: "sea bass", amount: 400, unit: "g" },
      { name: "lime juice", amount: 80, unit: "ml" },
      { name: "soy sauce", amount: 1, unit: "tbsp" },
      { name: "white miso", amount: 1, unit: "tsp" },
      { name: "ginger", amount: 1, unit: "cm" },
      { name: "aji amarillo", amount: 1, unit: "tsp" },
      { name: "red onion", amount: 0.5, unit: null },
      { name: "coriander", amount: null, unit: null },
      { name: "sesame oil", amount: 1, unit: "tsp" },
      { name: "nori strips", amount: null, unit: null },
    ],
    flavorBridge: ["miso umami + citrus acid", "aji amarillo heat + sesame oil richness"],
    heritage: ["Japanese", "Peruvian"],
    substitutions: [{ swap: "scallops", for: "sea bass" }, { swap: "yuzu juice", for: "lime juice" }],
  },
  {
    id: "ramen-burger",
    name: "Ramen Burger",
    category: "Asian-Latin Fusion",
    originStory: "New York chef Keizo Shimamoto replaced bread buns with crisped ramen noodle patties, creating a viral dish that treats ramen as both structure and flavour.",
    ingredients: ["ramen noodles","egg","beef patty","soy glaze","arugula","shoyu tare","scallions","sesame oil","nori","burger cheese"],
    instructions: ["Cook ramen, drain and mix with egg.","Press into ring moulds and pan-fry until golden.","Grill beef patty, assemble with arugula, cheese and soy glaze between ramen buns."],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/ramen-burger",
    prepTime: 20, cookTime: 15, servings: 2, difficulty: "medium",
    dietaryTags: [],
    calories: 650, protein: 38, carbs: 55, fat: 28,
    structuredIngredients: [
      { name: "ramen noodles", amount: 200, unit: "g" },
      { name: "egg", amount: 2, unit: null },
      { name: "beef patty", amount: 200, unit: "g" },
      { name: "soy glaze", amount: 2, unit: "tbsp" },
      { name: "arugula", amount: 30, unit: "g" },
      { name: "shoyu tare", amount: 1, unit: "tbsp" },
      { name: "scallions", amount: 2, unit: null },
      { name: "sesame oil", amount: 1, unit: "tsp" },
      { name: "nori", amount: 1, unit: "sheet" },
      { name: "burger cheese", amount: 2, unit: "slices" },
    ],
    flavorBridge: ["soy glaze caramel + beef char", "ramen starch crust + sesame aroma"],
    heritage: ["Japanese", "American"],
    substitutions: [{ swap: "portobello mushroom", for: "beef patty" }, { swap: "udon noodles", for: "ramen noodles" }],
  },
  {
    id: "mochi-donuts",
    name: "Mochi Donuts",
    category: "Asian-Latin Fusion",
    originStory: "Hawaii's Malasada shops evolved these chewy ring donuts by blending mochiko rice flour with classic Portuguese deep-fry dough, giving them their signature bounce.",
    ingredients: ["mochiko rice flour","all-purpose flour","sugar","baking powder","egg","milk","butter","matcha powder","white chocolate","sprinkles"],
    instructions: ["Mix flours, sugar and baking powder.","Add egg, milk and melted butter to form a sticky dough.","Shape into rings and deep fry at 170C until puffed and golden.","Dip in melted white chocolate tinted with matcha."],
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/mochi-donuts",
    prepTime: 30, cookTime: 20, servings: 12, difficulty: "medium",
    dietaryTags: ["vegetarian"],
    calories: 220, protein: 4, carbs: 34, fat: 9,
    structuredIngredients: [
      { name: "mochiko rice flour", amount: 150, unit: "g" },
      { name: "all-purpose flour", amount: 100, unit: "g" },
      { name: "sugar", amount: 80, unit: "g" },
      { name: "baking powder", amount: 1, unit: "tsp" },
      { name: "egg", amount: 2, unit: null },
      { name: "milk", amount: 120, unit: "ml" },
      { name: "butter", amount: 60, unit: "g" },
      { name: "matcha powder", amount: 2, unit: "tbsp" },
      { name: "white chocolate", amount: 100, unit: "g" },
      { name: "sprinkles", amount: null, unit: null },
    ],
    flavorBridge: ["mochiko chewiness + choux crunch", "matcha bitterness + white chocolate sweetness"],
    heritage: ["Japanese", "Portuguese"],
    substitutions: [{ swap: "ube powder", for: "matcha powder" }, { swap: "dark chocolate", for: "white chocolate" }],
  },
  {
    id: "bulgogi-quesadilla",
    name: "Bulgogi Quesadilla",
    category: "Asian-Latin Fusion",
    originStory: "LA's Korean-Mexican diaspora pressed sweet soy bulgogi and gooey jack cheese inside crisp flour tortillas, turning two pantry staples into one irresistible snack.",
    ingredients: ["beef bulgogi","flour tortillas","Monterey jack cheese","kimchi","green onions","sesame oil","sour cream","sriracha","gochujang","lime"],
    instructions: ["Cook bulgogi until caramelised.","Place tortilla in pan, scatter cheese, bulgogi and chopped kimchi.","Fold and press until golden and melted.","Serve with sriracha sour cream."],
    image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=600&q=80",
    sourceUrl: "https://www.delish.com/bulgogi-quesadilla",
    prepTime: 15, cookTime: 10, servings: 2, difficulty: "easy",
    dietaryTags: [],
    calories: 560, protein: 34, carbs: 42, fat: 26,
    structuredIngredients: [
      { name: "beef bulgogi", amount: 200, unit: "g" },
      { name: "flour tortillas", amount: 4, unit: null },
      { name: "Monterey jack cheese", amount: 120, unit: "g" },
      { name: "kimchi", amount: 80, unit: "g" },
      { name: "green onions", amount: 3, unit: null },
      { name: "sesame oil", amount: 1, unit: "tsp" },
      { name: "sour cream", amount: 60, unit: "ml" },
      { name: "sriracha", amount: 1, unit: "tsp" },
      { name: "gochujang", amount: 1, unit: "tsp" },
      { name: "lime", amount: 1, unit: null },
    ],
    flavorBridge: ["sweet soy bulgogi + tangy kimchi", "melted jack cheese + gochujang heat"],
    heritage: ["Korean", "Mexican"],
    substitutions: [{ swap: "mushrooms", for: "beef bulgogi" }, { swap: "cheddar", for: "Monterey jack" }],
  },
  {
    id: "matcha-churros",
    name: "Matcha Churros",
    category: "Asian-Latin Fusion",
    originStory: "Tokyo theme parks began dusting their churros with ceremonial-grade matcha, creating a bittersweet jade-green twist on the Spanish-Mexican deep-fried dough.",
    ingredients: ["choux pastry dough","matcha powder","sugar","vegetable oil","white chocolate","heavy cream","vanilla","cinnamon","salt","milk"],
    instructions: ["Prepare choux dough and pipe into hot oil.","Fry 3 minutes until crisp.","Toss in matcha-sugar mixture.","Serve with white chocolate dipping sauce."],
    image: "https://images.unsplash.com/photo-1516100882582-96c3a05fe590?w=600&q=80",
    sourceUrl: "https://www.japanesecooking101.com/matcha-churros",
    prepTime: 20, cookTime: 15, servings: 6, difficulty: "medium",
    dietaryTags: ["vegetarian"],
    calories: 280, protein: 5, carbs: 38, fat: 13,
    structuredIngredients: [
      { name: "choux pastry dough", amount: 250, unit: "g" },
      { name: "matcha powder", amount: 3, unit: "tbsp" },
      { name: "sugar", amount: 60, unit: "g" },
      { name: "vegetable oil", amount: 500, unit: "ml" },
      { name: "white chocolate", amount: 100, unit: "g" },
      { name: "heavy cream", amount: 60, unit: "ml" },
      { name: "vanilla", amount: 1, unit: "tsp" },
      { name: "cinnamon", amount: 0.5, unit: "tsp" },
      { name: "salt", amount: null, unit: null },
      { name: "milk", amount: 120, unit: "ml" },
    ],
    flavorBridge: ["matcha vegetal bitterness + choux butter", "white chocolate fat + cinnamon warmth"],
    heritage: ["Japanese", "Spanish"],
    substitutions: [{ swap: "black sesame", for: "matcha powder" }, { swap: "dark chocolate ganache", for: "white chocolate" }],
  },
  {
    id: "tamale-sushi",
    name: "Tamale Sushi Roll",
    category: "Asian-Latin Fusion",
    originStory: "Chicago chefs discovered that masa dough can be rolled inside nori just like sushi rice, creating a corn-forward vehicle for jalapeno tuna and avocado.",
    ingredients: ["masa harina","tuna","jalapeno","avocado","nori","lime zest","chipotle mayo","cucumber","cilantro","sesame seeds"],
    instructions: ["Press hydrated masa onto nori.","Layer tuna, jalapeno, avocado and cucumber.","Roll tightly using a sushi mat, refrigerate 20 minutes.","Slice and drizzle with chipotle mayo."],
    image: "https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/tamale-sushi",
    prepTime: 40, cookTime: 5, servings: 4, difficulty: "hard",
    dietaryTags: ["dairy-free"],
    calories: 310, protein: 18, carbs: 42, fat: 8,
    structuredIngredients: [
      { name: "masa harina", amount: 200, unit: "g" },
      { name: "tuna", amount: 150, unit: "g" },
      { name: "jalapeno", amount: 1, unit: null },
      { name: "avocado", amount: 1, unit: null },
      { name: "nori", amount: 4, unit: "sheets" },
      { name: "lime zest", amount: 1, unit: "tsp" },
      { name: "chipotle mayo", amount: 3, unit: "tbsp" },
      { name: "cucumber", amount: 0.5, unit: null },
      { name: "cilantro", amount: null, unit: null },
      { name: "sesame seeds", amount: 1, unit: "tsp" },
    ],
    flavorBridge: ["masa corn sweetness + nori brine", "chipotle smoke + tuna richness"],
    heritage: ["Mexican", "Japanese"],
    substitutions: [{ swap: "salmon", for: "tuna" }, { swap: "roasted sweet potato", for: "avocado" }],
  },
  {
    id: "causa-sushi",
    name: "Causa Sushi",
    category: "Asian-Latin Fusion",
    originStory: "Lima Nikkei restaurants layer aji amarillo yellow potato causa between sashimi slices instead of rice, fusing Peru's beloved causa terrine with Japanese aesthetics.",
    ingredients: ["yellow potatoes","aji amarillo paste","lime juice","tuna sashimi","avocado","mayonnaise","coriander","nori","sesame","soy"],
    instructions: ["Mash potatoes with aji amarillo, lime and salt.","Press into ring mould, add tuna and avocado layer.","Top with second potato layer and unmould.","Garnish with sesame and micro coriander."],
    image: "https://images.unsplash.com/photo-1617196034096-2186592e2f79?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/causa-sushi",
    prepTime: 45, cookTime: 0, servings: 4, difficulty: "hard",
    dietaryTags: ["gluten-free", "dairy-free"],
    calories: 290, protein: 20, carbs: 36, fat: 9,
    structuredIngredients: [
      { name: "yellow potatoes", amount: 400, unit: "g" },
      { name: "aji amarillo paste", amount: 2, unit: "tbsp" },
      { name: "lime juice", amount: 2, unit: "tbsp" },
      { name: "tuna sashimi", amount: 150, unit: "g" },
      { name: "avocado", amount: 1, unit: null },
      { name: "mayonnaise", amount: 2, unit: "tbsp" },
      { name: "coriander", amount: null, unit: null },
      { name: "nori", amount: 2, unit: "sheets" },
      { name: "sesame", amount: 1, unit: "tsp" },
      { name: "soy sauce", amount: 1, unit: "tbsp" },
    ],
    flavorBridge: ["aji amarillo heat + potato starch", "sashimi fat + citrus brightness"],
    heritage: ["Peruvian", "Japanese"],
    substitutions: [{ swap: "crab", for: "tuna sashimi" }, { swap: "sriracha", for: "aji amarillo paste" }],
  },
  {
    id: "kimchi-empanadas",
    name: "Kimchi Empanadas",
    category: "Asian-Latin Fusion",
    originStory: "Korean settlers in Chile folded their fermented cabbage into empanada dough alongside pork and gochujang, marrying two cultures that both love stuffed pastries.",
    ingredients: ["empanada dough","kimchi","ground pork","gochujang","soy sauce","garlic","green onion","sesame oil","egg wash","cumin"],
    instructions: ["Saute pork with kimchi, gochujang, soy and garlic.","Fill dough rounds, crimp edges.","Brush with egg wash and bake at 200C for 20 minutes."],
    image: "https://images.unsplash.com/photo-1604152135912-04a022e23696?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/kimchi-empanadas",
    prepTime: 30, cookTime: 20, servings: 8, difficulty: "medium",
    dietaryTags: ["dairy-free"],
    calories: 340, protein: 18, carbs: 38, fat: 14,
    structuredIngredients: [
      { name: "empanada dough", amount: 400, unit: "g" },
      { name: "kimchi", amount: 150, unit: "g" },
      { name: "ground pork", amount: 200, unit: "g" },
      { name: "gochujang", amount: 2, unit: "tbsp" },
      { name: "soy sauce", amount: 1, unit: "tbsp" },
      { name: "garlic", amount: 3, unit: "cloves" },
      { name: "green onion", amount: 3, unit: null },
      { name: "sesame oil", amount: 1, unit: "tsp" },
      { name: "egg wash", amount: 1, unit: null },
      { name: "cumin", amount: 0.5, unit: "tsp" },
    ],
    flavorBridge: ["kimchi funk + pork fat", "gochujang heat + cumin earthiness"],
    heritage: ["Korean", "Chilean"],
    substitutions: [{ swap: "tofu", for: "ground pork" }, { swap: "gyoza wrappers", for: "empanada dough" }],
  },
  // ── New American Staples ──
  {
    id: "lobster-mac-cheese",
    name: "Lobster Mac and Cheese",
    category: "New American Staples",
    originStory: "New England steakhouses elevated the American comfort classic by folding sweet lobster knuckle meat into a gruyere-cheddar bechamel, making mac and cheese fine dining.",
    ingredients: ["macaroni","lobster tail","gruyere","sharp cheddar","butter","flour","whole milk","dijon mustard","breadcrumbs","chives"],
    instructions: ["Cook pasta al dente.","Make bechamel with butter, flour and milk, melt in both cheeses.","Fold in chopped lobster and pasta.","Top with buttered breadcrumbs and bake at 190C for 20 minutes."],
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/lobster-mac-cheese",
    prepTime: 20, cookTime: 25, servings: 6, difficulty: "medium",
    dietaryTags: [],
    calories: 620, protein: 35, carbs: 58, fat: 28,
    structuredIngredients: [
      { name: "macaroni", amount: 400, unit: "g" },
      { name: "lobster tail", amount: 300, unit: "g" },
      { name: "gruyere", amount: 120, unit: "g" },
      { name: "sharp cheddar", amount: 120, unit: "g" },
      { name: "butter", amount: 60, unit: "g" },
      { name: "flour", amount: 40, unit: "g" },
      { name: "whole milk", amount: 500, unit: "ml" },
      { name: "dijon mustard", amount: 1, unit: "tsp" },
      { name: "breadcrumbs", amount: 80, unit: "g" },
      { name: "chives", amount: null, unit: null },
    ],
    flavorBridge: ["lobster sweetness + gruyere nuttiness", "bechamel richness + dijon bite"],
    heritage: ["New England", "French"],
    substitutions: [{ swap: "langoustine", for: "lobster tail" }, { swap: "gouda", for: "gruyere" }],
  },
  {
    id: "avocado-toast-benedict",
    name: "Avocado Toast Benedict",
    category: "New American Staples",
    originStory: "Brunch culture merged California avocado toast with classic Eggs Benedict, drizzling hollandaise over smashed avocado and a poached egg on sourdough.",
    ingredients: ["sourdough bread","ripe avocado","poached eggs","hollandaise sauce","red chilli flakes","lemon juice","everything bagel seasoning","prosciutto","baby greens","sea salt"],
    instructions: ["Toast sourdough, smash avocado with lemon and season.","Poach eggs to soft set.","Layer avocado and egg on toast, drizzle hollandaise.","Finish with chilli flakes and seasoning."],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/avocado-benedict",
    prepTime: 15, cookTime: 10, servings: 2, difficulty: "medium",
    dietaryTags: ["vegetarian"],
    calories: 520, protein: 18, carbs: 42, fat: 32,
    structuredIngredients: [
      { name: "sourdough bread", amount: 2, unit: "slices" },
      { name: "ripe avocado", amount: 1, unit: null },
      { name: "poached eggs", amount: 2, unit: null },
      { name: "hollandaise sauce", amount: 60, unit: "ml" },
      { name: "red chilli flakes", amount: 0.5, unit: "tsp" },
      { name: "lemon juice", amount: 1, unit: "tsp" },
      { name: "everything bagel seasoning", amount: 1, unit: "tsp" },
      { name: "prosciutto", amount: 40, unit: "g" },
      { name: "baby greens", amount: 30, unit: "g" },
      { name: "sea salt", amount: null, unit: null },
    ],
    flavorBridge: ["avocado fat + hollandaise richness", "poached egg yolk + lemon brightness"],
    heritage: ["Californian", "French"],
    substitutions: [{ swap: "smoked salmon", for: "prosciutto" }, { swap: "pesto drizzle", for: "hollandaise sauce" }],
  },
  {
    id: "smash-burger",
    name: "Smash Burger",
    category: "New American Staples",
    originStory: "The smash technique presses a beef ball onto a screaming-hot griddle to maximise the Maillard crust, pioneered by Steak n Shake and perfected by craft burger joints.",
    ingredients: ["80/20 beef mince","American cheese","potato bun","yellow mustard","brined gherkins","raw white onion","ketchup","mayonnaise","lettuce","beef tallow"],
    instructions: ["Form loose 85g beef balls.","Smash onto screaming-hot cast iron with a heavy spatula.","Immediately season and top with cheese.","Serve on toasted bun with condiments."],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/smash-burger",
    prepTime: 10, cookTime: 8, servings: 2, difficulty: "easy",
    dietaryTags: [],
    calories: 680, protein: 42, carbs: 38, fat: 38,
    structuredIngredients: [
      { name: "80/20 beef mince", amount: 340, unit: "g" },
      { name: "American cheese", amount: 4, unit: "slices" },
      { name: "potato bun", amount: 2, unit: null },
      { name: "yellow mustard", amount: 2, unit: "tsp" },
      { name: "brined gherkins", amount: 4, unit: "slices" },
      { name: "raw white onion", amount: 60, unit: "g" },
      { name: "ketchup", amount: 1, unit: "tbsp" },
      { name: "mayonnaise", amount: 1, unit: "tbsp" },
      { name: "lettuce", amount: 2, unit: "leaves" },
      { name: "beef tallow", amount: 1, unit: "tbsp" },
    ],
    flavorBridge: ["Maillard crust + melted cheese", "gherkin acid + beef fat richness"],
    heritage: ["American", "American"],
    substitutions: [{ swap: "wagyu mince", for: "80/20 beef mince" }, { swap: "brioche bun", for: "potato bun" }],
  },
  {
    id: "birria-tacos",
    name: "Birria Tacos",
    category: "New American Staples",
    originStory: "Jalisco's birria stew crossed the border and evolved into LA's quesabirria: corn tortillas dipped in rich beef consomme, pan-crisped with cheese and braised beef.",
    ingredients: ["beef short rib","guajillo chillies","ancho chillies","cinnamon","cloves","corn tortillas","oaxaca cheese","white onion","cilantro","lime"],
    instructions: ["Braise beef with rehydrated chillies and spices 3-4 hours.","Shred beef, reserve consomme.","Dip tortillas in consomme, crisp in pan with cheese.","Fill with beef, top with onion and cilantro.","Serve with consomme for dipping."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.foodnetwork.com/birria-tacos",
    prepTime: 30, cookTime: 240, servings: 6, difficulty: "hard",
    dietaryTags: ["dairy-free", "gluten-free"],
    calories: 520, protein: 38, carbs: 34, fat: 24,
    structuredIngredients: [
      { name: "beef short rib", amount: 800, unit: "g" },
      { name: "guajillo chillies", amount: 6, unit: null },
      { name: "ancho chillies", amount: 3, unit: null },
      { name: "cinnamon", amount: 1, unit: "stick" },
      { name: "cloves", amount: 4, unit: null },
      { name: "corn tortillas", amount: 12, unit: null },
      { name: "oaxaca cheese", amount: 200, unit: "g" },
      { name: "white onion", amount: 1, unit: null },
      { name: "cilantro", amount: null, unit: null },
      { name: "lime", amount: 2, unit: null },
    ],
    flavorBridge: ["guajillo smoke + beef collagen", "oaxaca melt + consomme dip"],
    heritage: ["Mexican", "American"],
    substitutions: [{ swap: "lamb shoulder", for: "beef short rib" }, { swap: "jack cheese", for: "oaxaca cheese" }],
  },
  {
    id: "nashville-hot-chicken",
    name: "Nashville Hot Chicken Sandwich",
    category: "New American Staples",
    originStory: "Nashville's Prince's Hot Chicken Shack created a cayenne-lard paste dish that became America's most copied sandwich, landing on every fast-food menu by 2020.",
    ingredients: ["chicken thighs","buttermilk","cayenne pepper","flour","brown sugar","garlic powder","lard","brioche bun","brined gherkins","coleslaw"],
    instructions: ["Brine chicken in seasoned buttermilk overnight.","Dredge in seasoned flour and fry at 175C.","Mix cayenne paste with hot fry oil and brush on chicken.","Serve on brioche with gherkins and coleslaw."],
    image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/nashville-hot-chicken",
    prepTime: 480, cookTime: 15, servings: 2, difficulty: "medium",
    dietaryTags: [],
    calories: 720, protein: 44, carbs: 58, fat: 32,
    structuredIngredients: [
      { name: "chicken thighs", amount: 400, unit: "g" },
      { name: "buttermilk", amount: 250, unit: "ml" },
      { name: "cayenne pepper", amount: 2, unit: "tbsp" },
      { name: "flour", amount: 200, unit: "g" },
      { name: "brown sugar", amount: 1, unit: "tbsp" },
      { name: "garlic powder", amount: 1, unit: "tsp" },
      { name: "lard", amount: 500, unit: "ml" },
      { name: "brioche bun", amount: 2, unit: null },
      { name: "brined gherkins", amount: 6, unit: "slices" },
      { name: "coleslaw", amount: 80, unit: "g" },
    ],
    flavorBridge: ["cayenne-lard paste + buttermilk tang", "brioche sweetness + pickle acid"],
    heritage: ["American", "American"],
    substitutions: [{ swap: "chicken breast", for: "chicken thighs" }, { swap: "vegetable oil", for: "lard" }],
  },
  {
    id: "brunch-shakshuka",
    name: "American Brunch Shakshuka",
    category: "New American Staples",
    originStory: "Middle Eastern shakshuka landed in NYC's brunch scene where it absorbed kale, feta and sourdough, becoming a fixture on every Brooklyn menu.",
    ingredients: ["eggs","crushed tomatoes","bell peppers","onion","garlic","smoked paprika","cumin","kale","feta cheese","sourdough"],
    instructions: ["Saute onion, peppers and garlic.","Add spices and tomatoes, simmer 10 minutes.","Stir in kale, make wells and crack in eggs.","Cover and cook until whites set.","Top with feta and serve with sourdough."],
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/brunch-shakshuka",
    prepTime: 10, cookTime: 25, servings: 4, difficulty: "easy",
    dietaryTags: ["vegetarian", "gluten-free"],
    calories: 280, protein: 16, carbs: 22, fat: 14,
    structuredIngredients: [
      { name: "eggs", amount: 6, unit: null },
      { name: "crushed tomatoes", amount: 400, unit: "g" },
      { name: "bell peppers", amount: 2, unit: null },
      { name: "onion", amount: 1, unit: null },
      { name: "garlic", amount: 3, unit: "cloves" },
      { name: "smoked paprika", amount: 1, unit: "tsp" },
      { name: "cumin", amount: 0.5, unit: "tsp" },
      { name: "kale", amount: 60, unit: "g" },
      { name: "feta cheese", amount: 80, unit: "g" },
      { name: "sourdough", amount: 4, unit: "slices" },
    ],
    flavorBridge: ["spiced tomato acidity + egg richness", "kale bitterness + feta brine"],
    heritage: ["Middle Eastern", "American"],
    substitutions: [{ swap: "spinach", for: "kale" }, { swap: "goat cheese", for: "feta cheese" }],
  },
  {
    id: "bbq-brisket-banh-mi",
    name: "BBQ Brisket Banh Mi",
    category: "New American Staples",
    originStory: "Texas pitmasters near Houston's Vietnamese quarter began filling French-Vietnamese baguettes with smoked brisket and daikon, creating an unexpected regional classic.",
    ingredients: ["smoked brisket","baguette","daikon","carrot","jalapeno","cilantro","hoisin sauce","sriracha mayo","cucumber","lime"],
    instructions: ["Slice brisket thin.","Mix hoisin with sriracha for sauce.","Fill toasted baguette with brisket, veg, jalapeno and cilantro.","Drizzle sauce, add cucumber."],
    image: "https://images.unsplash.com/photo-1558030006-450675393462?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/brisket-banh-mi",
    prepTime: 20, cookTime: 10, servings: 2, difficulty: "easy",
    dietaryTags: ["dairy-free"],
    calories: 580, protein: 36, carbs: 52, fat: 22,
    structuredIngredients: [
      { name: "smoked brisket", amount: 300, unit: "g" },
      { name: "baguette", amount: 2, unit: "rolls" },
      { name: "daikon", amount: 80, unit: "g" },
      { name: "carrot", amount: 1, unit: null },
      { name: "jalapeno", amount: 1, unit: null },
      { name: "cilantro", amount: null, unit: null },
      { name: "hoisin sauce", amount: 2, unit: "tbsp" },
      { name: "sriracha mayo", amount: 2, unit: "tbsp" },
      { name: "cucumber", amount: 0.5, unit: null },
      { name: "lime", amount: 1, unit: null },
    ],
    flavorBridge: ["smoked brisket + hoisin sweetness", "pickled daikon crunch + sriracha heat"],
    heritage: ["Texan", "Vietnamese"],
    substitutions: [{ swap: "pulled pork", for: "smoked brisket" }, { swap: "ciabatta", for: "baguette" }],
  },
  // ── European-Asian Fusion ──
  {
    id: "rasta-pasta",
    name: "Rasta Pasta",
    category: "European-Asian Fusion",
    originStory: "A Jamaican-Italian mashup that stirs jerk seasoning and scotch bonnet into an Italian cream sauce, coloured with three-bell-pepper rasta stripes.",
    ingredients: ["penne pasta","jerk seasoning","red bell pepper","yellow bell pepper","green bell pepper","heavy cream","garlic","scotch bonnet","thyme","parmesan"],
    instructions: ["Cook pasta. Saute peppers and garlic.","Add cream, jerk seasoning and scotch bonnet.","Toss pasta in sauce, finish with parmesan."],
    image: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/rasta-pasta",
    prepTime: 10, cookTime: 20, servings: 4, difficulty: "easy",
    dietaryTags: ["vegetarian"],
    calories: 520, protein: 18, carbs: 68, fat: 20,
    structuredIngredients: [
      { name: "penne pasta", amount: 400, unit: "g" },
      { name: "jerk seasoning", amount: 2, unit: "tbsp" },
      { name: "red bell pepper", amount: 1, unit: null },
      { name: "yellow bell pepper", amount: 1, unit: null },
      { name: "green bell pepper", amount: 1, unit: null },
      { name: "heavy cream", amount: 200, unit: "ml" },
      { name: "garlic", amount: 3, unit: "cloves" },
      { name: "scotch bonnet", amount: 0.5, unit: null },
      { name: "thyme", amount: 1, unit: "tsp" },
      { name: "parmesan", amount: 60, unit: "g" },
    ],
    flavorBridge: ["jerk heat + cream richness", "three-pepper sweetness + parmesan umami"],
    heritage: ["Jamaican", "Italian"],
    substitutions: [{ swap: "coconut cream", for: "heavy cream" }, { swap: "rigatoni", for: "penne pasta" }],
  },
  {
    id: "gyoza-pierogi",
    name: "Gyoza Pierogi",
    category: "European-Asian Fusion",
    originStory: "Polish-Japanese fusion chefs discovered that pierogi dough holds gyoza fillings beautifully, resulting in pan-fried dumplings with crispy bottoms and a potato-cheese heart.",
    ingredients: ["pierogi dough","pork mince","napa cabbage","soy sauce","ginger","garlic","mashed potato","quark cheese","chives","sesame oil"],
    instructions: ["Fill pierogi discs with pork, cabbage and seasoning.","Seal edges, boil 3 minutes.","Pan-fry in butter until golden bottomed.","Serve with sour cream and chives."],
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/gyoza-pierogi",
    prepTime: 45, cookTime: 15, servings: 4, difficulty: "hard",
    dietaryTags: [],
    calories: 380, protein: 18, carbs: 48, fat: 14,
    structuredIngredients: [
      { name: "pierogi dough", amount: 300, unit: "g" },
      { name: "pork mince", amount: 150, unit: "g" },
      { name: "napa cabbage", amount: 100, unit: "g" },
      { name: "soy sauce", amount: 2, unit: "tbsp" },
      { name: "ginger", amount: 1, unit: "cm" },
      { name: "garlic", amount: 2, unit: "cloves" },
      { name: "mashed potato", amount: 200, unit: "g" },
      { name: "quark cheese", amount: 80, unit: "g" },
      { name: "chives", amount: null, unit: null },
      { name: "sesame oil", amount: 1, unit: "tsp" },
    ],
    flavorBridge: ["potato starch + pork fat", "soy umami + butter pan crust"],
    heritage: ["Polish", "Japanese"],
    substitutions: [{ swap: "mushrooms", for: "pork mince" }, { swap: "ricotta", for: "quark cheese" }],
  },
  {
    id: "miso-carbonara",
    name: "Miso Carbonara",
    category: "European-Asian Fusion",
    originStory: "Tokyo trattorie replaced guanciale with Japanese smoky bacon and stirred white miso into the egg yolk base, deepening the umami of the Roman classic.",
    ingredients: ["spaghetti","white miso","egg yolks","pecorino","Japanese bacon","black pepper","sake","pasta water","nori","toasted sesame"],
    instructions: ["Cook pasta. Fry bacon until crisp.","Whisk egg yolks with miso, pecorino and pepper.","Toss hot pasta with bacon, remove from heat.","Add egg mixture with pasta water, stirring vigorously."],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/miso-carbonara",
    prepTime: 10, cookTime: 15, servings: 2, difficulty: "medium",
    dietaryTags: ["dairy-free"],
    calories: 580, protein: 26, carbs: 72, fat: 22,
    structuredIngredients: [
      { name: "spaghetti", amount: 200, unit: "g" },
      { name: "white miso", amount: 2, unit: "tbsp" },
      { name: "egg yolks", amount: 4, unit: null },
      { name: "pecorino", amount: 60, unit: "g" },
      { name: "Japanese bacon", amount: 100, unit: "g" },
      { name: "black pepper", amount: 1, unit: "tsp" },
      { name: "sake", amount: 1, unit: "tbsp" },
      { name: "pasta water", amount: 60, unit: "ml" },
      { name: "nori", amount: 1, unit: "sheet" },
      { name: "toasted sesame", amount: 1, unit: "tsp" },
    ],
    flavorBridge: ["miso umami + egg yolk richness", "Japanese bacon smoke + pecorino salt"],
    heritage: ["Japanese", "Italian"],
    substitutions: [{ swap: "pancetta", for: "Japanese bacon" }, { swap: "parmesan", for: "pecorino" }],
  },
  {
    id: "thai-basil-pizza",
    name: "Thai Basil Pizza",
    category: "European-Asian Fusion",
    originStory: "Australian-Asian fusion restaurants replaced tomato base with peanut sauce and topped Neapolitan dough with Thai basil chicken, fish sauce caramel and lime zest.",
    ingredients: ["pizza dough","peanut sauce","chicken breast","Thai basil","fish sauce","lime juice","red chilli","mozzarella","bean sprouts","crushed peanuts"],
    instructions: ["Spread peanut sauce on stretched dough.","Top with mozzarella and marinated chicken.","Bake at 250C for 8-10 minutes.","Finish with fresh basil, bean sprouts, lime and peanuts."],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/thai-basil-pizza",
    prepTime: 20, cookTime: 10, servings: 4, difficulty: "medium",
    dietaryTags: ["dairy-free"],
    calories: 480, protein: 28, carbs: 52, fat: 18,
    structuredIngredients: [
      { name: "pizza dough", amount: 400, unit: "g" },
      { name: "peanut sauce", amount: 80, unit: "ml" },
      { name: "chicken breast", amount: 300, unit: "g" },
      { name: "Thai basil", amount: 20, unit: "g" },
      { name: "fish sauce", amount: 1, unit: "tbsp" },
      { name: "lime juice", amount: 1, unit: "tbsp" },
      { name: "red chilli", amount: 2, unit: null },
      { name: "mozzarella", amount: 150, unit: "g" },
      { name: "bean sprouts", amount: 50, unit: "g" },
      { name: "crushed peanuts", amount: 30, unit: "g" },
    ],
    flavorBridge: ["peanut richness + fish sauce umami", "Thai basil anise + mozzarella melt"],
    heritage: ["Thai", "Italian"],
    substitutions: [{ swap: "tofu", for: "chicken breast" }, { swap: "tahini", for: "peanut sauce" }],
  },
  {
    id: "kimchi-risotto",
    name: "Kimchi Risotto",
    category: "European-Asian Fusion",
    originStory: "Milan-based Korean chefs used arborio rice and the slow stir of Italian risotto technique with kimchi brine as the broth, creating an electrifyingly funky first course.",
    ingredients: ["arborio rice","kimchi","kimchi brine","parmesan","butter","shallot","white wine","chicken stock","sesame oil","toasted nori"],
    instructions: ["Saute shallot, toast rice.","Add wine then ladle stock, stirring continuously.","Halfway through, add kimchi brine instead of stock.","Finish with butter, parmesan and chopped kimchi.","Drizzle sesame oil."],
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/kimchi-risotto",
    prepTime: 10, cookTime: 30, servings: 4, difficulty: "medium",
    dietaryTags: ["vegetarian", "gluten-free"],
    calories: 460, protein: 14, carbs: 68, fat: 16,
    structuredIngredients: [
      { name: "arborio rice", amount: 300, unit: "g" },
      { name: "kimchi", amount: 150, unit: "g" },
      { name: "kimchi brine", amount: 80, unit: "ml" },
      { name: "parmesan", amount: 60, unit: "g" },
      { name: "butter", amount: 40, unit: "g" },
      { name: "shallot", amount: 2, unit: null },
      { name: "white wine", amount: 80, unit: "ml" },
      { name: "chicken stock", amount: 800, unit: "ml" },
      { name: "sesame oil", amount: 1, unit: "tsp" },
      { name: "toasted nori", amount: 1, unit: "sheet" },
    ],
    flavorBridge: ["kimchi brine acid + butter richness", "arborio starch + parmesan umami"],
    heritage: ["Korean", "Italian"],
    substitutions: [{ swap: "vegetable stock", for: "chicken stock" }, { swap: "gochujang", for: "kimchi brine" }],
  },
  {
    id: "teriyaki-crepes",
    name: "Teriyaki Crepes",
    category: "European-Asian Fusion",
    originStory: "Harajuku crepe stalls in Tokyo wrap French-style delicate crepes around teriyaki chicken, avocado and lettuce, eaten as street food in paper cones.",
    ingredients: ["crepe batter","chicken breast","teriyaki sauce","avocado","lettuce","mayonnaise","red cabbage","sesame seeds","spring onion","nori strip"],
    instructions: ["Cook thin crepes. Grill chicken with teriyaki sauce.","Lay crepe flat, add mayo, lettuce, chicken and avocado.","Roll into cone, secure with nori strip."],
    image: "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=600&q=80",
    sourceUrl: "https://www.japancentre.com/teriyaki-crepes",
    prepTime: 20, cookTime: 15, servings: 4, difficulty: "easy",
    dietaryTags: ["dairy-free"],
    calories: 340, protein: 22, carbs: 38, fat: 10,
    structuredIngredients: [
      { name: "crepe batter", amount: 250, unit: "ml" },
      { name: "chicken breast", amount: 300, unit: "g" },
      { name: "teriyaki sauce", amount: 4, unit: "tbsp" },
      { name: "avocado", amount: 1, unit: null },
      { name: "lettuce", amount: 4, unit: "leaves" },
      { name: "mayonnaise", amount: 2, unit: "tbsp" },
      { name: "red cabbage", amount: 40, unit: "g" },
      { name: "sesame seeds", amount: 1, unit: "tsp" },
      { name: "spring onion", amount: 2, unit: null },
      { name: "nori strip", amount: 4, unit: null },
    ],
    flavorBridge: ["teriyaki caramel + crepe butter", "avocado creaminess + sesame aroma"],
    heritage: ["Japanese", "French"],
    substitutions: [{ swap: "tofu strips", for: "chicken breast" }, { swap: "hoisin sauce", for: "teriyaki sauce" }],
  },
  {
    id: "bao-burger",
    name: "Bao Burger",
    category: "European-Asian Fusion",
    originStory: "London's Bao restaurant placed pulled pork belly inside cloud-soft steamed Taiwanese bao buns, simultaneously launching a street-food trend and redefining the British burger.",
    ingredients: ["steamed bao buns","pork belly","hoisin sauce","cucumber","peanut powder","coriander","garlic","five spice","brown sugar","rice vinegar"],
    instructions: ["Braise pork belly with hoisin, five spice, garlic and sugar until tender.","Shred pork. Steam bao buns.","Fill with pork, cucumber and peanut powder.","Garnish with coriander."],
    image: "https://images.unsplash.com/photo-1514190051997-0f6f39ca5cde?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/bao-burger",
    prepTime: 20, cookTime: 180, servings: 4, difficulty: "hard",
    dietaryTags: ["dairy-free"],
    calories: 560, protein: 30, carbs: 52, fat: 26,
    structuredIngredients: [
      { name: "steamed bao buns", amount: 8, unit: null },
      { name: "pork belly", amount: 600, unit: "g" },
      { name: "hoisin sauce", amount: 3, unit: "tbsp" },
      { name: "cucumber", amount: 1, unit: null },
      { name: "peanut powder", amount: 2, unit: "tbsp" },
      { name: "coriander", amount: null, unit: null },
      { name: "garlic", amount: 4, unit: "cloves" },
      { name: "five spice", amount: 1, unit: "tsp" },
      { name: "brown sugar", amount: 2, unit: "tbsp" },
      { name: "rice vinegar", amount: 1, unit: "tbsp" },
    ],
    flavorBridge: ["pork belly fat + hoisin sweetness", "steamed bao cloud + five spice depth"],
    heritage: ["Taiwanese", "British"],
    substitutions: [{ swap: "jackfruit", for: "pork belly" }, { swap: "plum sauce", for: "hoisin sauce" }],
  },
  {
    id: "matcha-tiramisu",
    name: "Matcha Tiramisu",
    category: "European-Asian Fusion",
    originStory: "Italian pastry chefs in Kyoto swapped espresso for ceremonial matcha, soaking ladyfingers in bitter green tea and dusting with kinako instead of cocoa.",
    ingredients: ["ladyfinger biscuits","matcha powder","mascarpone","eggs","sugar","cream","kinako","sake","vanilla","white chocolate"],
    instructions: ["Brew strong matcha, cool and add sake.","Whip mascarpone with egg yolks and sugar.","Fold in whipped cream.","Dip ladyfingers in matcha, layer with cream.","Dust with kinako and white chocolate shavings."],
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/matcha-tiramisu",
    prepTime: 30, cookTime: 0, servings: 6, difficulty: "medium",
    dietaryTags: ["vegetarian"],
    calories: 420, protein: 8, carbs: 38, fat: 28,
    structuredIngredients: [
      { name: "ladyfinger biscuits", amount: 200, unit: "g" },
      { name: "matcha powder", amount: 3, unit: "tbsp" },
      { name: "mascarpone", amount: 250, unit: "g" },
      { name: "eggs", amount: 3, unit: null },
      { name: "sugar", amount: 80, unit: "g" },
      { name: "cream", amount: 150, unit: "ml" },
      { name: "kinako", amount: 2, unit: "tbsp" },
      { name: "sake", amount: 2, unit: "tbsp" },
      { name: "vanilla", amount: 1, unit: "tsp" },
      { name: "white chocolate", amount: 60, unit: "g" },
    ],
    flavorBridge: ["matcha bitterness + mascarpone fat", "sake floral + kinako nuttiness"],
    heritage: ["Japanese", "Italian"],
    substitutions: [{ swap: "hojicha", for: "matcha powder" }, { swap: "cream cheese", for: "mascarpone" }],
  },
  // ── Indian-Western Fusion ──
  {
    id: "naan-pizza",
    name: "Naan Pizza",
    category: "Indian-Western Fusion",
    originStory: "British curry houses discovered that tandoor-blistered naan makes a perfect pizza base: charred, chewy and ready in minutes, loaded with tikka masala sauce.",
    ingredients: ["naan bread","tikka masala sauce","paneer","mozzarella","red onion","bell peppers","coriander","chaat masala","lime","chilli flakes"],
    instructions: ["Spread tikka sauce on naan.","Top with mozzarella, paneer and vegetables.","Bake at 220C for 8 minutes.","Finish with fresh coriander and chaat masala."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/naan-pizza",
    prepTime: 5, cookTime: 10, servings: 2, difficulty: "easy",
    dietaryTags: ["vegetarian"],
    calories: 480, protein: 22, carbs: 54, fat: 18,
    structuredIngredients: [
      { name: "naan bread", amount: 2, unit: null },
      { name: "tikka masala sauce", amount: 80, unit: "ml" },
      { name: "paneer", amount: 150, unit: "g" },
      { name: "mozzarella", amount: 120, unit: "g" },
      { name: "red onion", amount: 0.5, unit: null },
      { name: "bell peppers", amount: 1, unit: null },
      { name: "coriander", amount: null, unit: null },
      { name: "chaat masala", amount: 0.5, unit: "tsp" },
      { name: "lime", amount: 0.5, unit: null },
      { name: "chilli flakes", amount: 0.5, unit: "tsp" },
    ],
    flavorBridge: ["tikka masala spice + mozzarella melt", "naan char + paneer curd"],
    heritage: ["Indian", "Italian"],
    substitutions: [{ swap: "chicken", for: "paneer" }, { swap: "pita bread", for: "naan bread" }],
  },
  {
    id: "butter-chicken-poutine",
    name: "Butter Chicken Poutine",
    category: "Indian-Western Fusion",
    originStory: "Toronto's Indian-Canadian diaspora replaced poutine gravy with murgh makhani sauce, demonstrating that cheese curds and butter chicken are a surprisingly perfect marriage.",
    ingredients: ["fries","cheese curds","butter chicken sauce","chicken breast","cream","tomato passata","garam masala","fenugreek","ginger","coriander"],
    instructions: ["Make butter chicken sauce.","Fry or bake fries until crisp.","Heap fries with cheese curds, pour hot butter chicken over.","Garnish with coriander."],
    image: "https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=600&q=80",
    sourceUrl: "https://www.foodnetwork.com/butter-chicken-poutine",
    prepTime: 20, cookTime: 30, servings: 4, difficulty: "medium",
    dietaryTags: ["gluten-free"],
    calories: 680, protein: 32, carbs: 72, fat: 28,
    structuredIngredients: [
      { name: "fries", amount: 400, unit: "g" },
      { name: "cheese curds", amount: 150, unit: "g" },
      { name: "butter chicken sauce", amount: 300, unit: "ml" },
      { name: "chicken breast", amount: 300, unit: "g" },
      { name: "cream", amount: 60, unit: "ml" },
      { name: "tomato passata", amount: 200, unit: "ml" },
      { name: "garam masala", amount: 1, unit: "tsp" },
      { name: "fenugreek", amount: 0.5, unit: "tsp" },
      { name: "ginger", amount: 2, unit: "cm" },
      { name: "coriander", amount: null, unit: null },
    ],
    flavorBridge: ["butter chicken spice + cheese curd squeak", "fry starch + makhani richness"],
    heritage: ["Indian", "Canadian"],
    substitutions: [{ swap: "paneer", for: "chicken breast" }, { swap: "halloumi cubes", for: "cheese curds" }],
  },
  {
    id: "dosa-quesadilla",
    name: "Dosa Quesadilla",
    category: "Indian-Western Fusion",
    originStory: "Bay Area South Indian restaurants fold masala dosa filling inside a wheat quesadilla with melted pepper jack, served with coconut chutney as salsa.",
    ingredients: ["flour tortillas","potato","onion","mustard seeds","curry leaves","turmeric","pepper jack cheese","coconut chutney","sambar","coriander"],
    instructions: ["Make masala potato filling.","Place tortilla in pan, add cheese and potato filling.","Fold and cook until cheese melts and tortilla crisps.","Serve with coconut chutney."],
    image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=600&q=80",
    sourceUrl: "https://www.delish.com/dosa-quesadilla",
    prepTime: 20, cookTime: 10, servings: 4, difficulty: "easy",
    dietaryTags: ["vegetarian"],
    calories: 380, protein: 14, carbs: 52, fat: 14,
    structuredIngredients: [
      { name: "flour tortillas", amount: 4, unit: null },
      { name: "potato", amount: 300, unit: "g" },
      { name: "onion", amount: 1, unit: null },
      { name: "mustard seeds", amount: 1, unit: "tsp" },
      { name: "curry leaves", amount: 8, unit: null },
      { name: "turmeric", amount: 0.5, unit: "tsp" },
      { name: "pepper jack cheese", amount: 120, unit: "g" },
      { name: "coconut chutney", amount: 80, unit: "ml" },
      { name: "sambar", amount: 100, unit: "ml" },
      { name: "coriander", amount: null, unit: null },
    ],
    flavorBridge: ["masala potato spice + pepper jack heat", "curry leaf aroma + crispy tortilla"],
    heritage: ["South Indian", "Mexican"],
    substitutions: [{ swap: "sweet potato", for: "potato" }, { swap: "cheddar", for: "pepper jack cheese" }],
  },
  {
    id: "tandoori-chicken-tacos",
    name: "Tandoori Chicken Tacos",
    category: "Indian-Western Fusion",
    originStory: "Mumbai food trucks adapted the taco format for Indian flavours, placing charred tandoori chicken inside corn tortillas with mint chutney standing in for salsa verde.",
    ingredients: ["chicken thighs","yoghurt","tandoori spice mix","corn tortillas","mint chutney","red onion","cucumber","mango","chaat masala","lime"],
    instructions: ["Marinate chicken in yoghurt and spices overnight.","Grill until charred and cooked through.","Warm tortillas, fill with sliced chicken.","Top with mint chutney, cucumber and red onion."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/tandoori-tacos",
    prepTime: 480, cookTime: 15, servings: 4, difficulty: "medium",
    dietaryTags: ["gluten-free"],
    calories: 440, protein: 36, carbs: 34, fat: 16,
    structuredIngredients: [
      { name: "chicken thighs", amount: 500, unit: "g" },
      { name: "yoghurt", amount: 120, unit: "ml" },
      { name: "tandoori spice mix", amount: 3, unit: "tbsp" },
      { name: "corn tortillas", amount: 8, unit: null },
      { name: "mint chutney", amount: 80, unit: "ml" },
      { name: "red onion", amount: 0.5, unit: null },
      { name: "cucumber", amount: 0.5, unit: null },
      { name: "mango", amount: 0.5, unit: null },
      { name: "chaat masala", amount: 0.5, unit: "tsp" },
      { name: "lime", amount: 1, unit: null },
    ],
    flavorBridge: ["tandoori char + yoghurt tang", "mint chutney freshness + mango sweetness"],
    heritage: ["Indian", "Mexican"],
    substitutions: [{ swap: "paneer", for: "chicken thighs" }, { swap: "raita", for: "mint chutney" }],
  },
  {
    id: "masala-mac-cheese",
    name: "Masala Mac and Cheese",
    category: "Indian-Western Fusion",
    originStory: "London's curry-belt fusion movement stirred garam masala and caramelised onion into bechamel cheese sauce, heating mac and cheese with Indian spice layering.",
    ingredients: ["macaroni","cheddar","cream","garam masala","turmeric","caramelised onion","green chilli","butter","panko breadcrumbs","coriander"],
    instructions: ["Cook pasta. Make spiced bechamel with cheese and garam masala.","Fold in pasta and caramelised onion.","Top with spiced breadcrumbs and bake."],
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/masala-mac-cheese",
    prepTime: 15, cookTime: 30, servings: 6, difficulty: "medium",
    dietaryTags: ["vegetarian"],
    calories: 540, protein: 22, carbs: 62, fat: 22,
    structuredIngredients: [
      { name: "macaroni", amount: 400, unit: "g" },
      { name: "cheddar", amount: 200, unit: "g" },
      { name: "cream", amount: 200, unit: "ml" },
      { name: "garam masala", amount: 1.5, unit: "tsp" },
      { name: "turmeric", amount: 0.5, unit: "tsp" },
      { name: "caramelised onion", amount: 100, unit: "g" },
      { name: "green chilli", amount: 1, unit: null },
      { name: "butter", amount: 40, unit: "g" },
      { name: "panko breadcrumbs", amount: 60, unit: "g" },
      { name: "coriander", amount: null, unit: null },
    ],
    flavorBridge: ["garam masala warmth + cheddar fat", "caramelised onion sweetness + green chilli bite"],
    heritage: ["Indian", "American"],
    substitutions: [{ swap: "gruyere", for: "cheddar" }, { swap: "curry powder", for: "garam masala" }],
  },
  {
    id: "chicken-tikka-pasta",
    name: "Chicken Tikka Pasta",
    category: "Indian-Western Fusion",
    originStory: "British comfort food culture married the nation's favourite Indian takeaway with penne in a tikka-spiced tomato cream sauce, going viral on TikTok in 2021.",
    ingredients: ["penne","chicken breast","tikka masala paste","cream","crushed tomatoes","garlic","ginger","bell pepper","coriander","parmesan"],
    instructions: ["Marinate and grill chicken in tikka paste.","Saute garlic and ginger, add paste and tomatoes.","Add cream, simmer. Toss in pasta and sliced chicken.","Garnish with coriander."],
    image: "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=600&q=80",
    sourceUrl: "https://www.delish.com/chicken-tikka-pasta",
    prepTime: 15, cookTime: 25, servings: 4, difficulty: "easy",
    dietaryTags: [],
    calories: 560, protein: 34, carbs: 64, fat: 18,
    structuredIngredients: [
      { name: "penne", amount: 400, unit: "g" },
      { name: "chicken breast", amount: 400, unit: "g" },
      { name: "tikka masala paste", amount: 4, unit: "tbsp" },
      { name: "cream", amount: 150, unit: "ml" },
      { name: "crushed tomatoes", amount: 400, unit: "g" },
      { name: "garlic", amount: 3, unit: "cloves" },
      { name: "ginger", amount: 2, unit: "cm" },
      { name: "bell pepper", amount: 1, unit: null },
      { name: "coriander", amount: null, unit: null },
      { name: "parmesan", amount: 40, unit: "g" },
    ],
    flavorBridge: ["tikka paste depth + tomato acidity", "cream richness + penne starch"],
    heritage: ["Indian", "Italian"],
    substitutions: [{ swap: "chickpeas", for: "chicken breast" }, { swap: "coconut milk", for: "cream" }],
  },
  {
    id: "curry-grilled-cheese",
    name: "Curry Grilled Cheese",
    category: "Indian-Western Fusion",
    originStory: "New York Indian-American sandwich shops spread mango chutney and curry-spiced caramelised onions inside a classic grilled cheese, bridging a diner and a chaat stall.",
    ingredients: ["sourdough bread","gruyere","mango chutney","curry powder","caramelised onion","jalapeno","butter","coriander","apple","dijon mustard"],
    instructions: ["Caramelise onion with curry powder.","Spread mango chutney on one slice, mustard on other.","Fill with gruyere, onion and jalapeno.","Butter outside, grill until golden."],
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/curry-grilled-cheese",
    prepTime: 15, cookTime: 10, servings: 2, difficulty: "easy",
    dietaryTags: ["vegetarian"],
    calories: 520, protein: 18, carbs: 46, fat: 28,
    structuredIngredients: [
      { name: "sourdough bread", amount: 4, unit: "slices" },
      { name: "gruyere", amount: 120, unit: "g" },
      { name: "mango chutney", amount: 3, unit: "tbsp" },
      { name: "curry powder", amount: 1, unit: "tsp" },
      { name: "caramelised onion", amount: 80, unit: "g" },
      { name: "jalapeno", amount: 1, unit: null },
      { name: "butter", amount: 40, unit: "g" },
      { name: "coriander", amount: null, unit: null },
      { name: "apple", amount: 0.5, unit: null },
      { name: "dijon mustard", amount: 1, unit: "tsp" },
    ],
    flavorBridge: ["mango chutney sweet-sour + curry warmth", "gruyere nuttiness + sourdough tang"],
    heritage: ["Indian", "American"],
    substitutions: [{ swap: "cheddar", for: "gruyere" }, { swap: "apricot jam", for: "mango chutney" }],
  },
  // ── Middle Eastern & Global Fusion ──
  {
    id: "shakshuka-pizza",
    name: "Shakshuka Pizza",
    category: "Middle Eastern & Global Fusion",
    originStory: "Tel Aviv bakeries began cracking eggs into hollows of flatbread topped with spiced tomato sauce, merging shakshuka's drama with pizza's communal eating ritual.",
    ingredients: ["pizza dough","crushed tomatoes","red pepper","harissa","cumin","eggs","feta","zaatar","olive oil","fresh mint"],
    instructions: ["Stretch dough, spread tomato harissa base.","Make wells in sauce.","Bake 5 minutes at 250C, crack in eggs.","Return to oven 4-5 minutes until whites set.","Finish with feta, zaatar and mint."],
    image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/shakshuka-pizza",
    prepTime: 15, cookTime: 15, servings: 4, difficulty: "medium",
    dietaryTags: ["vegetarian"],
    calories: 420, protein: 18, carbs: 52, fat: 16,
    structuredIngredients: [
      { name: "pizza dough", amount: 400, unit: "g" },
      { name: "crushed tomatoes", amount: 200, unit: "g" },
      { name: "red pepper", amount: 1, unit: null },
      { name: "harissa", amount: 2, unit: "tbsp" },
      { name: "cumin", amount: 0.5, unit: "tsp" },
      { name: "eggs", amount: 4, unit: null },
      { name: "feta", amount: 80, unit: "g" },
      { name: "zaatar", amount: 1, unit: "tsp" },
      { name: "olive oil", amount: 2, unit: "tbsp" },
      { name: "fresh mint", amount: null, unit: null },
    ],
    flavorBridge: ["harissa fire + egg richness", "feta brine + zaatar herb"],
    heritage: ["Middle Eastern", "Italian"],
    substitutions: [{ swap: "labneh", for: "feta" }, { swap: "ras el hanout", for: "harissa" }],
  },
  {
    id: "falafel-burger",
    name: "Falafel Burger",
    category: "Middle Eastern & Global Fusion",
    originStory: "Berlin's street food scene placed crispy falafel inside brioche buns, dressing them with tahini instead of mayo and preserved turnips instead of gherkins.",
    ingredients: ["falafel patty","brioche bun","tahini sauce","hummus","preserved turnip","tomato","rocket","cucumber","sumac","lemon"],
    instructions: ["Deep fry or pan-fry falafel.","Toast bun and spread hummus on bottom.","Layer rocket, tomato, falafel and turnip.","Drizzle tahini, sprinkle sumac."],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/falafel-burger",
    prepTime: 20, cookTime: 10, servings: 2, difficulty: "easy",
    dietaryTags: ["vegan", "dairy-free"],
    calories: 480, protein: 18, carbs: 62, fat: 18,
    structuredIngredients: [
      { name: "falafel patty", amount: 4, unit: null },
      { name: "brioche bun", amount: 2, unit: null },
      { name: "tahini sauce", amount: 4, unit: "tbsp" },
      { name: "hummus", amount: 60, unit: "g" },
      { name: "preserved turnip", amount: 40, unit: "g" },
      { name: "tomato", amount: 1, unit: null },
      { name: "rocket", amount: 30, unit: "g" },
      { name: "cucumber", amount: 0.5, unit: null },
      { name: "sumac", amount: 0.5, unit: "tsp" },
      { name: "lemon", amount: 0.5, unit: null },
    ],
    flavorBridge: ["tahini nuttiness + falafel herb", "sumac tartness + hummus creaminess"],
    heritage: ["Middle Eastern", "American"],
    substitutions: [{ swap: "pitta bread", for: "brioche bun" }, { swap: "tzatziki", for: "tahini sauce" }],
  },
  {
    id: "zaatar-focaccia",
    name: "Zaatar Focaccia",
    category: "Middle Eastern & Global Fusion",
    originStory: "Italian-Lebanese bakeries replaced rosemary with zaatar and drizzled generous pools of olive oil into focaccia dimples, creating a herb bread that belongs to both traditions.",
    ingredients: ["bread flour","zaatar","olive oil","salt","yeast","water","olives","cherry tomatoes","sea salt flakes","sumac"],
    instructions: ["Make focaccia dough, let rise.","Press into oiled tin, dimple generously.","Scatter zaatar, olives and tomatoes into dimples.","Drizzle olive oil and bake at 220C for 20-25 minutes."],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/zaatar-focaccia",
    prepTime: 90, cookTime: 25, servings: 8, difficulty: "medium",
    dietaryTags: ["vegan", "dairy-free"],
    calories: 280, protein: 6, carbs: 42, fat: 10,
    structuredIngredients: [
      { name: "bread flour", amount: 500, unit: "g" },
      { name: "zaatar", amount: 3, unit: "tbsp" },
      { name: "olive oil", amount: 80, unit: "ml" },
      { name: "salt", amount: 10, unit: "g" },
      { name: "yeast", amount: 7, unit: "g" },
      { name: "water", amount: 380, unit: "ml" },
      { name: "olives", amount: 80, unit: "g" },
      { name: "cherry tomatoes", amount: 100, unit: "g" },
      { name: "sea salt flakes", amount: null, unit: null },
      { name: "sumac", amount: 1, unit: "tsp" },
    ],
    flavorBridge: ["zaatar herb + olive oil richness", "sumac tartness + focaccia yeast depth"],
    heritage: ["Lebanese", "Italian"],
    substitutions: [{ swap: "rosemary + thyme", for: "zaatar" }, { swap: "roasted garlic", for: "olives" }],
  },
  {
    id: "harissa-lamb-tacos",
    name: "Harissa Lamb Tacos",
    category: "Middle Eastern & Global Fusion",
    originStory: "Sydney's Middle Eastern-Mexican fusion trucks marinate lamb shoulder in North African harissa before slow-roasting it shawarma-style and serving in corn tortillas with tahini.",
    ingredients: ["lamb shoulder","harissa","cumin","coriander","corn tortillas","tahini","sumac onions","mint","pomegranate seeds","yoghurt"],
    instructions: ["Rub lamb with harissa and spices, slow-roast 4 hours.","Pull meat and rest.","Fill warmed tortillas with lamb.","Top with sumac onions, mint and pomegranate.","Drizzle tahini."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/harissa-lamb-tacos",
    prepTime: 20, cookTime: 240, servings: 6, difficulty: "hard",
    dietaryTags: ["gluten-free", "dairy-free"],
    calories: 480, protein: 34, carbs: 28, fat: 26,
    structuredIngredients: [
      { name: "lamb shoulder", amount: 800, unit: "g" },
      { name: "harissa", amount: 3, unit: "tbsp" },
      { name: "cumin", amount: 1, unit: "tsp" },
      { name: "coriander", amount: 1, unit: "tsp" },
      { name: "corn tortillas", amount: 12, unit: null },
      { name: "tahini", amount: 4, unit: "tbsp" },
      { name: "sumac onions", amount: 80, unit: "g" },
      { name: "mint", amount: null, unit: null },
      { name: "pomegranate seeds", amount: 40, unit: "g" },
      { name: "yoghurt", amount: 100, unit: "ml" },
    ],
    flavorBridge: ["harissa fire + lamb fat", "pomegranate acid + tahini earthiness"],
    heritage: ["North African", "Mexican"],
    substitutions: [{ swap: "jackfruit", for: "lamb shoulder" }, { swap: "pita", for: "corn tortillas" }],
  },
  {
    id: "mujaddara-bowl",
    name: "Mujaddara Bowl",
    category: "Middle Eastern & Global Fusion",
    originStory: "NYC's grain bowl trend adopted Lebanon's ancient lentil-rice dish and dressed it with crispy chickpeas, tahini drizzle and turmeric-roasted cauliflower.",
    ingredients: ["green lentils","basmati rice","caramelised onion","cauliflower","tahini","chickpeas","cumin","lemon","parsley","pomegranate molasses"],
    instructions: ["Cook lentils with cumin, fold in cooked rice.","Roast cauliflower and chickpeas with turmeric.","Serve mujaddara topped with roasted veg.","Drizzle tahini and pomegranate molasses."],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    sourceUrl: "https://www.bonappetit.com/mujaddara-bowl",
    prepTime: 15, cookTime: 40, servings: 4, difficulty: "easy",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    calories: 380, protein: 16, carbs: 58, fat: 12,
    structuredIngredients: [
      { name: "green lentils", amount: 200, unit: "g" },
      { name: "basmati rice", amount: 200, unit: "g" },
      { name: "caramelised onion", amount: 150, unit: "g" },
      { name: "cauliflower", amount: 300, unit: "g" },
      { name: "tahini", amount: 4, unit: "tbsp" },
      { name: "chickpeas", amount: 200, unit: "g" },
      { name: "cumin", amount: 1, unit: "tsp" },
      { name: "lemon", amount: 1, unit: null },
      { name: "parsley", amount: null, unit: null },
      { name: "pomegranate molasses", amount: 1, unit: "tbsp" },
    ],
    flavorBridge: ["lentil earthiness + caramelised onion sweetness", "tahini nuttiness + pomegranate tartness"],
    heritage: ["Lebanese", "American"],
    substitutions: [{ swap: "freekeh", for: "basmati rice" }, { swap: "roasted beets", for: "cauliflower" }],
  },
  {
    id: "persian-tahdig-bowl",
    name: "Tahdig Buddha Bowl",
    category: "Middle Eastern & Global Fusion",
    originStory: "LA's Persian-fusion cafes placed the sacred golden crust of Persian tahdig at the base of a modern Buddha bowl, surrounding the crispy rice with roasted vegetables.",
    ingredients: ["basmati rice","saffron","yoghurt","roasted vegetables","chickpeas","fresh herbs","pomegranate","barberries","pistachios","rose water dressing"],
    instructions: ["Make tahdig: line pot with oiled yoghurt-rice, steam until golden.","Roast seasonal vegetables.","Unmould tahdig, arrange veg, chickpeas and herbs around.","Drizzle rose water dressing and scatter barberries."],
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    sourceUrl: "https://www.foodandwine.com/tahdig-bowl",
    prepTime: 20, cookTime: 45, servings: 4, difficulty: "hard",
    dietaryTags: ["vegetarian", "gluten-free"],
    calories: 420, protein: 12, carbs: 62, fat: 14,
    structuredIngredients: [
      { name: "basmati rice", amount: 300, unit: "g" },
      { name: "saffron", amount: 0.5, unit: "tsp" },
      { name: "yoghurt", amount: 80, unit: "ml" },
      { name: "roasted vegetables", amount: 400, unit: "g" },
      { name: "chickpeas", amount: 150, unit: "g" },
      { name: "fresh herbs", amount: null, unit: null },
      { name: "pomegranate", amount: 60, unit: "g" },
      { name: "barberries", amount: 30, unit: "g" },
      { name: "pistachios", amount: 40, unit: "g" },
      { name: "rose water dressing", amount: 2, unit: "tbsp" },
    ],
    flavorBridge: ["saffron floral + tahdig crunch", "barberry tartness + pistachio richness"],
    heritage: ["Persian", "American"],
    substitutions: [{ swap: "dried cranberries", for: "barberries" }, { swap: "almonds", for: "pistachios" }],
  },
  {
    id: "labneh-toast",
    name: "Labneh Toast",
    category: "Middle Eastern & Global Fusion",
    originStory: "London's Middle Eastern cafes swapped avocado for labneh: strained yoghurt so thick it holds toppings, dressed with dukkah and honey on sourdough.",
    ingredients: ["sourdough bread","labneh","dukkah","honey","zaatar","cucumber","cherry tomatoes","fresh mint","olive oil","sea salt"],
    instructions: ["Toast sourdough.","Spread thick labneh generously.","Top with cucumber, tomatoes and mint.","Sprinkle dukkah and zaatar, drizzle honey and olive oil."],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/labneh-toast",
    prepTime: 10, cookTime: 5, servings: 2, difficulty: "easy",
    dietaryTags: ["vegetarian"],
    calories: 320, protein: 12, carbs: 38, fat: 14,
    structuredIngredients: [
      { name: "sourdough bread", amount: 2, unit: "slices" },
      { name: "labneh", amount: 120, unit: "g" },
      { name: "dukkah", amount: 2, unit: "tbsp" },
      { name: "honey", amount: 1, unit: "tbsp" },
      { name: "zaatar", amount: 1, unit: "tsp" },
      { name: "cucumber", amount: 0.5, unit: null },
      { name: "cherry tomatoes", amount: 60, unit: "g" },
      { name: "fresh mint", amount: null, unit: null },
      { name: "olive oil", amount: 1, unit: "tbsp" },
      { name: "sea salt", amount: null, unit: null },
    ],
    flavorBridge: ["labneh tang + honey sweetness", "dukkah crunch + zaatar herb"],
    heritage: ["Lebanese", "Australian"],
    substitutions: [{ swap: "avocado", for: "labneh" }, { swap: "za'atar blend", for: "dukkah" }],
  },
  {
    id: "sumac-salmon-pasta",
    name: "Sumac Salmon Pasta",
    category: "Middle Eastern & Global Fusion",
    originStory: "Stockholm chefs combined cold-smoked salmon with pasta and a sumac-tahini cream sauce, bringing Levantine tartness to a Scandinavian-Italian collision.",
    ingredients: ["linguine","cold-smoked salmon","sumac","tahini","cream","lemon","capers","dill","garlic","crispy shallots"],
    instructions: ["Cook pasta. Make sauce with tahini, cream, lemon and sumac.","Toss pasta in sauce.","Top with smoked salmon, capers and dill.","Garnish with crispy shallots."],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=600&q=80",
    sourceUrl: "https://www.allrecipes.com/sumac-salmon-pasta",
    prepTime: 10, cookTime: 12, servings: 2, difficulty: "easy",
    dietaryTags: ["gluten-free"],
    calories: 520, protein: 32, carbs: 54, fat: 20,
    structuredIngredients: [
      { name: "linguine", amount: 200, unit: "g" },
      { name: "cold-smoked salmon", amount: 150, unit: "g" },
      { name: "sumac", amount: 2, unit: "tsp" },
      { name: "tahini", amount: 2, unit: "tbsp" },
      { name: "cream", amount: 100, unit: "ml" },
      { name: "lemon", amount: 1, unit: null },
      { name: "capers", amount: 2, unit: "tbsp" },
      { name: "dill", amount: null, unit: null },
      { name: "garlic", amount: 2, unit: "cloves" },
      { name: "crispy shallots", amount: 30, unit: "g" },
    ],
    flavorBridge: ["sumac tartness + smoked salmon richness", "tahini nuttiness + caper brine"],
    heritage: ["Middle Eastern", "Scandinavian"],
    substitutions: [{ swap: "hot-smoked trout", for: "cold-smoked salmon" }, { swap: "lemon zest + pepper", for: "sumac" }],
  },
  {
    id: "halloumi-tacos",
    name: "Halloumi Tacos",
    category: "Middle Eastern & Global Fusion",
    originStory: "Vegetarian fusion chefs replaced carne asada with grilled slabs of squeaky halloumi in corn tortillas, dressing them with harissa salsa and pomegranate.",
    ingredients: ["halloumi","corn tortillas","harissa","pomegranate seeds","red cabbage","mint yoghurt","lime","cumin","smoked paprika","rocket"],
    instructions: ["Slice halloumi and grill until golden.","Warm tortillas.","Fill with halloumi, red cabbage and rocket.","Top with harissa, pomegranate and mint yoghurt.","Squeeze lime."],
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&q=80",
    sourceUrl: "https://www.delish.com/halloumi-tacos",
    prepTime: 10, cookTime: 8, servings: 2, difficulty: "easy",
    dietaryTags: ["vegetarian", "gluten-free"],
    calories: 420, protein: 22, carbs: 34, fat: 22,
    structuredIngredients: [
      { name: "halloumi", amount: 250, unit: "g" },
      { name: "corn tortillas", amount: 6, unit: null },
      { name: "harissa", amount: 2, unit: "tbsp" },
      { name: "pomegranate seeds", amount: 40, unit: "g" },
      { name: "red cabbage", amount: 60, unit: "g" },
      { name: "mint yoghurt", amount: 80, unit: "ml" },
      { name: "lime", amount: 1, unit: null },
      { name: "cumin", amount: 0.5, unit: "tsp" },
      { name: "smoked paprika", amount: 0.5, unit: "tsp" },
      { name: "rocket", amount: 30, unit: "g" },
    ],
    flavorBridge: ["halloumi squeak + harissa heat", "pomegranate jewels + mint yoghurt cool"],
    heritage: ["Cypriot", "Mexican"],
    substitutions: [{ swap: "paneer", for: "halloumi" }, { swap: "hummus", for: "mint yoghurt" }],
  },
  {
    id: "turkish-eggs-brunch",
    name: "Turkish Eggs Brunch Bowl",
    category: "Middle Eastern & Global Fusion",
    originStory: "A 15th-century Ottoman court dish called cilbir: poached eggs on garlicky yoghurt with chilli butter, became a 2020s global brunch staple after landing on London menus.",
    ingredients: ["eggs","Greek yoghurt","garlic","butter","Aleppo pepper","white wine vinegar","sourdough bread","dill","sumac","olive oil"],
    instructions: ["Poach eggs in vinegared water.","Whip yoghurt with garlic and salt.","Brown butter with Aleppo pepper.","Spoon yoghurt into bowl, place eggs on top.","Pour sizzling butter over, garnish with dill."],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
    sourceUrl: "https://www.seriouseats.com/cilbir",
    prepTime: 10, cookTime: 10, servings: 2, difficulty: "easy",
    dietaryTags: ["vegetarian", "gluten-free"],
    calories: 380, protein: 20, carbs: 18, fat: 26,
    structuredIngredients: [
      { name: "eggs", amount: 4, unit: null },
      { name: "Greek yoghurt", amount: 200, unit: "ml" },
      { name: "garlic", amount: 1, unit: "clove" },
      { name: "butter", amount: 40, unit: "g" },
      { name: "Aleppo pepper", amount: 1, unit: "tsp" },
      { name: "white wine vinegar", amount: 1, unit: "tbsp" },
      { name: "sourdough bread", amount: 2, unit: "slices" },
      { name: "dill", amount: null, unit: null },
      { name: "sumac", amount: 0.5, unit: "tsp" },
      { name: "olive oil", amount: 1, unit: "tbsp" },
    ],
    flavorBridge: ["Aleppo pepper warmth + garlic yoghurt cool", "poached egg richness + sumac tartness"],
    heritage: ["Turkish", "British"],
    substitutions: [{ swap: "chilli flakes + black pepper", for: "Aleppo pepper" }, { swap: "labneh", for: "Greek yoghurt" }],
  },
];

export const FUSION_CATEGORIES: FusionCategory[] = [
  "Asian-Latin Fusion",
  "New American Staples",
  "European-Asian Fusion",
  "Indian-Western Fusion",
  "Middle Eastern & Global Fusion",
];

export const CULINARY_BRIDGES = [
  { location: "Georgia (Caucasus)", bridge: "Eastern Europe — Middle East — Central Asia", dish: "Khachapuri", description: "Sitting at the crossroads of three culinary worlds, Georgia absorbs walnut-rich Persian aromatics, Slavic bread traditions and Central Asian spice routes into one singular cuisine." },
  { location: "Philippines", bridge: "Southeast Asia — Spain — China", dish: "Adobo", description: "Three centuries of Spanish colonialism layered over indigenous Austronesian cooking, with Fujianese traders adding vinegar-soy braising techniques to create Southeast Asia's most eclectic table." },
  { location: "Maghreb", bridge: "North Africa — Arab World — France", dish: "Bastilla", description: "Berber grain traditions, Arab spice caravans and French pastry precision converge in couscous and filo pastry alike, making Morocco one of the world's richest culinary crossroads." },
  { location: "Peru", bridge: "Inca — Spain — Japan — China", dish: "Ceviche", description: "The Andean civilisation's potato and quinoa heritage absorbed Spanish citrus, Chinese stir-fry technique and Japanese precision into a uniquely layered South American tradition." },
  { location: "Malta", bridge: "Italy — North Africa — Arab", dish: "Pastizzi", description: "This tiny Mediterranean island accumulated Sicilian pasta culture, Moorish spice influence and British pub traditions into a kitchen that punches far above its geographic weight." },
  { location: "Uzbekistan", bridge: "Persia — China — Russia", dish: "Plov", description: "Straddling the Silk Road, Uzbek cooking fused Persian pilaf and aromatics, Chinese noodle techniques and Russian dairy traditions into plov: the world's most travelled rice dish." },
  { location: "Mauritius and Reunion", bridge: "Africa — India — France — China", dish: "Dholl Puri", description: "These Indian Ocean islands fused African staples, South Indian spice traditions, French Creole cooking and Fujianese Chinese techniques into one of the world's most diverse island cuisines." },
];
