"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "es" | "de" | "fr";

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: "en", label: "English", flag: "🇺🇸" },
  { code: "es", label: "Español", flag: "🇪🇸" },
  { code: "de", label: "Deutsch", flag: "🇩🇪" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
];

// ---------------------------------------------------------------------------
// Translation map
// ---------------------------------------------------------------------------
export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.dashboard": "Dashboard",
    "nav.discover": "Find Recipes",
    "nav.swipe": "Meal Swipe",
    "nav.saved": "Saved",
    "nav.my_recipes": "My Recipes",
    "nav.pantry": "My Pantry",
    "nav.plans": "Meal Plans",
    "nav.drinks": "Drinks",
    "nav.premium": "Premium",
    "nav.cuisines": "World Cuisines",
    "nav.dinner": "Dinner Parties",
    "nav.menu_scanner": "Menu Scanner",
    "nav.calorie": "Nutrient Tracker",
    "nav.profile": "Profile",
    // Discover
    "discover.title": "Find Recipes",
    "discover.search": "Search recipes…",
    "discover.all": "All",
    "discover.no_results": "No recipes found",
    // Recipe page
    "recipe.ingredients": "Ingredients",
    "recipe.instructions": "Instructions",
    "recipe.save": "Save recipe",
    "recipe.saved": "Saved",
    "recipe.back": "Back to recipes",
    "recipe.ratings": "Ratings",
    "recipe.comments": "Comments",
    "recipe.add_comment": "Add a comment…",
    "recipe.submit": "Submit",
    "recipe.tip": "Pro Tip",
    "recipe.min": "min",
    "recipe.kcal": "kcal",
    "recipe.protein": "protein",
    "recipe.servings": "servings",
    "recipe.prep": "prep",
    "recipe.cook": "cook",
    // Meal plans
    "plans.new": "New plan",
    "plans.title": "My Meal Plans",
    "plans.template": "Start from a template",
    "plans.custom": "Or build your own",
    "plans.create": "Create plan",
    "plans.name": "Plan name",
    "plans.duration": "Duration",
    "plans.meals_per_day": "Meals per day",
    "plans.dietary": "Dietary preferences",
    "plans.goals": "Daily goals",
    "plans.ai_prompt": "AI prompt",
    "plans.ai_hint": "e.g. Quick weeknight meals for 2, max 30 min cooking time",
    "plans.days": "days",
    "plans.meals": "meals",
    "plans.creating": "Creating…",
    // Pantry
    "pantry.add": "Add ingredient",
    "pantry.search": "Search pantry…",
    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.suggested": "Suggested for you",
    // Tags
    "tag.high_protein": "High Protein",
    "tag.quick_cook": "Quick Cook",
    "tag.low_cost": "Budget",
    "tag.vegan": "Vegan",
    "tag.vegetarian": "Vegetarian",
    "tag.gluten_free": "Gluten-Free",
    "tag.dairy_free": "Dairy-Free",
    "tag.family": "Family",
    "tag.meal_prep": "Meal Prep",
    "tag.mediterranean": "Mediterranean",
    "tag.under_30": "Under 30 min",
    "tag.batch_cook": "Batch Cook",
  },
  es: {
    "nav.dashboard": "Inicio",
    "nav.discover": "Buscar Recetas",
    "nav.swipe": "Meal Swipe",
    "nav.saved": "Guardadas",
    "nav.my_recipes": "Mis Recetas",
    "nav.pantry": "Mi Despensa",
    "nav.plans": "Planes de Comida",
    "nav.drinks": "Bebidas",
    "nav.premium": "Premium",
    "nav.cuisines": "Cocinas del Mundo",
    "nav.dinner": "Cenas con Amigos",
    "nav.menu_scanner": "Escáner de Menú",
    "nav.calorie": "Nutrientes",
    "nav.profile": "Perfil",
    "discover.title": "Buscar Recetas",
    "discover.search": "Buscar recetas…",
    "discover.all": "Todo",
    "discover.no_results": "Sin resultados",
    "recipe.ingredients": "Ingredientes",
    "recipe.instructions": "Instrucciones",
    "recipe.save": "Guardar receta",
    "recipe.saved": "Guardada",
    "recipe.back": "Volver a recetas",
    "recipe.ratings": "Valoraciones",
    "recipe.comments": "Comentarios",
    "recipe.add_comment": "Añadir comentario…",
    "recipe.submit": "Enviar",
    "recipe.tip": "Consejo Pro",
    "recipe.min": "min",
    "recipe.kcal": "kcal",
    "recipe.protein": "proteína",
    "recipe.servings": "porciones",
    "recipe.prep": "prep",
    "recipe.cook": "cocción",
    "plans.new": "Nuevo plan",
    "plans.title": "Mis Planes",
    "plans.template": "Empieza con una plantilla",
    "plans.custom": "O crea el tuyo",
    "plans.create": "Crear plan",
    "plans.name": "Nombre del plan",
    "plans.duration": "Duración",
    "plans.meals_per_day": "Comidas al día",
    "plans.dietary": "Preferencias dietéticas",
    "plans.goals": "Objetivos diarios",
    "plans.ai_prompt": "Prompt IA",
    "plans.ai_hint": "ej. Comidas rápidas entre semana, máx 30 minutos",
    "plans.days": "días",
    "plans.meals": "comidas",
    "plans.creating": "Creando…",
    "pantry.add": "Agregar ingrediente",
    "pantry.search": "Buscar en despensa…",
    "dashboard.welcome": "Bienvenido de vuelta",
    "dashboard.suggested": "Sugerido para ti",
    "tag.high_protein": "Alta Proteína",
    "tag.quick_cook": "Cocción Rápida",
    "tag.low_cost": "Económico",
    "tag.vegan": "Vegano",
    "tag.vegetarian": "Vegetariano",
    "tag.gluten_free": "Sin Gluten",
    "tag.dairy_free": "Sin Lácteos",
    "tag.family": "Familiar",
    "tag.meal_prep": "Preparación",
    "tag.mediterranean": "Mediterráneo",
    "tag.under_30": "Menos de 30 min",
    "tag.batch_cook": "Cocción en Lote",
  },
  de: {
    "nav.dashboard": "Dashboard",
    "nav.discover": "Rezepte finden",
    "nav.swipe": "Meal Swipe",
    "nav.saved": "Gespeichert",
    "nav.my_recipes": "Meine Rezepte",
    "nav.pantry": "Meine Vorratskammer",
    "nav.plans": "Mahlzeitenpläne",
    "nav.drinks": "Getränke",
    "nav.premium": "Premium",
    "nav.cuisines": "Weltküchen",
    "nav.dinner": "Dinnerpartys",
    "nav.menu_scanner": "Menü-Scanner",
    "nav.calorie": "Nährstoffe",
    "nav.profile": "Profil",
    "discover.title": "Rezepte finden",
    "discover.search": "Rezepte suchen…",
    "discover.all": "Alle",
    "discover.no_results": "Keine Ergebnisse",
    "recipe.ingredients": "Zutaten",
    "recipe.instructions": "Anleitung",
    "recipe.save": "Rezept speichern",
    "recipe.saved": "Gespeichert",
    "recipe.back": "Zurück zu Rezepten",
    "recipe.ratings": "Bewertungen",
    "recipe.comments": "Kommentare",
    "recipe.add_comment": "Kommentar hinzufügen…",
    "recipe.submit": "Absenden",
    "recipe.tip": "Profi-Tipp",
    "recipe.min": "Min",
    "recipe.kcal": "kcal",
    "recipe.protein": "Eiweiß",
    "recipe.servings": "Portionen",
    "recipe.prep": "Vorb.",
    "recipe.cook": "Kochen",
    "plans.new": "Neuer Plan",
    "plans.title": "Meine Pläne",
    "plans.template": "Mit einer Vorlage starten",
    "plans.custom": "Oder selbst erstellen",
    "plans.create": "Plan erstellen",
    "plans.name": "Planname",
    "plans.duration": "Dauer",
    "plans.meals_per_day": "Mahlzeiten pro Tag",
    "plans.dietary": "Ernährungspräferenzen",
    "plans.goals": "Tagesziele",
    "plans.ai_prompt": "KI-Prompt",
    "plans.ai_hint": "z.B. Schnelle Abendessen für 2, max 30 Min.",
    "plans.days": "Tage",
    "plans.meals": "Mahlzeiten",
    "plans.creating": "Erstellen…",
    "pantry.add": "Zutat hinzufügen",
    "pantry.search": "Vorratskammer durchsuchen…",
    "dashboard.welcome": "Willkommen zurück",
    "dashboard.suggested": "Für dich empfohlen",
    "tag.high_protein": "Proteinreich",
    "tag.quick_cook": "Schnell kochen",
    "tag.low_cost": "Günstig",
    "tag.vegan": "Vegan",
    "tag.vegetarian": "Vegetarisch",
    "tag.gluten_free": "Glutenfrei",
    "tag.dairy_free": "Laktosefrei",
    "tag.family": "Familie",
    "tag.meal_prep": "Meal Prep",
    "tag.mediterranean": "Mediterran",
    "tag.under_30": "Unter 30 Min",
    "tag.batch_cook": "Batch-Kochen",
  },
  fr: {
    "nav.dashboard": "Accueil",
    "nav.discover": "Trouver des Recettes",
    "nav.swipe": "Meal Swipe",
    "nav.saved": "Sauvegardées",
    "nav.my_recipes": "Mes Recettes",
    "nav.pantry": "Mon Garde-Manger",
    "nav.plans": "Plans de Repas",
    "nav.drinks": "Boissons",
    "nav.premium": "Premium",
    "nav.cuisines": "Cuisines du Monde",
    "nav.dinner": "Dîners entre Amis",
    "nav.menu_scanner": "Scanner de Menu",
    "nav.calorie": "Nutriments",
    "nav.profile": "Profil",
    "discover.title": "Trouver des Recettes",
    "discover.search": "Chercher des recettes…",
    "discover.all": "Tout",
    "discover.no_results": "Aucun résultat",
    "recipe.ingredients": "Ingrédients",
    "recipe.instructions": "Instructions",
    "recipe.save": "Sauvegarder",
    "recipe.saved": "Sauvegardée",
    "recipe.back": "Retour aux recettes",
    "recipe.ratings": "Notes",
    "recipe.comments": "Commentaires",
    "recipe.add_comment": "Ajouter un commentaire…",
    "recipe.submit": "Envoyer",
    "recipe.tip": "Astuce Pro",
    "recipe.min": "min",
    "recipe.kcal": "kcal",
    "recipe.protein": "protéines",
    "recipe.servings": "portions",
    "recipe.prep": "prép",
    "recipe.cook": "cuisson",
    "plans.new": "Nouveau plan",
    "plans.title": "Mes Plans",
    "plans.template": "Commencer avec un modèle",
    "plans.custom": "Ou créer le vôtre",
    "plans.create": "Créer le plan",
    "plans.name": "Nom du plan",
    "plans.duration": "Durée",
    "plans.meals_per_day": "Repas par jour",
    "plans.dietary": "Préférences alimentaires",
    "plans.goals": "Objectifs quotidiens",
    "plans.ai_prompt": "Prompt IA",
    "plans.ai_hint": "ex. Repas rapides en semaine, max 30 min de cuisine",
    "plans.days": "jours",
    "plans.meals": "repas",
    "plans.creating": "Création…",
    "pantry.add": "Ajouter un ingrédient",
    "pantry.search": "Rechercher dans le garde-manger…",
    "dashboard.welcome": "Bon retour",
    "dashboard.suggested": "Suggestions pour vous",
    "tag.high_protein": "Riche en Protéines",
    "tag.quick_cook": "Cuisson Rapide",
    "tag.low_cost": "Économique",
    "tag.vegan": "Végétalien",
    "tag.vegetarian": "Végétarien",
    "tag.gluten_free": "Sans Gluten",
    "tag.dairy_free": "Sans Lactose",
    "tag.family": "Famille",
    "tag.meal_prep": "Meal Prep",
    "tag.mediterranean": "Méditerranéen",
    "tag.under_30": "Moins de 30 min",
    "tag.batch_cook": "Cuisine en Lot",
  },
};

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------
interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    const stored = localStorage.getItem("wc_lang") as Language | null;
    if (stored && TRANSLATIONS[stored]) setLangState(stored);
  }, []);

  function setLang(l: Language) {
    setLangState(l);
    localStorage.setItem("wc_lang", l);
  }

  function t(key: string): string {
    return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS["en"]?.[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
