export interface WCNation {
  flag: string;
  iso2: string;
  name: string;
  cuisine: string;
  countrySlug: string;
  group: string;
  dishes: { name: string; description: string }[];
  heroImage: string;
  region: string;
}

export const WC2026_NATIONS: WCNation[] = [
  { flag: "🇺🇸", iso2: "US", name: "United States", cuisine: "American", countrySlug: "usa", group: "Host", region: "North America", heroImage: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80", dishes: [{name:"Apple Pie",description:"The classic American dessert"},{name:"Buffalo Wings",description:"Spicy chicken wings"},{name:"Hamburger",description:"The American staple"},{name:"Clam Chowder",description:"Creamy seafood soup"},{name:"Macaroni and Cheese",description:"Soul food/comfort"},{name:"Chocolate Chip Cookies",description:"Standard bake"},{name:"Texas BBQ Ribs",description:"Slow-cooked meat"},{name:"Grits",description:"Corn-based breakfast"},{name:"Bourbon Whiskey",description:"Kentucky spirit"},{name:"Cornbread",description:"Southern staple side"}] },
  { flag: "🇨🇦", iso2: "CA", name: "Canada", cuisine: "Canadian", countrySlug: "canada", group: "Host", region: "North America", heroImage: "https://images.unsplash.com/photo-1569025690938-a00729c9e1f9?w=800&q=80", dishes: [{name:"Poutine",description:"Fries, curds, gravy"},{name:"Nanaimo Bars",description:"No-bake dessert"},{name:"Butter Tarts",description:"Pastry with syrupy filling"},{name:"Tourtiere",description:"French-Canadian meat pie"},{name:"BeaverTails",description:"Fried dough pastry"},{name:"Peameal Bacon",description:"Cornmeal-crusted pork"},{name:"Split Pea Soup",description:"Classic winter comfort"},{name:"Caesar Cocktail",description:"Vodka, Clamato, spices"},{name:"Montreal Bagels",description:"Honey-boiled bagels"},{name:"Maple Taffy",description:"Hot maple syrup on snow"}] },
  { flag: "🇲🇽", iso2: "MX", name: "Mexico", cuisine: "Mexican", countrySlug: "mexico", group: "Host", region: "North America", heroImage: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80", dishes: [{name:"Tacos al Pastor",description:"Spit-grilled pork"},{name:"Mole Poblano",description:"Rich chocolate-chili sauce"},{name:"Chilaquiles",description:"Breakfast tortillas in salsa"},{name:"Guacamole",description:"Avocado dip"},{name:"Enchiladas",description:"Filled tortillas with sauce"},{name:"Tamales",description:"Steamed corn dough"},{name:"Pozole",description:"Hominy and meat soup"},{name:"Churros",description:"Fried dough with sugar"},{name:"Margarita",description:"Tequila-based cocktail"},{name:"Agua de Horchata",description:"Sweet rice milk drink"}] },
  { flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", iso2: "GB-ENG", name: "England", cuisine: "British", countrySlug: "england", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=800&q=80", dishes: [{name:"Fish and Chips",description:"Battered fish, fried potatoes"},{name:"Sunday Roast",description:"Meat, potatoes, veg, Yorkshire pudding"},{name:"Full English Breakfast",description:"Eggs, bacon, beans, tomato"},{name:"Shepherds Pie",description:"Lamb and mashed potato"},{name:"Bangers and Mash",description:"Sausages and potato"},{name:"Eton Mess",description:"Meringue, cream, berries"},{name:"Sticky Toffee Pudding",description:"Sponge with date syrup"},{name:"Beef Wellington",description:"Pastry-wrapped beef"},{name:"Scones",description:"With clotted cream and jam"},{name:"Pimms Cup",description:"Summer gin cocktail"}] },
  { flag: "🇫🇷", iso2: "FR", name: "France", cuisine: "French", countrySlug: "france", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800&q=80", dishes: [{name:"Coq au Vin",description:"Chicken in wine"},{name:"Ratatouille",description:"Vegetable stew"},{name:"Boeuf Bourguignon",description:"Beef stew"},{name:"Croissants",description:"Buttery pastry"},{name:"Quiche Lorraine",description:"Bacon and egg tart"},{name:"French Onion Soup",description:"Cheesy, onion broth"},{name:"Creme Brulee",description:"Custard with burnt sugar"},{name:"Bouillabaisse",description:"Provencal fish stew"},{name:"Macarons",description:"Almond meringue cookies"},{name:"Kir Royale",description:"Champagne and cassis"}] },
  { flag: "🇩🇪", iso2: "DE", name: "Germany", cuisine: "German", countrySlug: "germany", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1467189386127-c4e5e31ee213?w=800&q=80", dishes: [{name:"Bratwurst",description:"Grilled sausage"},{name:"Schnitzel",description:"Breaded meat"},{name:"Sauerkraut",description:"Fermented cabbage"},{name:"Pretzels",description:"Knotted bread"},{name:"Black Forest Cake",description:"Cherry and chocolate"},{name:"Currywurst",description:"Sausage with curry ketchup"},{name:"Kartoffelsalat",description:"Potato salad"},{name:"Spatzle",description:"Egg noodles"},{name:"Sauerbraten",description:"Pot roast"},{name:"Stollen",description:"Christmas fruit bread"}] },
  { flag: "🇪🇸", iso2: "ES", name: "Spain", cuisine: "Spanish", countrySlug: "spain", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=800&q=80", dishes: [{name:"Paella",description:"Saffron rice with seafood/meat"},{name:"Gazpacho",description:"Cold tomato soup"},{name:"Tortilla Espanola",description:"Potato omelet"},{name:"Churros con Chocolate",description:"Breakfast/dessert"},{name:"Patatas Bravas",description:"Fried potatoes with sauce"},{name:"Jamon Iberico",description:"Cured ham"},{name:"Sangria",description:"Wine and fruit punch"},{name:"Gambas al Ajillo",description:"Garlic shrimp"},{name:"Crema Catalana",description:"Spanish custard"},{name:"Tinto de Verano",description:"Wine and soda drink"}] },
  { flag: "🇵🇹", iso2: "PT", name: "Portugal", cuisine: "Portuguese", countrySlug: "portugal", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=800&q=80", dishes: [{name:"Bacalhau a Bras",description:"Salt cod with eggs/potatoes"},{name:"Pasteis de Nata",description:"Egg custard tarts"},{name:"Frango Piri-Piri",description:"Spicy grilled chicken"},{name:"Caldo Verde",description:"Kale and potato soup"},{name:"Arroz Doce",description:"Sweet rice pudding"},{name:"Bifana",description:"Pork sandwich"},{name:"Francesinha",description:"Mega sandwich with sauce"},{name:"Port Wine",description:"Fortified wine"},{name:"Sardinhas Assadas",description:"Grilled sardines"},{name:"Ginjinha",description:"Sour cherry liqueur"}] },
  { flag: "🇳🇱", iso2: "NL", name: "Netherlands", cuisine: "Dutch", countrySlug: "netherlands", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1576487236230-eaa4afe6a776?w=800&q=80", dishes: [{name:"Stroopwafel",description:"Syrup-filled wafer"},{name:"Stamppot",description:"Mashed potatoes and veg"},{name:"Bitterballen",description:"Deep-fried meat snacks"},{name:"Haring",description:"Raw herring with onions"},{name:"Poffertjes",description:"Mini pancakes"},{name:"Erwtensoep",description:"Split pea soup"},{name:"Kibbeling",description:"Fried fish pieces"},{name:"Oliebollen",description:"Dutch donuts"},{name:"Jenever",description:"Dutch gin"},{name:"Appeltaart",description:"Deep-dish apple pie"}] },
  { flag: "🇧🇪", iso2: "BE", name: "Belgium", cuisine: "Belgian", countrySlug: "belgium", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1579684947550-22e945225d9a?w=800&q=80", dishes: [{name:"Moules-Frites",description:"Mussels and fries"},{name:"Belgian Waffles",description:"Liege or Brussels style"},{name:"Carbonnade Flamande",description:"Beef and beer stew"},{name:"Waterzooi",description:"Creamy chicken/fish stew"},{name:"Speculoos",description:"Spiced biscuits"},{name:"Chocolate Pralines",description:"Luxury truffles"},{name:"Chicons au Gratin",description:"Endives with ham/cheese"},{name:"Sole Meuniere",description:"Pan-fried fish"},{name:"Trappist Beer",description:"Monk-brewed ale"},{name:"Stoemp",description:"Mashed veg and potatoes"}] },
  { flag: "🇭🇷", iso2: "HR", name: "Croatia", cuisine: "Croatian", countrySlug: "croatia", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1555990538-c4a69e14f0a0?w=800&q=80", dishes: [{name:"Crni Rizot",description:"Black squid ink risotto"},{name:"Peka",description:"Meat/veg slow-cooked under a bell"},{name:"Pasticada",description:"Braised beef dish"},{name:"Cevapi",description:"Grilled meat sausages"},{name:"Rozata",description:"Dubrovnik-style custard"},{name:"Kremsnica",description:"Custard cream cake"},{name:"Rakija",description:"Fruit brandy"},{name:"Strukli",description:"Dough with cottage cheese"},{name:"Brudet",description:"Fish stew"},{name:"Fritule",description:"Small festive donuts"}] },
  { flag: "🇨🇭", iso2: "CH", name: "Switzerland", cuisine: "Swiss", countrySlug: "switzerland", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80", dishes: [{name:"Cheese Fondue",description:"Melted cheese dip"},{name:"Raclette",description:"Scraped melted cheese"},{name:"Rosti",description:"Fried shredded potatoes"},{name:"Bircher Muesli",description:"Overnight oats"},{name:"Swiss Chocolate",description:"Milk chocolate bars"},{name:"Zopf",description:"Braided bread"},{name:"Rivella",description:"Milk-whey soda"},{name:"Absinthe",description:"Herbal spirit"},{name:"Papet Vaudois",description:"Leek and potato with sausage"},{name:"Engadiner Nusstorte",description:"Walnut tart"}] },
  { flag: "🇦🇹", iso2: "AT", name: "Austria", cuisine: "Austrian", countrySlug: "austria", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1551867633-194f125bddfa?w=800&q=80", dishes: [{name:"Wiener Schnitzel",description:"Fried veal cutlet"},{name:"Sachertorte",description:"Chocolate cake with apricot"},{name:"Apfelstrudel",description:"Apple strudel"},{name:"Kaiserschmarrn",description:"Shredded pancakes"},{name:"Tafelspitz",description:"Boiled beef in broth"},{name:"Gulasch",description:"Spiced meat stew"},{name:"Almdudler",description:"Herbal soda"},{name:"Mozartkugeln",description:"Pistachio/marzipan balls"},{name:"Linzer Torte",description:"Nut pastry with jam"},{name:"Knodel",description:"Potato or bread dumplings"}] },
  { flag: "🇳🇴", iso2: "NO", name: "Norway", cuisine: "Norwegian", countrySlug: "norway", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1601244851897-b8e0fbd0d8a2?w=800&q=80", dishes: [{name:"Farikaal",description:"Mutton and cabbage stew"},{name:"Gravlax",description:"Cured salmon"},{name:"Brunost",description:"Brown whey cheese"},{name:"Rakfisk",description:"Fermented trout"},{name:"Lutefisk",description:"Dried cod in lye"},{name:"Krumkake",description:"Rolled waffle cookie"},{name:"Aquavit",description:"Spiced spirit"},{name:"Lefse",description:"Potato flatbread"},{name:"Rommegrot",description:"Sour cream porridge"},{name:"Kjoettkaker",description:"Norwegian meatballs"}] },
  { flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", iso2: "GB-SCT", name: "Scotland", cuisine: "Scottish", countrySlug: "scotland", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", dishes: [{name:"Haggis",description:"Savory pudding"},{name:"Neeps and Tatties",description:"Turnips and potatoes"},{name:"Cullen Skink",description:"Smoked fish soup"},{name:"Scotch Broth",description:"Barley and meat soup"},{name:"Shortbread",description:"Buttery biscuit"},{name:"Cranachan",description:"Oats, cream, whisky, berries"},{name:"Irn-Bru",description:"Iconic orange soda"},{name:"Scotch Whisky",description:"Peated spirit"},{name:"Black Pudding",description:"Blood sausage"},{name:"Arbroath Smokie",description:"Smoked haddock"}] },
  { flag: "🇸🇪", iso2: "SE", name: "Sweden", cuisine: "Swedish", countrySlug: "sweden", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=800&q=80", dishes: [{name:"Kottbullar",description:"Meatballs with lingonberries"},{name:"Gravlax",description:"Dill-cured salmon"},{name:"Smorgasbord",description:"Traditional buffet"},{name:"Kanelbulle",description:"Cinnamon bun"},{name:"Prinsesstarta",description:"Green marzipan cake"},{name:"Surstroemming",description:"Fermented herring"},{name:"Glogg",description:"Mulled wine"},{name:"Pea Soup and Pancakes",description:"Thursday tradition"},{name:"Toast Skagen",description:"Shrimp toast"},{name:"Falukorv",description:"Traditional sausage"}] },
  { flag: "🇹🇷", iso2: "TR", name: "Turkiye", cuisine: "Turkish", countrySlug: "turkiye", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1599599810694-b5b37304c041?w=800&q=80", dishes: [{name:"Doner Kebab",description:"Rotating meat wrap"},{name:"Baklava",description:"Nut and honey pastry"},{name:"Turkish Delight",description:"Sweet jellies"},{name:"Pide",description:"Boat-shaped pizza"},{name:"Lahmacun",description:"Thin meat-topped dough"},{name:"Kofte",description:"Turkish meatballs"},{name:"Menemen",description:"Scrambled eggs with tomatoes"},{name:"Turkish Coffee",description:"Strong unfiltered coffee"},{name:"Ayran",description:"Salty yogurt drink"},{name:"Borek",description:"Flaky savory pastry"}] },
  { flag: "🇨🇿", iso2: "CZ", name: "Czechia", cuisine: "Czech", countrySlug: "czechia", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80", dishes: [{name:"Vepro Knedlo Zelo",description:"Pork, dumplings, kraut"},{name:"Svickova",description:"Beef in cream sauce"},{name:"Smazeny syr",description:"Fried cheese"},{name:"Trdlenik",description:"Chimney cake"},{name:"Pilsner Beer",description:"Origin of the style"},{name:"Bramboraky",description:"Potato pancakes"},{name:"Gulas",description:"Czech-style goulash"},{name:"Kolace",description:"Sweet fruit pastries"},{name:"Medovnik",description:"Honey layer cake"},{name:"Becherovka",description:"Herbal liqueur"}] },
  { flag: "🇧🇦", iso2: "BA", name: "Bosnia and Herzegovina", cuisine: "Bosnian", countrySlug: "bosnia", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80", dishes: [{name:"Cevapi",description:"Grilled meat fingers"},{name:"Burek",description:"Meat-filled phyllo"},{name:"Begova Corba",description:"Beys soup"},{name:"Klepe",description:"Bosnian ravioli"},{name:"Dolma",description:"Stuffed vegetables"},{name:"Tufahija",description:"Poached apples"},{name:"Baklava",description:"Bosnian style"},{name:"Bosnian Coffee",description:"Similar to Turkish"},{name:"Rakija",description:"Fruit brandy"},{name:"Somun",description:"Pita-like bread"}] },
  { flag: "🇬🇷", iso2: "GR", name: "Greece", cuisine: "Greek", countrySlug: "greece", group: "UEFA", region: "Europe", heroImage: "https://images.unsplash.com/photo-1576867757603-05b134ebc379?w=800&q=80", dishes: [{name:"Moussaka",description:"Layered eggplant and meat bake"},{name:"Souvlaki",description:"Grilled meat skewers"},{name:"Spanakopita",description:"Spinach and feta pie"},{name:"Tzatziki",description:"Yogurt and cucumber dip"},{name:"Pastitsio",description:"Greek pasta bake"},{name:"Horiatiki Salad",description:"Classic Greek salad"},{name:"Grilled Octopus",description:"With olive oil and lemon"},{name:"Loukoumades",description:"Honey doughnuts"},{name:"Gyros",description:"Wrapped rotisserie meat"},{name:"Avgolemono",description:"Egg-lemon soup"}] },
  { flag: "🇲🇦", iso2: "MA", name: "Morocco", cuisine: "Moroccan", countrySlug: "morocco", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80", dishes: [{name:"Tagine",description:"Slow-cooked stew"},{name:"Couscous",description:"Semolina grain with veg"},{name:"Pastilla",description:"Sweet/savory meat pie"},{name:"Harira",description:"Tomato and lentil soup"},{name:"Mint Tea",description:"The Moroccan Whiskey"},{name:"Baghrir",description:"Semolina pancakes"},{name:"Briouat",description:"Fried triangle pastries"},{name:"Zaalouk",description:"Eggplant/tomato dip"},{name:"Mechoui",description:"Roasted lamb"},{name:"Chebakia",description:"Honey-coated cookies"}] },
  { flag: "🇸🇳", iso2: "SN", name: "Senegal", cuisine: "Senegalese", countrySlug: "senegal", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1565026573-2b62a0dab11c?w=800&q=80", dishes: [{name:"Thieboudienne",description:"National fish and rice"},{name:"Yassa",description:"Chicken/fish with onions/lemon"},{name:"Maafe",description:"Peanut stew"},{name:"Bassi Salte",description:"Millet couscous"},{name:"Pastel",description:"Fried fish pastries"},{name:"Bissap",description:"Hibiscus flower tea"},{name:"Bouye",description:"Baobab fruit drink"},{name:"Sombi",description:"Sweet rice pudding"},{name:"Thiakry",description:"Couscous pudding"},{name:"Lakhou Bissap",description:"Meat and veg stew"}] },
  { flag: "🇪🇬", iso2: "EG", name: "Egypt", cuisine: "Egyptian", countrySlug: "egypt", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1568358319878-3d00f99ba5b4?w=800&q=80", dishes: [{name:"Koshary",description:"Rice, pasta, lentils, sauce"},{name:"Ful Medames",description:"Stewed fava beans"},{name:"Molokhia",description:"Jute mallow soup"},{name:"Fattah",description:"Meat, rice, bread, vinegar"},{name:"Falafel",description:"Fava bean balls"},{name:"Shawarma",description:"Marinated meat wraps"},{name:"Umm Ali",description:"Egyptian bread pudding"},{name:"Basbousa",description:"Semolina cake"},{name:"Hibiscus Tea",description:"Floral drink"},{name:"Mahshi",description:"Stuffed vegetables"}] },
  { flag: "🇩🇿", iso2: "DZ", name: "Algeria", cuisine: "Algerian", countrySlug: "algeria", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1604147706283-d7119b5b822c?w=800&q=80", dishes: [{name:"Couscous",description:"The staple dish"},{name:"Chorba Frik",description:"Lamb and grain soup"},{name:"Tajine Zitoun",description:"Chicken with olives"},{name:"Bourek",description:"Crispy phyllo rolls"},{name:"Rechta",description:"Noodles with chicken"},{name:"Makroudh",description:"Date-filled semolina"},{name:"Mahjouba",description:"Filled savory pancakes"},{name:"Algerian Mint Tea",description:"Strong and sweet"},{name:"Chakchouka",description:"Poached eggs in tomato"},{name:"Msemen",description:"Flaky flatbread"}] },
  { flag: "🇹🇳", iso2: "TN", name: "Tunisia", cuisine: "Tunisian", countrySlug: "tunisia", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1577803645773-f96470509666?w=800&q=80", dishes: [{name:"Couscous au Poisson",description:"Fish couscous"},{name:"Lablabi",description:"Chickpea soup"},{name:"Brik",description:"Deep-fried pastry with egg"},{name:"Ojja",description:"Tunisian shakshuka"},{name:"Mechouia Salad",description:"Grilled veg salad"},{name:"Bambalouni",description:"Tunisian donut"},{name:"Mint Tea with Pine Nuts",description:"Specialty"},{name:"Harissa",description:"Spicy chili paste"},{name:"Makroudh",description:"Semolina sweets"},{name:"Tunisian Tajine",description:"Frittata-like cake"}] },
  { flag: "🇳🇬", iso2: "NG", name: "Nigeria", cuisine: "Nigerian", countrySlug: "nigeria", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80", dishes: [{name:"Jollof Rice",description:"Spicy one-pot rice"},{name:"Pounded Yam and Egusi Soup",description:"Melon seed soup"},{name:"Suya",description:"Spicy skewered meat"},{name:"Akara",description:"Fried bean cakes"},{name:"Moi Moi",description:"Steamed bean pudding"},{name:"Puff-Puff",description:"Fried dough balls"},{name:"Pepper Soup",description:"Spicy broth"},{name:"Zobo",description:"Hibiscus drink"},{name:"Chin Chin",description:"Fried crunchy snacks"},{name:"Okra Soup",description:"Slimy, savory soup"}] },
  { flag: "🇿🇦", iso2: "ZA", name: "South Africa", cuisine: "South African", countrySlug: "south-africa", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80", dishes: [{name:"Bobotie",description:"Spiced meat bake"},{name:"Biltong",description:"Cured dried meat"},{name:"Bunny Chow",description:"Curry in bread loaf"},{name:"Boerewors",description:"Farmers sausage"},{name:"Melktert",description:"Milk tart"},{name:"Malva Pudding",description:"Apricot sponge"},{name:"Braai",description:"The South African BBQ"},{name:"Chakalaka",description:"Spicy vegetable relish"},{name:"Rooibos Tea",description:"Red herbal tea"},{name:"Amarula",description:"Cream liqueur from marula"}] },
  { flag: "🇨🇮", iso2: "CI", name: "Cote d'Ivoire", cuisine: "Ivorian", countrySlug: "cote-divoire", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1586511925558-a4c6376fe65f?w=800&q=80", dishes: [{name:"Garba",description:"Attieke with fried tuna"},{name:"Kedjenou",description:"Slow-cooked chicken"},{name:"Alloco",description:"Fried plantains"},{name:"Foutou",description:"Mashed plantain/yam"},{name:"Sauce Graine",description:"Palm nut soup"},{name:"Placali",description:"Fermented cassava dough"},{name:"Bangui",description:"Palm wine"},{name:"Gnamakoudji",description:"Ginger juice"},{name:"Poisson Braise",description:"Grilled fish"},{name:"Choukouya",description:"Smoked meat"}] },
  { flag: "🇬🇭", iso2: "GH", name: "Ghana", cuisine: "Ghanaian", countrySlug: "ghana", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80", dishes: [{name:"Ghanaian Jollof Rice",description:"The rival style"},{name:"Waakye",description:"Rice and beans"},{name:"Banku and Tilapia",description:"Corn/cassava dough"},{name:"Kenkey",description:"Fermented corn dough"},{name:"Shito",description:"Black pepper sauce"},{name:"Red-Red",description:"Bean stew with plantain"},{name:"Kelewele",description:"Fried spicy plantains"},{name:"Fufu",description:"Mashed starches"},{name:"Nkrakra Light Soup",description:"Traditional broth"},{name:"Sobolo",description:"Hibiscus drink"}] },
  { flag: "🇨🇻", iso2: "CV", name: "Cabo Verde", cuisine: "Cape Verdean", countrySlug: "cabo-verde", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1601930438988-0d7d3ff83e93?w=800&q=80", dishes: [{name:"Cachupa",description:"Corn and bean stew"},{name:"Pastels",description:"Fish-filled pastries"},{name:"Grogue",description:"Sugar cane spirit"},{name:"Pudim de Leite",description:"Milk pudding"},{name:"Xerem",description:"Cornmeal dish"},{name:"Catchupa Refogada",description:"Fried leftover stew"},{name:"Moreia Frita",description:"Fried moray eel"},{name:"Arroz Doce",description:"Rice pudding"},{name:"Canja de Galinha",description:"Chicken soup"},{name:"Doce de Papaia",description:"Papaya preserve"}] },
  { flag: "🇨🇩", iso2: "CD", name: "Congo DR", cuisine: "Congolese", countrySlug: "congo-dr", group: "CAF", region: "Africa", heroImage: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80", dishes: [{name:"Poulet a la Moambe",description:"Chicken in palm butter"},{name:"Fufu",description:"Cassava starch"},{name:"Pondu",description:"Cassava leaf stew"},{name:"Liboke",description:"Fish steamed in leaves"},{name:"Makayabu",description:"Salted fish"},{name:"Chikwangue",description:"Fermented cassava bread"},{name:"Ngai-Ngai",description:"Sorrel leaf dish"},{name:"Beignets",description:"Fried dough"},{name:"Lunguila",description:"Sugarcane wine"},{name:"Matembele",description:"Sweet potato leaf dish"}] },
  { flag: "🇯🇵", iso2: "JP", name: "Japan", cuisine: "Japanese", countrySlug: "japan", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80", dishes: [{name:"Sushi",description:"Vinegared rice and fish"},{name:"Ramen",description:"Noodle soup"},{name:"Tempura",description:"Battered fried food"},{name:"Okonomiyaki",description:"Savory pancake"},{name:"Takoyaki",description:"Octopus balls"},{name:"Miso Soup",description:"Fermented soy broth"},{name:"Yakitori",description:"Grilled chicken skewers"},{name:"Matcha Latte",description:"Green tea drink"},{name:"Tonkatsu",description:"Fried pork cutlet"},{name:"Udon",description:"Thick wheat noodles"}] },
  { flag: "🇰🇷", iso2: "KR", name: "South Korea", cuisine: "Korean", countrySlug: "south-korea", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=800&q=80", dishes: [{name:"Kimchi",description:"Fermented cabbage"},{name:"Bulgogi",description:"Marinated grilled beef"},{name:"Bibimbap",description:"Mixed rice bowl"},{name:"Japchae",description:"Glass noodle stir-fry"},{name:"Tteokbokki",description:"Spicy rice cakes"},{name:"Kimbap",description:"Seaweed rice rolls"},{name:"Korean Fried Chicken",description:"Double-fried"},{name:"Soju",description:"Distilled spirit"},{name:"Hotteok",description:"Sweet pancakes"},{name:"Galbi",description:"Grilled short ribs"}] },
  { flag: "🇦🇺", iso2: "AU", name: "Australia", cuisine: "Australian", countrySlug: "australia", group: "AFC", region: "Oceania", heroImage: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800&q=80", dishes: [{name:"Meat Pie",description:"National snack"},{name:"Lamingtons",description:"Sponge cake with coconut"},{name:"Vegemite on Toast",description:"Yeast extract spread"},{name:"Pavlova",description:"Meringue dessert"},{name:"Tim Tams",description:"Chocolate biscuits"},{name:"Anzac Biscuits",description:"Oat and coconut cookies"},{name:"Barramundi",description:"Native fish dish"},{name:"Kangaroo Steak",description:"Indigenous game"},{name:"Flat White",description:"Espresso coffee style"},{name:"Damper",description:"Bush bread"}] },
  { flag: "🇮🇷", iso2: "IR", name: "Iran", cuisine: "Persian", countrySlug: "iran", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1567226475328-9d6baaf565cf?w=800&q=80", dishes: [{name:"Chelow Kabab",description:"Beef/lamb with rice"},{name:"Ghormeh Sabzi",description:"Herb stew"},{name:"Fesenjan",description:"Pomegranate-walnut stew"},{name:"Tahdig",description:"Crispy rice layer"},{name:"Doogh",description:"Minty yogurt drink"},{name:"Bastani Sonnati",description:"Saffron ice cream"},{name:"Ash Reshteh",description:"Noodle and bean soup"},{name:"Joojeh Kabab",description:"Grilled saffron chicken"},{name:"Shirazi Salad",description:"Cucumber and tomato"},{name:"Halva",description:"Sweet flour-based dessert"}] },
  { flag: "🇸🇦", iso2: "SA", name: "Saudi Arabia", cuisine: "Saudi", countrySlug: "saudi-arabia", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1576867757603-05b134ebc379?w=800&q=80", dishes: [{name:"Kabsa",description:"Spiced rice and meat"},{name:"Mandi",description:"Pit-cooked meat and rice"},{name:"Jareesh",description:"Cracked wheat porridge"},{name:"Saleeg",description:"Creamy rice with meat"},{name:"Arabic Coffee",description:"Spiced coffee"},{name:"Dates",description:"National fruit"},{name:"Sambousek",description:"Fried savory pastries"},{name:"Mutabbaq",description:"Stuffed folded pancake"},{name:"Maamoul",description:"Date-filled cookies"},{name:"Sobia",description:"Traditional bread-based drink"}] },
  { flag: "🇶🇦", iso2: "QA", name: "Qatar", cuisine: "Qatari", countrySlug: "qatar", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80", dishes: [{name:"Machboos",description:"Spiced rice and meat"},{name:"Harees",description:"Beaten wheat and meat"},{name:"Madrouba",description:"Rice porridge"},{name:"Luqaimat",description:"Sweet dumplings"},{name:"Karak Tea",description:"Strong milky tea"},{name:"Balaleet",description:"Sweet vermicelli with egg"},{name:"Saloona",description:"Vegetable/meat broth"},{name:"Esh Asaraya",description:"Bread pudding with cream"},{name:"Ghuzi",description:"Roasted whole lamb"},{name:"Umm Ali",description:"Traditional pastry dessert"}] },
  { flag: "🇮🇶", iso2: "IQ", name: "Iraq", cuisine: "Iraqi", countrySlug: "iraq", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=800&q=80", dishes: [{name:"Masgouf",description:"Grilled carp"},{name:"Dolma",description:"Stuffed veggies and leaves"},{name:"Quzi",description:"Slow-roasted lamb"},{name:"Kleicha",description:"Date-filled cookies"},{name:"Iraqi Tea",description:"Strong, black, and sweet"},{name:"Kubba",description:"Bulgur meat patties"},{name:"Tashreeb",description:"Bread soaked in broth"},{name:"Bamia",description:"Okra stew"},{name:"Halawat Sha'iriyah",description:"Sweet vermicelli"},{name:"Shorbat Adas",description:"Lentil soup"}] },
  { flag: "🇺🇿", iso2: "UZ", name: "Uzbekistan", cuisine: "Uzbek", countrySlug: "uzbekistan", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&q=80", dishes: [{name:"Plov",description:"National rice dish"},{name:"Manti",description:"Steamed dumplings"},{name:"Shashlik",description:"Meat skewers"},{name:"Samsa",description:"Savory pastry"},{name:"Uzbek Bread",description:"Clay-oven bread"},{name:"Shurpa",description:"Meat and veg soup"},{name:"Lagman",description:"Noodle stew"},{name:"Green Tea",description:"Poured three times"},{name:"Halva",description:"Dense sweet"},{name:"Sumalak",description:"Wheat sprout spread"}] },
  { flag: "🇯🇴", iso2: "JO", name: "Jordan", cuisine: "Jordanian", countrySlug: "jordan", group: "AFC", region: "Asia", heroImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80", dishes: [{name:"Mansaf",description:"Lamb in yogurt sauce"},{name:"Maqluba",description:"Upside-down rice dish"},{name:"Falafel",description:"Chickpea fritters"},{name:"Hummus",description:"Chickpea dip"},{name:"Zarb",description:"Bedouin barbecue"},{name:"Kunafa",description:"Cheese pastry with syrup"},{name:"Bedouin Coffee",description:"Cardamom coffee"},{name:"Labaneh",description:"Strained yogurt"},{name:"Galayet Bandora",description:"Tomato stew"},{name:"Musakhan",description:"Sumac chicken on bread"}] },
  { flag: "🇦🇷", iso2: "AR", name: "Argentina", cuisine: "Argentinian", countrySlug: "argentina", group: "CONMEBOL", region: "South America", heroImage: "https://images.unsplash.com/photo-1612538498456-e861df91d4d0?w=800&q=80", dishes: [{name:"Asado",description:"Traditional BBQ"},{name:"Empanadas",description:"Pastry turnovers"},{name:"Choriopan",description:"Chorizo sandwich"},{name:"Dulce de Leche",description:"Caramel spread"},{name:"Alfajores",description:"Cookie sandwiches"},{name:"Chimichurri",description:"Garlic-herb sauce"},{name:"Milanesa",description:"Breaded cutlet"},{name:"Locro",description:"Corn and meat stew"},{name:"Yerba Mate",description:"Social herbal tea"},{name:"Medialunas",description:"Argentine croissants"}] },
  { flag: "🇧🇷", iso2: "BR", name: "Brazil", cuisine: "Brazilian", countrySlug: "brazil", group: "CONMEBOL", region: "South America", heroImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", dishes: [{name:"Feijoada",description:"Black bean and pork stew"},{name:"Brigadeiro",description:"Chocolate truffles"},{name:"Pao de Queijo",description:"Cheese bread"},{name:"Coxinha",description:"Chicken croquettes"},{name:"Caipirinha",description:"Cachaca cocktail"},{name:"Churrasco",description:"Grilled meats"},{name:"Moqueca",description:"Fish stew with coconut milk"},{name:"Acai Bowl",description:"Superfood berry mash"},{name:"Farofa",description:"Toasted cassava flour"},{name:"Pastel",description:"Deep-fried thin pastry"}] },
  { flag: "🇺🇾", iso2: "UY", name: "Uruguay", cuisine: "Uruguayan", countrySlug: "uruguay", group: "CONMEBOL", region: "South America", heroImage: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80", dishes: [{name:"Chivito",description:"Steak sandwich"},{name:"Asado",description:"Uruguayan BBQ"},{name:"Mate",description:"National drink"},{name:"Torta Frita",description:"Fried dough"},{name:"Revuelto Gramajo",description:"Eggs, ham, fries"},{name:"Dulce de Leche",description:"Similar to Argentina"},{name:"Pasta Frola",description:"Quince jam tart"},{name:"Clerico",description:"Wine and fruit punch"},{name:"Milanesa",description:"Breaded meat"},{name:"Alfajores",description:"The Uruguayan variety"}] },
  { flag: "🇨🇴", iso2: "CO", name: "Colombia", cuisine: "Colombian", countrySlug: "colombia", group: "CONMEBOL", region: "South America", heroImage: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80", dishes: [{name:"Bandeja Paisa",description:"Platter with beans, rice, meat"},{name:"Arepas",description:"Corn cakes"},{name:"Ajiaco",description:"Chicken and potato soup"},{name:"Sancocho",description:"Hearty meat/veg soup"},{name:"Pandebono",description:"Cheese bread"},{name:"Chicha",description:"Fermented corn drink"},{name:"Hot Chocolate with Cheese",description:"Breakfast"},{name:"Lulo Juice",description:"Citrusy fruit drink"},{name:"Empanadas",description:"Corn-based turnovers"},{name:"Postre de Natas",description:"Milk cream dessert"}] },
  { flag: "🇪🇨", iso2: "EC", name: "Ecuador", cuisine: "Ecuadorian", countrySlug: "ecuador", group: "CONMEBOL", region: "South America", heroImage: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80", dishes: [{name:"Ceviche",description:"Tomato-based style"},{name:"Encebollado",description:"Tuna and onion soup"},{name:"Llapingachos",description:"Potato pancakes"},{name:"Cuy Asado",description:"Roasted guinea pig"},{name:"Locro de Papa",description:"Potato and cheese soup"},{name:"Canelazo",description:"Spiced cinnamon drink"},{name:"Humitas",description:"Steamed corn cakes"},{name:"Morocho",description:"Sweet corn drink"},{name:"Fanesca",description:"Traditional Easter soup"},{name:"Espumilla",description:"Guava meringue dessert"}] },
  { flag: "🇵🇾", iso2: "PY", name: "Paraguay", cuisine: "Paraguayan", countrySlug: "paraguay", group: "CONMEBOL", region: "South America", heroImage: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80", dishes: [{name:"Sopa Paraguaya",description:"Cornbread soup"},{name:"Chipa",description:"Cheese bread"},{name:"Terere",description:"Cold yerba mate"},{name:"Mbeju",description:"Starchy flatbread"},{name:"Bori Bori",description:"Soup with cornmeal balls"},{name:"Pira Caldo",description:"Fish soup"},{name:"Mandioca",description:"Boiled cassava"},{name:"Cocido",description:"Roasted yerba mate tea"},{name:"Dulce de Guayaba",description:"Guava jelly"},{name:"Milanesa",description:"Common South American staple"}] },
  { flag: "🇵🇦", iso2: "PA", name: "Panama", cuisine: "Panamanian", countrySlug: "panama", group: "CONCACAF", region: "Central America", heroImage: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80", dishes: [{name:"Sancocho de Gallina",description:"Chicken soup"},{name:"Arroz con Pollo",description:"Rice and chicken"},{name:"Hojaldras",description:"Fried dough"},{name:"Ceviche Panameno",description:"Citrus fish"},{name:"Raspao",description:"Shaved ice dessert"},{name:"Chicha de Saril",description:"Sorrel/Hibiscus drink"},{name:"Carimanolas",description:"Meat-filled cassava"},{name:"Patacones",description:"Fried green plantains"},{name:"Tamal de Olla",description:"Unwrapped tamale"},{name:"Tres Leches",description:"Three-milk cake"}] },
  { flag: "🇭🇹", iso2: "HT", name: "Haiti", cuisine: "Haitian", countrySlug: "haiti", group: "CONCACAF", region: "Caribbean", heroImage: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80", dishes: [{name:"Griot",description:"Fried pork"},{name:"Diri ak Pwa",description:"Rice and beans"},{name:"Soup Joumou",description:"Independence pumpkin soup"},{name:"Pikliz",description:"Spicy pickled veg"},{name:"Epis",description:"Herb and spice base"},{name:"Kremas",description:"Coconut cream drink"},{name:"Pain Patate",description:"Sweet potato pudding"},{name:"Tassot",description:"Fried goat or beef"},{name:"Bannann Peze",description:"Pressed plantains"},{name:"Akassan",description:"Cornmeal shake"}] },
  { flag: "🇨🇼", iso2: "CW", name: "Curacao", cuisine: "Curacaoan", countrySlug: "curacao", group: "CONCACAF", region: "Caribbean", heroImage: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80", dishes: [{name:"Keshi Yena",description:"Stuffed cheese ball"},{name:"Kabritu Stoba",description:"Goat stew"},{name:"Pastechi",description:"Fried turnovers"},{name:"Ayaka",description:"Tamale-like wrap"},{name:"Kadushi",description:"Cactus soup"},{name:"Bolo Pretu",description:"Black fruit cake"},{name:"Blue Curacao Cocktail",description:"Iconic liqueur"},{name:"Pan Bati",description:"Sorghum pancake"},{name:"Giambo",description:"Okra and seafood soup"},{name:"Funchi",description:"Cornmeal mash"}] },
  { flag: "🇳🇿", iso2: "NZ", name: "New Zealand", cuisine: "New Zealand", countrySlug: "new-zealand", group: "OFC", region: "Oceania", heroImage: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80", dishes: [{name:"Hangi",description:"Maori earth-oven feast"},{name:"Pavlova",description:"The fruit/meringue battle with AU"},{name:"Kiwi Fruit",description:"The national icon"},{name:"Hokey Pokey Ice Cream",description:"Honeycomb toffee"},{name:"Lamb Roast",description:"New Zealand lamb"},{name:"L and P",description:"Iconic lemon soda"},{name:"Whitebait Fritters",description:"Tiny fish omelet"},{name:"Kumara",description:"Sweet potato"},{name:"Manuka Honey",description:"World-famous honey"},{name:"Feijoa",description:"Autumn fruit treats"}] },
];

export const CONF_COLORS: Record<string, string> = {
  "Host":     "#C8522A",
  "UEFA":     "#4060C0",
  "CONMEBOL": "#208040",
  "CAF":      "#B06020",
  "AFC":      "#6040A0",
  "CONCACAF": "#208080",
  "OFC":      "#208090",
};

export function getNationBySlug(slug: string): WCNation | undefined {
  return WC2026_NATIONS.find((n) => n.countrySlug === slug);
}

/**
 * Map an ISO-2 (or GB subdivision) code to a flagcdn.com file code.
 * flagcdn.com only serves ISO 3166-1 alpha-2, so England/Scotland fall back to GB.
 */
export function flagcdnCode(iso2: string): string {
  if (iso2 === "GB-ENG" || iso2 === "GB-SCT") return "gb";
  return iso2.toLowerCase();
}
