-- ============================================================
-- Fix: profiles INSERT policy (missing — causes pantry FK error)
-- ============================================================
drop policy if exists "Users can insert own profile" on profiles;
create policy "Users can insert own profile"
  on profiles for insert with check (auth.uid() = id);

-- Back-fill any auth users who don't yet have a profile row
insert into public.profiles (id, full_name)
select
  u.id,
  u.raw_user_meta_data->>'full_name'
from auth.users u
where u.id not in (select id from public.profiles)
on conflict (id) do nothing;

-- ============================================================
-- Add premium + hack flags to recipes
-- ============================================================
alter table recipes
  add column if not exists is_premium boolean not null default false,
  add column if not exists is_hack    boolean not null default false;

-- Widen source check to include 'social'
alter table recipes
  drop constraint if exists recipes_source_check;

alter table recipes
  add constraint recipes_source_check
  check (source in ('spoonacular','ai','curated','user','social'));

-- ============================================================
-- Social / Instagram recipe stubs — Hacks (8 posts)
-- ============================================================
insert into recipes (
  source, source_name, source_url,
  title, description, image_url,
  cuisine_type, dish_types, dietary_tags,
  ingredients, instructions,
  is_premium, is_hack,
  prep_time_minutes, cook_time_minutes, servings
) values

('social','Instagram','https://www.instagram.com/p/DWD_ey1DGTO/',
 'Viral Kitchen Hack #1',
 'A clever kitchen trick that changes how you cook — watch the original reel for the full technique.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1),

('social','Instagram','https://www.instagram.com/p/DVak712DO1T/',
 'Viral Kitchen Hack #2',
 'This simple technique will save you time in the kitchen every single day.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1),

('social','Instagram','https://www.instagram.com/p/DRm98bjiD3Q/',
 'Viral Kitchen Hack #3',
 'The hack professional chefs actually use — and never tell home cooks about.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1),

('social','Instagram','https://www.instagram.com/p/DO6WOoyDB9X/',
 'Viral Kitchen Hack #4',
 'Stop doing it the hard way. This kitchen trick is going viral for a reason.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1),

('social','Instagram','https://www.instagram.com/p/DIajZcwo22y/',
 'Viral Kitchen Hack #5',
 'The trick every home cook wishes they learned sooner.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1),

('social','Instagram','https://www.instagram.com/p/DGYqcZ4vspg/',
 'Viral Kitchen Hack #6',
 'This one weird trick makes your food taste restaurant-level every time.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1),

('social','Instagram','https://www.instagram.com/p/DFh-yimyzOH/',
 'Viral Kitchen Hack #7',
 'The shortcut that cuts your prep time in half — seriously.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1),

('social','Instagram','https://www.instagram.com/p/DGtEjTkvqPl/',
 'Viral Kitchen Hack #8',
 'Chefs hate this trick. Home cooks love it.',
 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
 'General', ARRAY['hack'], ARRAY[]::text[],
 '[]'::jsonb, ARRAY['See Instagram post for full technique.'],
 true, true, 0, 0, 1);

-- ============================================================
-- Social / Instagram recipe stubs — Premium recipes
-- (stored as source_url for embedding; title populated on first view)
-- ============================================================
insert into recipes (
  source, source_name, source_url,
  title, description, image_url,
  cuisine_type, dish_types, dietary_tags,
  ingredients, instructions,
  is_premium, is_hack,
  prep_time_minutes, cook_time_minutes, servings
)
select
  'social', 'Instagram', url,
  'Premium Recipe', -- placeholder; shown as embed
  'Exclusive recipe from our curated Instagram collection. Click to view the full post.',
  'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80',
  'Social', ARRAY['premium']::text[], ARRAY[]::text[],
  '[]'::jsonb, ARRAY['See the Instagram post for the full recipe.'],
  true, false,
  0, 0, 1
from (values
  ('https://www.instagram.com/p/DWt3vzAkSro/'),
  ('https://www.instagram.com/p/DVWSJPbjYq3/'),
  ('https://www.instagram.com/p/DVbK2KgDTMt/'),
  ('https://www.instagram.com/p/DVN59rIiAUn/'),
  ('https://www.instagram.com/p/DVdiPffiFyf/'),
  ('https://www.instagram.com/p/DSSwBKIDYI5/'),
  ('https://www.instagram.com/p/DVRHCHAjsuT/'),
  ('https://www.instagram.com/p/DVQ6qb0DMWH/'),
  ('https://www.instagram.com/p/DVRMXq6Cibl/'),
  ('https://www.instagram.com/p/DVE3we1CCXG/'),
  ('https://www.instagram.com/p/DVL0_uGDcib/'),
  ('https://www.instagram.com/p/DVDgI_vjWU4/'),
  ('https://www.instagram.com/p/DVM7azeEakc/'),
  ('https://www.instagram.com/p/DU0tklaDl6L/'),
  ('https://www.instagram.com/p/DUivA-UiEK5/'),
  ('https://www.instagram.com/p/DT0lSYyj9od/'),
  ('https://www.instagram.com/p/DS20IaMjFHs/'),
  ('https://www.instagram.com/p/DUSpp8fDMXY/'),
  ('https://www.instagram.com/p/DUnVQzkkewj/'),
  ('https://www.instagram.com/p/DVDd_rFDavT/'),
  ('https://www.instagram.com/p/DU8oKcICFyV/'),
  ('https://www.instagram.com/p/DOGJ-LoDORe/'),
  ('https://www.instagram.com/p/DU3XP1vjDYD/'),
  ('https://www.instagram.com/p/DTQLc0pEYNp/'),
  ('https://www.instagram.com/p/DUdH-w3DZVE/'),
  ('https://www.instagram.com/p/DUSzfxukfkn/'),
  ('https://www.instagram.com/p/DSNNkHQjFtO/'),
  ('https://www.instagram.com/p/DT5JnPQjBhC/'),
  ('https://www.instagram.com/p/DTGYxt2kVEU/'),
  ('https://www.instagram.com/p/DT3QfM0ET1W/'),
  ('https://www.instagram.com/p/DTWl6JGEfyb/'),
  ('https://www.instagram.com/p/DT3R-rxjFZY/'),
  ('https://www.instagram.com/p/DN3KlBA0OvE/'),
  ('https://www.instagram.com/p/DOoDa6WCP27/'),
  ('https://www.instagram.com/p/DPjaQZeiHH9/'),
  ('https://www.instagram.com/p/DRudxP5iEuc/'),
  ('https://www.instagram.com/p/DSFt8_iiCsg/'),
  ('https://www.instagram.com/p/DSh-v-EiGQk/'),
  ('https://www.instagram.com/p/DTQSxT6iGqi/'),
  ('https://www.instagram.com/p/DTk4079CDaX/'),
  ('https://www.instagram.com/p/DTimOPZCE_S/'),
  ('https://www.instagram.com/p/DS8dE-okiBS/'),
  ('https://www.instagram.com/p/DRrix-KCAoG/'),
  ('https://www.instagram.com/p/DTVL9AZiA-i/'),
  ('https://www.instagram.com/p/DTF1DwJCKEq/'),
  ('https://www.instagram.com/p/DTGSwbHCFBQ/'),
  ('https://www.instagram.com/p/DTQqWSQDRrR/'),
  ('https://www.instagram.com/p/DTnyDn9CGV_/'),
  ('https://www.instagram.com/p/DTYWmIxiJ4s/'),
  ('https://www.instagram.com/p/DTa1XM2CMM2/'),
  ('https://www.instagram.com/p/DTlEq2TDZX2/'),
  ('https://www.instagram.com/p/C7CQEmeKgT0/'),
  ('https://www.instagram.com/p/DDmoIvFoG1G/'),
  ('https://www.instagram.com/p/DFvVjctKF_H/'),
  ('https://www.instagram.com/p/DHJfP02ITGl/'),
  ('https://www.instagram.com/p/DIeRl0gqsN-/'),
  ('https://www.instagram.com/p/DI1feVGq472/'),
  ('https://www.instagram.com/p/DJW7pG0KezQ/'),
  ('https://www.instagram.com/p/DJrmT-UqIoR/'),
  ('https://www.instagram.com/p/DMDOt3foFJK/'),
  ('https://www.instagram.com/p/DNLHteFoPG8/'),
  ('https://www.instagram.com/p/DPCBGEKCKO8/'),
  ('https://www.instagram.com/p/DRDAX9iEs9j/'),
  ('https://www.instagram.com/p/DS-r5etCK2B/'),
  ('https://www.instagram.com/p/DTFbXmkjM2n/'),
  ('https://www.instagram.com/p/DSVeN5QAgWy/'),
  ('https://www.instagram.com/p/DRm5mr_CIHt/'),
  ('https://www.instagram.com/p/DRhVJKqDKlP/'),
  ('https://www.instagram.com/p/DRNN8XcjYE1/'),
  ('https://www.instagram.com/p/DMbXSpZBCj2/'),
  ('https://www.instagram.com/p/DQmqY-XDazr/'),
  ('https://www.instagram.com/p/DQzEzheDSiJ/'),
  ('https://www.instagram.com/p/DOLTPQSCI1q/'),
  ('https://www.instagram.com/p/DOeBDYTjMY5/'),
  ('https://www.instagram.com/p/DQZmh3dja0s/'),
  ('https://www.instagram.com/p/DQZavImDYW6/'),
  ('https://www.instagram.com/p/DQcL-2EjNb9/'),
  ('https://www.instagram.com/p/DQj9bHIkaZ1/'),
  ('https://www.instagram.com/p/DPltk3nDKG6/'),
  ('https://www.instagram.com/p/DQMuhpSiOza/'),
  ('https://www.instagram.com/p/DMp4QqkMdLY/'),
  ('https://www.instagram.com/p/DPcuUToEbzN/'),
  ('https://www.instagram.com/p/DP6_QhAElf4/'),
  ('https://www.instagram.com/p/DNk4rcaPLyQ/'),
  ('https://www.instagram.com/p/DO_SxfxDWRD/'),
  ('https://www.instagram.com/p/DPAwmcgDA1D/'),
  ('https://www.instagram.com/p/DPG5ckDDMn3/'),
  ('https://www.instagram.com/p/DOo62eoDcD3/'),
  ('https://www.instagram.com/p/DOWY0GyiAut/'),
  ('https://www.instagram.com/p/DOcN2b7EjVZ/'),
  ('https://www.instagram.com/p/DOZ-XXbkqVO/'),
  ('https://www.instagram.com/p/DNQNS6doytC/'),
  ('https://www.instagram.com/p/DLjB9L7MYNx/'),
  ('https://www.instagram.com/p/DNN9TDgM7Tu/'),
  ('https://www.instagram.com/p/DM8JZd1tTP1/'),
  ('https://www.instagram.com/p/DMci2ELITAo/'),
  ('https://www.instagram.com/p/DF0ReimMgZm/'),
  ('https://www.instagram.com/p/DMvHTywsfhC/'),
  ('https://www.instagram.com/p/DMfmxbetGor/'),
  ('https://www.instagram.com/p/DL9g8IHtUHW/'),
  ('https://www.instagram.com/p/DLVnQNQSmM4/'),
  ('https://www.instagram.com/p/DLpw7y0tXlW/'),
  ('https://www.instagram.com/p/DKo32E8N0en/'),
  ('https://www.instagram.com/p/DKoamZjKhBj/'),
  ('https://www.instagram.com/p/DLDLHyLscwl/'),
  ('https://www.instagram.com/p/DLNXCHXgGDH/'),
  ('https://www.instagram.com/p/DKs_SC8u6FA/'),
  ('https://www.instagram.com/p/DKzpzgEIbFv/'),
  ('https://www.instagram.com/p/DEvKwU-sfG7/'),
  ('https://www.instagram.com/p/DJoCpaCojEx/'),
  ('https://www.instagram.com/p/DJv5Zbyu0iO/'),
  ('https://www.instagram.com/p/DH--Hd4INBf/'),
  ('https://www.instagram.com/p/DJzeWcPJ28k/'),
  ('https://www.instagram.com/p/DJj4Bbmse25/'),
  ('https://www.instagram.com/p/DJrM-o-tcZV/'),
  ('https://www.instagram.com/p/DJZWeBTIBt-/'),
  ('https://www.instagram.com/p/DJb639CI-sm/'),
  ('https://www.instagram.com/p/DJR2W31Ivej/'),
  ('https://www.instagram.com/p/DGpkf6xMm-7/'),
  ('https://www.instagram.com/p/DJBJoGNsKjc/'),
  ('https://www.instagram.com/p/DH3p2MHMydJ/'),
  ('https://www.instagram.com/p/DIOrNb3xlfb/'),
  ('https://www.instagram.com/p/DGXpTCgIkoD/'),
  ('https://www.instagram.com/p/DHT3hh6IRPl/'),
  ('https://www.instagram.com/p/DE8PaZStb7s/'),
  ('https://www.instagram.com/p/DHUAKowxMMk/'),
  ('https://www.instagram.com/p/DHOQ1gJICNE/'),
  ('https://www.instagram.com/p/DHLL6IgSfR5/'),
  ('https://www.instagram.com/p/DBDlk3Mp6Ww/'),
  ('https://www.instagram.com/p/DHEO9XjtOgp/'),
  ('https://www.instagram.com/p/DB3_p82uCSv/'),
  ('https://www.instagram.com/p/DGgAUi9qvAy/'),
  ('https://www.instagram.com/p/DFh-yimyzOH/'),
  ('https://www.instagram.com/p/DGiKRfiMlFA/'),
  ('https://www.instagram.com/p/DG0yrx_NVd_/'),
  ('https://www.instagram.com/p/DGyN3oGMjD_/'),
  ('https://www.instagram.com/p/DGvpC8RsREb/'),
  ('https://www.instagram.com/p/DG3XppgsqSD/'),
  ('https://www.instagram.com/p/DG3Fy6ERtwu/'),
  ('https://www.instagram.com/p/DGePwiySkH4/'),
  ('https://www.instagram.com/p/DGbc6wwOvng/'),
  ('https://www.instagram.com/p/DC2fx6XOD5c/'),
  ('https://www.instagram.com/p/DDruonxvUN5/'),
  ('https://www.instagram.com/p/DGNndC8Nq9b/'),
  ('https://www.instagram.com/p/DFLsTAeKf00/'),
  ('https://www.instagram.com/p/DG5NOzlqRvx/'),
  ('https://www.instagram.com/p/DFkkY6WNihv/'),
  ('https://www.instagram.com/p/DGNx_sgqd_Z/'),
  ('https://www.instagram.com/p/DGc-xXjMP5W/'),
  ('https://www.instagram.com/p/DFVbCPPRdLQ/'),
  ('https://www.instagram.com/p/DBJljXcN5MP/'),
  ('https://www.instagram.com/p/DGqaXdPRIlO/'),
  ('https://www.instagram.com/p/DEnRrjMoOR9/'),
  ('https://www.instagram.com/p/DFcaZedI4Fx/'),
  ('https://www.instagram.com/p/DFt8Tq9OsQx/'),
  ('https://www.instagram.com/p/DGSsyy5tXG-/'),
  ('https://www.instagram.com/p/DGQryILIhoZ/'),
  ('https://www.instagram.com/p/DEXi2aTMPZY/'),
  ('https://www.instagram.com/p/DFAu-cct5cq/'),
  ('https://www.instagram.com/p/DFLB1m5NBRs/'),
  ('https://www.instagram.com/p/DF79BZHtELW/'),
  ('https://www.instagram.com/p/DGDyxS2N_1C/'),
  ('https://www.instagram.com/p/DCYOBXbu0wF/'),
  ('https://www.instagram.com/p/DFScYglSqCE/'),
  ('https://www.instagram.com/p/DFvsVH_OD9h/'),
  ('https://www.instagram.com/p/DFvN98ROMlT/'),
  ('https://www.instagram.com/p/DE0Hw-yNr-M/'),
  ('https://www.instagram.com/p/DFae52GPCVG/'),
  ('https://www.instagram.com/p/C_KrgA0oUCf/'),
  ('https://www.instagram.com/p/DCEId_SO1k1/'),
  ('https://www.instagram.com/p/DEc_Zw3i_yR/'),
  ('https://www.instagram.com/p/DEkT-UKocvb/'),
  ('https://www.instagram.com/p/DEhIIVjMIhL/'),
  ('https://www.instagram.com/p/DEU4IELSWc9/'),
  ('https://www.instagram.com/p/DEXaycBSsaD/'),
  ('https://www.instagram.com/p/DEaSWzUSVF7/'),
  ('https://www.instagram.com/p/DEcXJ38yfZU/'),
  ('https://www.instagram.com/p/C_YJUMqoJv2/'),
  ('https://www.instagram.com/p/DC7GQQvN6UY/'),
  ('https://www.instagram.com/p/DEaNxwwIbJL/'),
  ('https://www.instagram.com/p/DDciHEDiSmE/'),
  ('https://www.instagram.com/p/DEOajC4pHLF/'),
  ('https://www.instagram.com/p/DETn4QOpQib/'),
  ('https://www.instagram.com/p/DDHteM4ukZp/'),
  ('https://www.instagram.com/p/DC6z2R7tHQ4/'),
  ('https://www.instagram.com/p/DEdT8BgNwZT/'),
  ('https://www.instagram.com/p/DDzeac_ueIa/'),
  ('https://www.instagram.com/p/C_a2xcOs4eu/'),
  ('https://www.instagram.com/p/DDNJKr-RAZB/'),
  ('https://www.instagram.com/p/DA_pertJhf3/'),
  ('https://www.instagram.com/p/DDXXCCBoEUf/'),
  ('https://www.instagram.com/p/DDVFHI2xH7G/'),
  ('https://www.instagram.com/p/DC4Y6tIRqV3/'),
  ('https://www.instagram.com/p/DDOoR4doo7-/'),
  ('https://www.instagram.com/p/DDNUUCQOT7b/'),
  ('https://www.instagram.com/p/DDFILqTtvk5/'),
  ('https://www.instagram.com/p/DCsWTtkoaa9/'),
  ('https://www.instagram.com/p/DCp_T2ERka8/'),
  ('https://www.instagram.com/p/DCZmmdSOSx1/'),
  ('https://www.instagram.com/p/DCNOLT7yU2Z/'),
  ('https://www.instagram.com/p/C_tMioPyVnY/'),
  ('https://www.instagram.com/p/DBZK2yGsIVb/'),
  ('https://www.instagram.com/p/DBlq9vSMl5X/'),
  ('https://www.instagram.com/p/DBO2BxAo3jL/'),
  ('https://www.instagram.com/p/DBy-4-EIkEx/'),
  ('https://www.instagram.com/p/DA05aVto2Al/'),
  ('https://www.instagram.com/p/DBOoWPbIUS_/'),
  ('https://www.instagram.com/p/DBzEO7LJEXa/'),
  ('https://www.instagram.com/p/DAvS2M3oTqX/'),
  ('https://www.instagram.com/p/DBMEtFBpC6I/'),
  ('https://www.instagram.com/p/DBgKtn-sxaC/'),
  ('https://www.instagram.com/p/DATxLmOSj2W/'),
  ('https://www.instagram.com/p/DAWIDckI-cR/'),
  ('https://www.instagram.com/p/DARBBwTC0B-/'),
  ('https://www.instagram.com/p/DAJUHKao_2b/'),
  ('https://www.instagram.com/p/DAGNK2wxMey/'),
  ('https://www.instagram.com/p/C_eSJ_HSxbS/'),
  ('https://www.instagram.com/p/DAEmRB-tr8Q/'),
  ('https://www.instagram.com/p/C97I5H6t9b3/'),
  ('https://www.instagram.com/p/C--K-bjJbRT/'),
  ('https://www.instagram.com/p/C_fxqIpyewh/'),
  ('https://www.instagram.com/p/C_swe_eSbuo/'),
  ('https://www.instagram.com/p/C-YSupXJ0-F/'),
  ('https://www.instagram.com/p/C--RVRbyyM-/'),
  ('https://www.instagram.com/p/C9uxh_BKdQ4/'),
  ('https://www.instagram.com/p/C92gVFSqFow/'),
  ('https://www.instagram.com/p/C9-FMxZqtHl/'),
  ('https://www.instagram.com/p/C-YDgLOKJql/'),
  ('https://www.instagram.com/p/C-iDPmIKgZ2/'),
  ('https://www.instagram.com/p/C-p_2XCKYD5/'),
  ('https://www.instagram.com/p/DABi_zBIYgp/'),
  ('https://www.instagram.com/p/C-K4wdQKfsl/'),
  ('https://www.instagram.com/p/C_-IqP-SoDJ/'),
  ('https://www.instagram.com/p/C_qL05zxCdg/'),
  ('https://www.instagram.com/p/C8sCTestYf5/'),
  ('https://www.instagram.com/p/C97Sx4BKVKh/'),
  ('https://www.instagram.com/p/C_2ixsBN04I/'),
  ('https://www.instagram.com/p/C_3KYX_NFE0/'),
  ('https://www.instagram.com/p/C_v7IAvoDm9/'),
  ('https://www.instagram.com/p/C_vk_EkIaBt/'),
  ('https://www.instagram.com/p/C9WxFLuqLAS/')
) as t(url)
on conflict do nothing;
