-- ══════════════════════════════════════════════════════════════════
-- MORE DRINKS: Cocktails, Mocktails, Smoothies, Brewed
-- Run AFTER fix_duplicates.sql
-- ══════════════════════════════════════════════════════════════════

INSERT INTO recipes (source, source_name, source_url, title, description, image_url, cuisine_type, dish_types, dietary_tags, ingredients, instructions, prep_time_minutes, cook_time_minutes, servings, calories, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg) VALUES

-- ══ COCKTAILS ══════════════════════════════════════════════════════

('curated','Serious Eats','https://www.seriouseats.com/old-fashioned-recipe',
 'Old Fashioned',
 'Bourbon or rye, a sugar cube, Angostura bitters, and an orange peel. The original cocktail — unchanged for 200 years because it cannot be improved.',
 'https://images.unsplash.com/photo-1527661591914-5b67fd703b82?w=800&q=80',
 'American',ARRAY['drink','cocktail'],ARRAY[]::text[],
 '[{"name":"bourbon or rye whiskey","amount":60,"unit":"ml"},{"name":"sugar cube","amount":1,"unit":"whole"},{"name":"Angostura bitters","amount":2,"unit":"dashes"},{"name":"orange peel","amount":1,"unit":"strip"},{"name":"ice","amount":1,"unit":"large cube"}]'::jsonb,
 ARRAY['Place sugar cube in a rocks glass. Saturate with bitters and a splash of water.','Muddle until sugar dissolves.','Add ice cube.','Pour whiskey over ice.','Stir 20 times.','Express orange peel over the glass, run around the rim, drop in.'],
 3,0,1,160,0,6,0,0,6,5),

('curated','NYT Cooking','https://cooking.nytimes.com/recipes/1021671-daiquiri',
 'Classic Daiquiri',
 'Two parts rum, one part fresh lime, three-quarter parts simple syrup. The most abused cocktail in the world, and also the most perfect when made correctly.',
 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80',
 'Cuban',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"white rum","amount":60,"unit":"ml"},{"name":"fresh lime juice","amount":30,"unit":"ml"},{"name":"simple syrup","amount":22,"unit":"ml"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Add rum, lime juice, and simple syrup to a shaker.','Fill with ice.','Shake hard for 15 seconds.','Double-strain into a chilled coupe glass.','Garnish with a lime wheel if desired.'],
 3,0,1,175,0,12,0,0,10,5),

('curated','Bon Appétit','https://www.bonappetit.com/recipe/classic-mojito',
 'Classic Mojito',
 'White rum, fresh mint, lime, sugar, soda. Cuba''s most famous export — bright, herbaceous, and dangerously easy to drink.',
 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
 'Cuban',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"white rum","amount":60,"unit":"ml"},{"name":"fresh mint leaves","amount":10,"unit":"leaves"},{"name":"lime","amount":1,"unit":"whole"},{"name":"sugar syrup","amount":22,"unit":"ml"},{"name":"soda water","amount":90,"unit":"ml"},{"name":"crushed ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Muddle mint with sugar syrup in a highball glass — gently, just to bruise, not shred.','Cut lime into wedges, squeeze all juice in, drop wedges.','Fill glass with crushed ice.','Pour rum over ice.','Top with soda water.','Stir briefly. Garnish with mint sprig.'],
 5,0,1,195,0,16,0,0,12,10),

('curated','Serious Eats','https://www.seriouseats.com/whiskey-sour-recipe',
 'Whiskey Sour',
 'Bourbon, fresh lemon juice, simple syrup, and — the controversial part — an egg white for that silky foam. One of the essential five.',
 'https://images.unsplash.com/photo-1516535794938-6063878f08cc?w=800&q=80',
 'American',ARRAY['drink','cocktail'],ARRAY[]::text[],
 '[{"name":"bourbon","amount":60,"unit":"ml"},{"name":"fresh lemon juice","amount":30,"unit":"ml"},{"name":"simple syrup","amount":22,"unit":"ml"},{"name":"egg white","amount":1,"unit":"whole"},{"name":"Angostura bitters","amount":2,"unit":"dashes"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Combine bourbon, lemon juice, syrup, and egg white in a shaker (no ice).','Dry-shake vigorously for 15 seconds to emulsify the egg white.','Add ice and shake again for 15 seconds.','Strain into a rocks glass over ice, or into a coupe.','Add bitters dashes on the foam for garnish.'],
 5,0,1,185,3,14,1,0,12,20),

('curated','NYT Cooking','https://cooking.nytimes.com/recipes/1014697-manhattan',
 'Manhattan',
 'Rye whiskey, sweet vermouth, bitters. Three ingredients, stirred cold. The drink that made New York famous.',
 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
 'American',ARRAY['drink','cocktail'],ARRAY[]::text[],
 '[{"name":"rye whiskey","amount":60,"unit":"ml"},{"name":"sweet vermouth","amount":30,"unit":"ml"},{"name":"Angostura bitters","amount":2,"unit":"dashes"},{"name":"maraschino cherry","amount":1,"unit":"whole"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Add whiskey, vermouth, and bitters to a mixing glass.','Fill with ice.','Stir for 30 seconds until well-chilled and diluted.','Strain into a chilled coupe or martini glass.','Garnish with maraschino cherry.'],
 3,0,1,165,0,7,0,0,6,5),

('curated','Bon Appétit','https://www.bonappetit.com/recipe/espresso-martini',
 'Espresso Martini',
 'Vodka, coffee liqueur, and freshly pulled espresso shaken hard so the foam crowns perfectly. The drink that ended dinner parties.',
 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
 'British',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"vodka","amount":50,"unit":"ml"},{"name":"coffee liqueur","amount":20,"unit":"ml"},{"name":"fresh espresso","amount":30,"unit":"ml"},{"name":"simple syrup","amount":10,"unit":"ml"},{"name":"ice","amount":1,"unit":"cup"},{"name":"coffee beans","amount":3,"unit":"whole (garnish)"}]'::jsonb,
 ARRAY['Pull espresso and let cool slightly (30 seconds).','Add vodka, coffee liqueur, syrup, and espresso to shaker.','Fill with ice.','Shake very hard for 20 seconds — the force creates the foam.','Double-strain into chilled coupe glass.','Float 3 coffee beans on the foam.'],
 5,0,1,190,0,14,0,0,12,10),

('curated','Serious Eats','https://www.seriouseats.com/gin-tonic-recipe',
 'Perfect Gin & Tonic',
 'The ratio matters: 1 part gin to 2 parts tonic. Premium tonic, good gin, the right garnish. The simplest cocktail done properly.',
 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=800&q=80',
 'British',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"London Dry gin","amount":50,"unit":"ml"},{"name":"premium tonic water","amount":100,"unit":"ml"},{"name":"lime wedge","amount":1,"unit":"whole"},{"name":"ice","amount":1,"unit":"large handful"},{"name":"juniper berries","amount":3,"unit":"whole (optional)"}]'::jsonb,
 ARRAY['Fill a highball glass to the brim with ice.','Pour gin over ice.','Pour tonic water slowly down the side of the glass to preserve carbonation.','Squeeze lime over, drop in.','Stir once, gently.','Garnish with juniper berries if using.'],
 2,0,1,145,0,10,0,0,8,5),

('curated','Punch Drink','https://punchdrink.com/recipes/moscow-mule',
 'Moscow Mule',
 'Vodka, ginger beer, lime juice served in a copper mug (which actually does make it taste better). Invented in 1940s Hollywood, still undeniably excellent.',
 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
 'American',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"vodka","amount":60,"unit":"ml"},{"name":"ginger beer","amount":150,"unit":"ml"},{"name":"fresh lime juice","amount":15,"unit":"ml"},{"name":"lime wedge","amount":1,"unit":"whole"},{"name":"mint sprigs","amount":2,"unit":"whole"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Fill a copper mug with ice.','Add vodka and lime juice.','Top with ginger beer.','Stir gently once.','Garnish with lime wedge and mint sprig.'],
 3,0,1,150,0,12,0,0,10,15),

('curated','Bon Appétit','https://www.bonappetit.com/recipe/paloma',
 'Paloma',
 'Tequila and fresh grapefruit juice topped with soda. Mexico''s most popular tequila drink — more widely drunk there than the margarita.',
 'https://images.unsplash.com/photo-1609345265499-2b5cb6b6b5f8?w=800&q=80',
 'Mexican',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"blanco tequila","amount":60,"unit":"ml"},{"name":"fresh grapefruit juice","amount":90,"unit":"ml"},{"name":"fresh lime juice","amount":15,"unit":"ml"},{"name":"agave syrup","amount":10,"unit":"ml"},{"name":"soda water","amount":60,"unit":"ml"},{"name":"salt","amount":1,"unit":"pinch"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Salt the rim of a highball glass: rub with lime, dip in salt.','Fill with ice.','Combine tequila, grapefruit juice, lime juice, and agave in a shaker.','Shake with ice, strain over fresh ice.','Top with soda water.','Stir gently.'],
 5,0,1,180,0,16,0,0,14,120),

('curated','Serious Eats','https://www.seriouseats.com/french-75-cocktail',
 'French 75',
 'Gin, lemon juice, simple syrup, topped with champagne. Named after the French 75mm field gun because it hits just as hard.',
 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80',
 'French',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"London Dry gin","amount":45,"unit":"ml"},{"name":"fresh lemon juice","amount":22,"unit":"ml"},{"name":"simple syrup","amount":15,"unit":"ml"},{"name":"champagne or dry sparkling wine","amount":90,"unit":"ml"},{"name":"ice","amount":1,"unit":"cup"},{"name":"lemon twist","amount":1,"unit":"strip"}]'::jsonb,
 ARRAY['Add gin, lemon juice, and simple syrup to a shaker with ice.','Shake well for 12 seconds.','Strain into a chilled champagne flute.','Top with champagne.','Garnish with lemon twist.'],
 4,0,1,210,0,14,0,0,12,5),

('curated','Punch Drink','https://punchdrink.com/recipes/amaretto-sour',
 'Amaretto Sour',
 'The best amaretto sour is made with cask-strength bourbon to balance the sweetness, plus egg white for texture. Unpretentious and deeply satisfying.',
 'https://images.unsplash.com/photo-1516535794938-6063878f08cc?w=800&q=80',
 'American',ARRAY['drink','cocktail'],ARRAY[]::text[],
 '[{"name":"amaretto","amount":45,"unit":"ml"},{"name":"cask-strength bourbon","amount":22,"unit":"ml"},{"name":"fresh lemon juice","amount":30,"unit":"ml"},{"name":"simple syrup","amount":7,"unit":"ml"},{"name":"egg white","amount":1,"unit":"whole"},{"name":"Angostura bitters","amount":2,"unit":"dashes"}]'::jsonb,
 ARRAY['Combine amaretto, bourbon, lemon juice, syrup, and egg white in shaker (no ice).','Dry-shake 15 seconds.','Add ice, shake again 15 seconds.','Strain into rocks glass over ice.','Dot bitters on foam.'],
 5,0,1,195,3,20,1,0,18,15),

('curated','Bon Appétit','https://www.bonappetit.com/recipe/dark-and-stormy',
 'Dark & Stormy',
 'Gosling''s Black Seal rum and Barritt''s Bermuda Stone ginger beer — technically the only legal Dark & Stormy, but any dark rum and spicy ginger beer works beautifully.',
 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
 'Bermudian',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"dark rum","amount":60,"unit":"ml"},{"name":"ginger beer","amount":120,"unit":"ml"},{"name":"fresh lime juice","amount":15,"unit":"ml"},{"name":"lime wedge","amount":1,"unit":"whole"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Fill a highball glass with ice.','Add lime juice.','Pour ginger beer over ice.','Float rum on top — pour slowly over the back of a spoon.','Garnish with lime wedge. Do not stir; the layers are the point.'],
 3,0,1,165,0,14,0,0,12,20),

('curated','Serious Eats','https://www.seriouseats.com/pisco-sour',
 'Pisco Sour',
 'Peru''s national drink and one of the great cocktails: pisco, lime, simple syrup, egg white, and bitters on top. Frothy, citrusy, and completely addictive.',
 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
 'Peruvian',ARRAY['drink','cocktail'],ARRAY[]::text[],
 '[{"name":"pisco","amount":60,"unit":"ml"},{"name":"fresh lime juice","amount":30,"unit":"ml"},{"name":"simple syrup","amount":22,"unit":"ml"},{"name":"egg white","amount":1,"unit":"whole"},{"name":"Angostura bitters","amount":3,"unit":"drops"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Add pisco, lime, syrup, and egg white to shaker with no ice.','Dry-shake 20 seconds.','Add ice, shake again 15 seconds.','Strain into a chilled old-fashioned glass (no ice).','Drop bitters on top of foam.'],
 5,0,1,185,3,15,1,0,13,15),

('curated','NYT Cooking','https://cooking.nytimes.com/recipes/1016234-cosmopolitan',
 'Cosmopolitan',
 'Citrus vodka, triple sec, cranberry juice, and fresh lime. Made famous by Sex and the City, unfairly dismissed, absolutely delicious when made properly.',
 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800&q=80',
 'American',ARRAY['drink','cocktail'],ARRAY['vegan','dairy-free'],
 '[{"name":"citrus vodka","amount":45,"unit":"ml"},{"name":"Cointreau","amount":22,"unit":"ml"},{"name":"cranberry juice","amount":22,"unit":"ml"},{"name":"fresh lime juice","amount":15,"unit":"ml"},{"name":"ice","amount":1,"unit":"cup"},{"name":"orange peel","amount":1,"unit":"strip"}]'::jsonb,
 ARRAY['Add all ingredients to a shaker with ice.','Shake hard for 15 seconds.','Strain into chilled martini glass.','Express orange peel over glass, discard or use as garnish.'],
 3,0,1,195,0,16,0,0,14,15),

-- ══ MOCKTAILS ══════════════════════════════════════════════════════

('curated','Serious Eats','https://www.seriouseats.com/shirley-temple',
 'Shirley Temple',
 'Ginger ale, grenadine, and orange juice. The original "fancy" drink for non-drinkers — and still excellent when made with quality grenadine.',
 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80',
 'American',ARRAY['drink','mocktail'],ARRAY['vegetarian','vegan','dairy-free'],
 '[{"name":"ginger ale","amount":200,"unit":"ml"},{"name":"grenadine","amount":30,"unit":"ml"},{"name":"fresh orange juice","amount":60,"unit":"ml"},{"name":"maraschino cherry","amount":1,"unit":"whole"},{"name":"orange slice","amount":1,"unit":"whole"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Fill a tall glass with ice.','Add orange juice.','Add ginger ale.','Drizzle grenadine in slowly so it sinks to the bottom.','Garnish with orange slice and cherry.','Stir just before drinking.'],
 3,0,1,110,0,28,0,0,26,25),

('curated','AllRecipes','https://www.allrecipes.com/recipe/arnold-palmer',
 'Arnold Palmer',
 'Half sweet iced tea, half fresh lemonade. Named after the legendary golfer. The most refreshing non-alcoholic drink ever conceived.',
 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=800&q=80',
 'American',ARRAY['drink','mocktail'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"strong brewed black tea","amount":200,"unit":"ml (cooled)"},{"name":"fresh lemonade","amount":200,"unit":"ml"},{"name":"lemon slices","amount":2,"unit":"whole"},{"name":"ice","amount":1,"unit":"cup"},{"name":"mint","amount":2,"unit":"sprigs"}]'::jsonb,
 ARRAY['Brew tea strong and cool completely.','Make lemonade: juice 4 lemons into 200ml water with 2 tbsp sugar.','Fill a tall glass with ice.','Pour tea over ice.','Gently add lemonade on top.','Garnish with lemon slices and mint.'],
 10,5,2,90,0,22,0,0,20,10),

('curated','Bon Appétit','https://www.bonappetit.com/recipe/cucumber-mint-cooler',
 'Cucumber Mint Cooler',
 'Fresh cucumber juice, mint, lime, and sparkling water. Cool, crisp, and refreshing enough to make summer bearable.',
 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
 'American',ARRAY['drink','mocktail'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"cucumber","amount":1,"unit":"whole"},{"name":"fresh mint","amount":15,"unit":"leaves"},{"name":"fresh lime juice","amount":30,"unit":"ml"},{"name":"simple syrup","amount":20,"unit":"ml"},{"name":"sparkling water","amount":200,"unit":"ml"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Blend cucumber until smooth. Strain through fine mesh sieve.','Muddle mint with simple syrup in a glass.','Add cucumber juice and lime juice.','Fill with ice and top with sparkling water.','Stir gently. Garnish with cucumber ribbons and mint.'],
 8,0,1,65,1,16,0,0,13,5),

('curated','NYT Cooking','https://cooking.nytimes.com/recipes/mango-lassi',
 'Mango Lassi',
 'Ripe mango, yogurt, milk, sugar, and cardamom. India''s most beloved drink — thick, tangy, sweet, and extraordinary with spicy food.',
 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80',
 'Indian',ARRAY['drink','mocktail'],ARRAY['vegetarian','gluten-free'],
 '[{"name":"ripe mango","amount":1,"unit":"large (or 200g frozen)"},{"name":"full-fat yogurt","amount":200,"unit":"ml"},{"name":"whole milk","amount":100,"unit":"ml"},{"name":"sugar","amount":2,"unit":"tbsp"},{"name":"cardamom","amount":0.25,"unit":"tsp"},{"name":"rose water","amount":1,"unit":"tsp (optional)"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Peel and dice mango.','Blend mango, yogurt, milk, sugar, and cardamom until very smooth.','Add ice and blend again until frothy.','Taste and adjust sweetness.','Pour into chilled glasses.','Garnish with a pinch of cardamom.'],
 8,0,2,185,5,34,4,1,30,65),

('curated','Serious Eats','https://www.seriouseats.com/passion-fruit-fizz',
 'Passion Fruit Fizz',
 'Passion fruit pulp, elderflower cordial, lime, and fizzy water. Tropical, fragrant, and sophisticated without a drop of alcohol.',
 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=800&q=80',
 'British',ARRAY['drink','mocktail'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"passion fruit","amount":2,"unit":"whole"},{"name":"elderflower cordial","amount":30,"unit":"ml"},{"name":"fresh lime juice","amount":20,"unit":"ml"},{"name":"sparkling water","amount":200,"unit":"ml"},{"name":"ice","amount":1,"unit":"cup"},{"name":"mint","amount":3,"unit":"leaves"}]'::jsonb,
 ARRAY['Scoop passion fruit pulp into a glass.','Add elderflower cordial and lime juice.','Stir to combine.','Fill glass with ice.','Top with sparkling water.','Garnish with mint leaves.'],
 3,0,1,75,1,18,0,1,16,5),

('curated','AllRecipes','https://www.allrecipes.com/recipe/lavender-lemonade',
 'Lavender Lemonade',
 'Homemade lavender syrup, fresh lemon juice, and still or sparkling water. Floral, elegant, and surprisingly easy to make at home.',
 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=800&q=80',
 'American',ARRAY['drink','mocktail'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"fresh lemon juice","amount":180,"unit":"ml (6 lemons)"},{"name":"dried lavender","amount":2,"unit":"tbsp"},{"name":"sugar","amount":150,"unit":"g"},{"name":"water","amount":1.2,"unit":"L"},{"name":"ice","amount":2,"unit":"cups"},{"name":"lavender sprigs","amount":4,"unit":"garnish"}]'::jsonb,
 ARRAY['Make lavender syrup: simmer sugar, 200ml water, and lavender for 10 min. Cool, strain.','Combine lemon juice, lavender syrup, and remaining cold water.','Taste and adjust.','Serve over ice.','Garnish with lavender sprig.'],
 15,10,6,105,0,27,0,0,25,5),

('curated','NYT Cooking','https://cooking.nytimes.com/recipes/ginger-beer-mule',
 'Alcohol-Free Ginger Mule',
 'Non-alcoholic spirit (Seedlip or similar), ginger beer, and fresh lime. All the burn and complexity of a mule with zero alcohol.',
 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
 'American',ARRAY['drink','mocktail'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"non-alcoholic spirit","amount":60,"unit":"ml"},{"name":"spicy ginger beer","amount":150,"unit":"ml"},{"name":"fresh lime juice","amount":20,"unit":"ml"},{"name":"mint sprigs","amount":3,"unit":"whole"},{"name":"ice","amount":1,"unit":"cup"},{"name":"lime wedge","amount":1,"unit":"garnish"}]'::jsonb,
 ARRAY['Fill a copper mug or highball with ice.','Add non-alcoholic spirit and lime juice.','Top with ginger beer.','Stir gently.','Garnish with mint and lime wedge.'],
 3,0,1,55,0,13,0,0,11,15),

-- ══ SMOOTHIES ══════════════════════════════════════════════════════

('curated','Bon Appétit','https://www.bonappetit.com/recipe/green-detox-smoothie',
 'Green Detox Smoothie',
 'Spinach, cucumber, green apple, ginger, lemon, and coconut water. It tastes far better than it sounds and makes you feel unreasonably virtuous.',
 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80',
 'American',ARRAY['drink','smoothie'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"baby spinach","amount":2,"unit":"large handfuls"},{"name":"cucumber","amount":0.5,"unit":"whole"},{"name":"green apple","amount":1,"unit":"whole"},{"name":"fresh ginger","amount":2,"unit":"cm piece"},{"name":"lemon","amount":0.5,"unit":"juiced"},{"name":"coconut water","amount":250,"unit":"ml"},{"name":"ice","amount":1,"unit":"cup"}]'::jsonb,
 ARRAY['Chop apple and cucumber roughly.','Add all ingredients to blender.','Blend on high 60 seconds until completely smooth.','Taste — adjust lemon or ginger.','Serve immediately over ice.'],
 5,0,1,95,3,20,0,3,14,80),

('curated','Serious Eats','https://www.seriouseats.com/mango-turmeric-smoothie',
 'Mango Turmeric Smoothie',
 'Frozen mango, turmeric, ginger, coconut milk, and black pepper (it activates the curcumin). Anti-inflammatory and brilliant.',
 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80',
 'American',ARRAY['drink','smoothie'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"frozen mango chunks","amount":200,"unit":"g"},{"name":"coconut milk","amount":200,"unit":"ml"},{"name":"turmeric","amount":1,"unit":"tsp"},{"name":"fresh ginger","amount":1,"unit":"cm piece"},{"name":"black pepper","amount":1,"unit":"pinch"},{"name":"honey","amount":1,"unit":"tsp"},{"name":"ice","amount":0.5,"unit":"cup"}]'::jsonb,
 ARRAY['Add all ingredients to blender.','Blend until smooth and creamy — about 45 seconds.','Taste and adjust sweetness with honey.','Pour into a glass and serve immediately.'],
 5,0,1,185,2,30,7,2,26,25),

('curated','AllRecipes','https://www.allrecipes.com/recipe/acai-berry-smoothie',
 'Açaí Berry Smoothie Bowl',
 'Açaí, frozen mixed berries, banana, and almond milk blended thick. Topped with granola and fresh fruit. The smoothie bowl that launched a thousand brunches.',
 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80',
 'Brazilian',ARRAY['drink','smoothie'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"açaí packet (frozen)","amount":100,"unit":"g"},{"name":"frozen mixed berries","amount":150,"unit":"g"},{"name":"banana","amount":1,"unit":"frozen"},{"name":"almond milk","amount":100,"unit":"ml"},{"name":"granola","amount":4,"unit":"tbsp (topping)"},{"name":"fresh strawberries","amount":6,"unit":"halved (topping)"},{"name":"coconut flakes","amount":2,"unit":"tbsp (topping)"}]'::jsonb,
 ARRAY['Blend açaí, berries, banana, and almond milk on high until thick and smooth.','Add only enough liquid to blend — it should be thicker than a regular smoothie.','Pour into a bowl.','Top with granola, strawberries, and coconut flakes.','Eat immediately.'],
 5,0,1,265,5,48,7,8,28,45),

('curated','NYT Cooking','https://cooking.nytimes.com/recipes/banana-peanut-butter-smoothie',
 'Banana Peanut Butter Smoothie',
 'Banana, peanut butter, oat milk, and a touch of honey. Thick, filling, and tastes like a milkshake. The best breakfast smoothie.',
 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80',
 'American',ARRAY['drink','smoothie'],ARRAY['vegetarian','vegan','dairy-free'],
 '[{"name":"ripe banana","amount":1,"unit":"frozen"},{"name":"peanut butter","amount":2,"unit":"tbsp"},{"name":"oat milk","amount":250,"unit":"ml"},{"name":"honey","amount":1,"unit":"tsp"},{"name":"vanilla extract","amount":0.5,"unit":"tsp"},{"name":"ice","amount":0.5,"unit":"cup"}]'::jsonb,
 ARRAY['Freeze banana in chunks (or use fresh for a thinner smoothie).','Add all ingredients to blender.','Blend until smooth and creamy.','Taste and adjust sweetness.','Serve immediately.'],
 3,0,1,295,9,42,10,3,24,65),

('curated','Bon Appétit','https://www.bonappetit.com/recipe/chocolate-avocado-smoothie',
 'Chocolate Avocado Smoothie',
 'Avocado, cacao powder, banana, and almond milk. Tastes like a chocolate milkshake but is genuinely nutritious. The healthy dessert smoothie.',
 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80',
 'American',ARRAY['drink','smoothie'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"ripe avocado","amount":0.5,"unit":"whole"},{"name":"frozen banana","amount":1,"unit":"whole"},{"name":"raw cacao powder","amount":2,"unit":"tbsp"},{"name":"almond milk","amount":250,"unit":"ml"},{"name":"medjool dates","amount":2,"unit":"pitted"},{"name":"vanilla extract","amount":0.5,"unit":"tsp"}]'::jsonb,
 ARRAY['Add all ingredients to blender.','Blend on high until completely smooth — about 60 seconds.','Taste; add more dates if not sweet enough.','Serve immediately with ice if desired.'],
 5,0,1,310,4,44,14,8,26,45),

-- ══ BREWED & HOT DRINKS ═══════════════════════════════════════════

('curated','Serious Eats','https://www.seriouseats.com/masala-chai-recipe',
 'Masala Chai',
 'Black tea simmered with cardamom, cinnamon, ginger, cloves, and black pepper, then steeped with whole milk. The real chai — not a syrup.',
 'https://images.unsplash.com/photo-1561336526-2914f13ceb36?w=800&q=80',
 'Indian',ARRAY['drink','brewed'],ARRAY['vegetarian','gluten-free'],
 '[{"name":"whole milk","amount":250,"unit":"ml"},{"name":"water","amount":250,"unit":"ml"},{"name":"black tea leaves","amount":2,"unit":"tsp"},{"name":"cardamom pods","amount":4,"unit":"crushed"},{"name":"cinnamon","amount":1,"unit":"stick"},{"name":"fresh ginger","amount":2,"unit":"cm slice"},{"name":"cloves","amount":3,"unit":"whole"},{"name":"black peppercorns","amount":5,"unit":"whole"},{"name":"sugar","amount":2,"unit":"tsp"}]'::jsonb,
 ARRAY['Combine water and all spices in a saucepan.','Bring to boil, reduce heat, simmer 3 minutes.','Add milk and sugar, bring back to gentle boil.','Add tea leaves, turn off heat, steep 3 minutes.','Strain through fine mesh sieve into mugs.','Serve immediately.'],
 5,10,2,120,4,14,5,0,12,60),

('curated','NYT Cooking','https://cooking.nytimes.com/recipes/turkish-coffee',
 'Traditional Turkish Coffee',
 'Finely ground coffee, water, and sugar simmered in a cezve until a dense foam crowns the top. Dark, thick, unfiltered, and serious.',
 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80',
 'Turkish',ARRAY['drink','brewed'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"Turkish-ground coffee","amount":2,"unit":"heaped tsp"},{"name":"cold water","amount":100,"unit":"ml"},{"name":"sugar","amount":1,"unit":"tsp (optional)"}]'::jsonb,
 ARRAY['Add cold water to cezve (small long-handled pot).','Add coffee and sugar (if using). Do not stir yet.','Heat over very low heat.','When coffee starts to warm, stir once.','Watch carefully — when foam rises to the top, remove from heat.','Spoon some foam into the cup, then pour the coffee.','Wait 2 minutes for grounds to settle before drinking.'],
 1,5,1,15,0,2,0,0,1,5),

('curated','Bon Appétit','https://www.bonappetit.com/recipe/dalgona-coffee',
 'Dalgona Coffee',
 'Equal parts instant coffee, sugar, and hot water whipped to a stiff foam, then spooned over cold milk. Went viral for good reason — it''s spectacular.',
 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80',
 'Korean',ARRAY['drink','brewed'],ARRAY['vegetarian','gluten-free'],
 '[{"name":"instant coffee","amount":2,"unit":"tbsp"},{"name":"sugar","amount":2,"unit":"tbsp"},{"name":"hot water","amount":2,"unit":"tbsp"},{"name":"whole milk","amount":250,"unit":"ml (cold or warm)"},{"name":"ice","amount":1,"unit":"cup (for iced version)"}]'::jsonb,
 ARRAY['Add instant coffee, sugar, and hot water to a bowl.','Whip with electric mixer (or by hand — expect 10+ minutes) until thick, glossy, and pale caramel coloured.','Fill a glass with ice and milk.','Spoon the coffee foam on top.','Stir together before drinking.'],
 10,0,1,125,4,22,3,0,20,55),

('curated','Serious Eats','https://www.seriouseats.com/lavender-latte',
 'Lavender London Fog Latte',
 'Earl Grey tea, lavender syrup, vanilla, and steamed oat milk. The most elegant afternoon drink — floral, warming, and deeply soothing.',
 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800&q=80',
 'British',ARRAY['drink','brewed'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"Earl Grey tea bags","amount":2,"unit":"whole"},{"name":"hot water","amount":100,"unit":"ml"},{"name":"lavender syrup","amount":20,"unit":"ml"},{"name":"vanilla extract","amount":0.5,"unit":"tsp"},{"name":"oat milk","amount":200,"unit":"ml"}]'::jsonb,
 ARRAY['Steep Earl Grey in 100ml hot water (just off boil) for 4 minutes. Remove bags.','Add lavender syrup and vanilla to tea.','Steam or heat oat milk until hot and frothy.','Pour tea into mug.','Add steamed oat milk.','Garnish with a pinch of dried lavender.'],
 8,0,1,95,2,16,2,0,14,75),

('curated','AllRecipes','https://www.allrecipes.com/recipe/golden-milk',
 'Turmeric Golden Milk',
 'Warm milk with turmeric, ginger, cinnamon, and black pepper. An Ayurvedic drink with real anti-inflammatory benefits and a surprisingly beautiful golden colour.',
 'https://images.unsplash.com/photo-1561336526-2914f13ceb36?w=800&q=80',
 'Indian',ARRAY['drink','brewed'],ARRAY['vegetarian','vegan','gluten-free','dairy-free'],
 '[{"name":"oat milk","amount":300,"unit":"ml"},{"name":"turmeric powder","amount":1,"unit":"tsp"},{"name":"cinnamon","amount":0.5,"unit":"tsp"},{"name":"ground ginger","amount":0.25,"unit":"tsp"},{"name":"black pepper","amount":1,"unit":"pinch"},{"name":"honey or maple syrup","amount":1,"unit":"tsp"},{"name":"coconut oil","amount":0.5,"unit":"tsp (optional)"}]'::jsonb,
 ARRAY['Combine all ingredients in a small saucepan.','Whisk to combine.','Heat over medium, stirring, until steaming — about 4 minutes.','Do not boil.','Taste and adjust sweetness.','Pour into a mug through a fine strainer if desired.'],
 3,5,1,90,2,14,3,0,10,80)

ON CONFLICT DO NOTHING;
